// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.4.0
// // LVGL version: 8.3.11
// // Project name: DA_KTMT

// #include "../ui.h"
// #include "../ui_images.h"

// void ui_Screen3_screen_init(void)
// {
//     ui_Screen3 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Panel19 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_Panel19, 163);
//     lv_obj_set_height(ui_Panel19, 454);
//     lv_obj_set_x(ui_Panel19, -299);
//     lv_obj_set_y(ui_Panel19, -6);
//     lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button18 = lv_btn_create(ui_Panel19);
//     lv_obj_set_width(ui_Button18, 119);
//     lv_obj_set_height(ui_Button18, 82);
//     lv_obj_set_x(ui_Button18, 0);
//     lv_obj_set_y(ui_Button18, 54);
//     lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);
//     lv_obj_set_style_text_color(ui_Button18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label25 = lv_label_create(ui_Button18);
//     lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label25, 0);
//     lv_obj_set_y(ui_Label25, 21);
//     lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label25, "Scheduler");

//     ui_Image19 = lv_img_create(ui_Button18);
//     lv_img_set_src(ui_Image19, &ui_img_calendar_747310_png);
//     lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image19, 0);
//     lv_obj_set_y(ui_Image19, -11);
//     lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button13 = lv_btn_create(ui_Panel19);
//     lv_obj_set_width(ui_Button13, 119);
//     lv_obj_set_height(ui_Button13, 82);
//     lv_obj_set_x(ui_Button13, 0);
//     lv_obj_set_y(ui_Button13, -160);
//     lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);
//     lv_obj_set_style_text_letter_space(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label20 = lv_label_create(ui_Button13);
//     lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label20, 0);
//     lv_obj_set_y(ui_Label20, 21);
//     lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label20, "Switch");
//     lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image14 = lv_img_create(ui_Button13);
//     lv_img_set_src(ui_Image14, &ui_img_981488682);
//     lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image14, 0);
//     lv_obj_set_y(ui_Image14, -11);
//     lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button15 = lv_btn_create(ui_Panel19);
//     lv_obj_set_width(ui_Button15, 119);
//     lv_obj_set_height(ui_Button15, 82);
//     lv_obj_set_x(ui_Button15, 0);
//     lv_obj_set_y(ui_Button15, -54);
//     lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);
//     lv_obj_set_style_text_letter_space(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label22 = lv_label_create(ui_Button15);
//     lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label22, 0);
//     lv_obj_set_y(ui_Label22, 21);
//     lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label22, "Wifi setting");
//     lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image16 = lv_img_create(ui_Button15);
//     lv_img_set_src(ui_Image16, &ui_img_wifi_12237189_png);
//     lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image16, 0);
//     lv_obj_set_y(ui_Image16, -11);
//     lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button16 = lv_btn_create(ui_Panel19);
//     lv_obj_set_width(ui_Button16, 119);
//     lv_obj_set_height(ui_Button16, 82);
//     lv_obj_set_x(ui_Button16, 0);
//     lv_obj_set_y(ui_Button16, 160);
//     lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);
//     lv_obj_set_style_text_letter_space(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label23 = lv_label_create(ui_Button16);
//     lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label23, 0);
//     lv_obj_set_y(ui_Label23, 21);
//     lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label23, "Home");
//     lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image17 = lv_img_create(ui_Button16);
//     lv_img_set_src(ui_Image17, &ui_img_home_12484335_png);
//     lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image17, 0);
//     lv_obj_set_y(ui_Image17, -11);
//     lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Panel16 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_Panel16, 340);
//     lv_obj_set_height(ui_Panel16, 58);
//     lv_obj_set_x(ui_Panel16, 39);
//     lv_obj_set_y(ui_Panel16, -180);
//     lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Panel16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Panel16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);

//     ui_Dropdown1 = lv_dropdown_create(ui_Panel16);
//     lv_dropdown_set_options(ui_Dropdown1, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
//     lv_obj_set_width(ui_Dropdown1, 68);
//     lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Dropdown1, 34);
//     lv_obj_set_y(ui_Dropdown1, 0);
//     lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



//     ui_Label6 = lv_label_create(ui_Panel16);
//     lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label6, -97);
//     lv_obj_set_y(ui_Label6, 0);
//     lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label6, "Time Setup :");
//     lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Dropdown2 = lv_dropdown_create(ui_Panel16);
//     lv_dropdown_set_options(ui_Dropdown2, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
//     lv_obj_set_width(ui_Dropdown2, 68);
//     lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Dropdown2, 124);
//     lv_obj_set_y(ui_Dropdown2, 0);
//     lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



//     ui_Label26 = lv_label_create(ui_Panel16);
//     lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label26, 79);
//     lv_obj_set_y(ui_Label26, 0);
//     lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label26, ":");
//     lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);



//     ui_Panel21 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_Panel21, 341);
//     lv_obj_set_height(ui_Panel21, 58);
//     lv_obj_set_x(ui_Panel21, 39);
//     lv_obj_set_y(ui_Panel21, -30);
//     lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Panel21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Panel21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);

//     ui_Dropdown4 = lv_dropdown_create(ui_Panel21);
//     lv_dropdown_set_options(ui_Dropdown4, "On\nOff");
//     lv_obj_set_width(ui_Dropdown4, 70);
//     lv_obj_set_height(ui_Dropdown4, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Dropdown4, 130);
//     lv_obj_set_y(ui_Dropdown4, 0);
//     lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



//     ui_Dropdown3 = lv_dropdown_create(ui_Panel21);
//     lv_dropdown_set_options(ui_Dropdown3, "Switch 1\nSwitch 2\nSwitch 3\nSwitch 4\nSwitch 5\nSwitch 6\nSwitch 7\nSwitch 8");
//     lv_obj_set_width(ui_Dropdown3, 116);
//     lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Dropdown3, -21);
//     lv_obj_set_y(ui_Dropdown3, 0);
//     lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



//     ui_Label27 = lv_label_create(ui_Panel21);
//     lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label27, -118);
//     lv_obj_set_y(ui_Label27, 0);
//     lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label27, "Switch:");
//     lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label35 = lv_label_create(ui_Panel21);
//     lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label35, 68);
//     lv_obj_set_y(ui_Label35, 0);
//     lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label35, "State:");
//     lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Panel22 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_Panel22, 340);
//     lv_obj_set_height(ui_Panel22, 58);
//     lv_obj_set_x(ui_Panel22, 39);
//     lv_obj_set_y(ui_Panel22, -105);
//     lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Panel22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Panel22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);

//     ui_Label28 = lv_label_create(ui_Panel22);
//     lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label28, -121);
//     lv_obj_set_y(ui_Label28, 0);
//     lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label28, "Date:");
//     lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TextArea3 = lv_textarea_create(ui_Panel22);
//     lv_obj_set_width(ui_TextArea3, 228);
//     lv_obj_set_height(ui_TextArea3, 44);
//     lv_obj_set_x(ui_TextArea3, 36);
//     lv_obj_set_y(ui_TextArea3, 0);
//     lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
//     lv_textarea_set_max_length(ui_TextArea3, 1000);
//     lv_textarea_set_placeholder_text(ui_TextArea3, "dd-mm-yyyy");

    
//     ui_Button19 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_Button19, 160);
//     lv_obj_set_height(ui_Button19, 60);
//     lv_obj_set_x(ui_Button19, 127);
//     lv_obj_set_y(ui_Button19, 45);
//     lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);
//     lv_obj_set_style_text_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label36 = lv_label_create(ui_Button19);
//     lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label36, 31);
//     lv_obj_set_y(ui_Label36, 2);
//     lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label36, "Show\nschedule");

//     ui_Image21 = lv_img_create(ui_Button19);
//     lv_img_set_src(ui_Image21, &ui_img_calendar_747310_png);
//     lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image21, -35);
//     lv_obj_set_y(ui_Image21, 0);
//     lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button20 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_Button20, 160);
//     lv_obj_set_height(ui_Button20, 60);
//     lv_obj_set_x(ui_Button20, -50);
//     lv_obj_set_y(ui_Button20, 45);
//     lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Button20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Button20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);

//     ui_Image22 = lv_img_create(ui_Button20);
//     lv_img_set_src(ui_Image22, &ui_img_save_button_png);
//     lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image22, -35);
//     lv_obj_set_y(ui_Image22, 0);
//     lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label37 = lv_label_create(ui_Button20);
//     lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label37, 31);
//     lv_obj_set_y(ui_Label37, 0);
//     lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label37, "  Save\nSetting");
//     lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


//     ui_Panel23 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_Panel23, 380);
//     lv_obj_set_height(ui_Panel23, 315);
//     lv_obj_set_x(ui_Panel23, 39);
//     lv_obj_set_y(ui_Panel23, 19);
//     lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Panel23, LV_OBJ_FLAG_HIDDEN);     /// Flags
//     lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     ui_object_set_themeable_style_property(ui_Panel23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
//                                            _ui_theme_color_green);
//     ui_object_set_themeable_style_property(ui_Panel23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
//                                            _ui_theme_alpha_green);

//     ui_Container1 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container1);
//     lv_obj_set_width(ui_Container1, 340);
//     lv_obj_set_height(ui_Container1, 50);
//     lv_obj_set_x(ui_Container1, 0);
//     lv_obj_set_y(ui_Container1, -120);
//     lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[0] = lv_label_create(ui_Container1);
//     lv_obj_set_width(ui_LabelSwitch[0], 210);
//     lv_obj_set_height(ui_LabelSwitch[0], 15);
//     lv_obj_set_x(ui_LabelSwitch[0], 70);
//     lv_obj_set_y(ui_LabelSwitch[0], 0);
//     lv_obj_set_align(ui_LabelSwitch[0], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[0], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[0], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[0], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label29 = lv_label_create(ui_Container1);
//     lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label29, -100);
//     lv_obj_set_y(ui_Label29, 0);
//     lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label29, "Switch 1:");
//     lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container2 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container2);
//     lv_obj_set_width(ui_Container2, 340);
//     lv_obj_set_height(ui_Container2, 50);
//     lv_obj_set_x(ui_Container2, 0);
//     lv_obj_set_y(ui_Container2, -85);
//     lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[1] = lv_label_create(ui_Container2);
//     lv_obj_set_width(ui_LabelSwitch[1], 210);
//     lv_obj_set_height(ui_LabelSwitch[1], 15);
//     lv_obj_set_x(ui_LabelSwitch[1], 70);
//     lv_obj_set_y(ui_LabelSwitch[1], 0);
//     lv_obj_set_align(ui_LabelSwitch[1], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[1], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[1], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[1], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label30 = lv_label_create(ui_Container2);
//     lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label30, -100);
//     lv_obj_set_y(ui_Label30, 0);
//     lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label30, "Switch 2:");
//     lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container3 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container3);
//     lv_obj_set_width(ui_Container3, 340);
//     lv_obj_set_height(ui_Container3, 50);
//     lv_obj_set_x(ui_Container3, 0);
//     lv_obj_set_y(ui_Container3, -50);
//     lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[2] = lv_label_create(ui_Container3);
//     lv_obj_set_width(ui_LabelSwitch[2], 210);
//     lv_obj_set_height(ui_LabelSwitch[2], 15);
//     lv_obj_set_x(ui_LabelSwitch[2], 70);
//     lv_obj_set_y(ui_LabelSwitch[2], 0);
//     lv_obj_set_align(ui_LabelSwitch[2], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[2], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[2], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[2], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label31 = lv_label_create(ui_Container3);
//     lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label31, -100);
//     lv_obj_set_y(ui_Label31, 0);
//     lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label31, "Switch 3:");
//     lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container4 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container4);
//     lv_obj_set_width(ui_Container4, 340);
//     lv_obj_set_height(ui_Container4, 50);
//     lv_obj_set_x(ui_Container4, 0);
//     lv_obj_set_y(ui_Container4, -15);
//     lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[3] = lv_label_create(ui_Container4);
//     lv_obj_set_width(ui_LabelSwitch[3], 210);
//     lv_obj_set_height(ui_LabelSwitch[3], 15);
//     lv_obj_set_x(ui_LabelSwitch[3], 70);
//     lv_obj_set_y(ui_LabelSwitch[3], 0);
//     lv_obj_set_align(ui_LabelSwitch[3], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[3], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[3], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[3], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label32 = lv_label_create(ui_Container4);
//     lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label32, -100);
//     lv_obj_set_y(ui_Label32, 0);
//     lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label32, "Switch 4:");
//     lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container5 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container5);
//     lv_obj_set_width(ui_Container5, 340);
//     lv_obj_set_height(ui_Container5, 50);
//     lv_obj_set_x(ui_Container5, 0);
//     lv_obj_set_y(ui_Container5, 20);
//     lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label33 = lv_label_create(ui_Container5);
//     lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label33, -100);
//     lv_obj_set_y(ui_Label33, 0);
//     lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label33, "Switch 5:");
//     lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_LabelSwitch[4] = lv_label_create(ui_Container5);
//     lv_obj_set_width(ui_LabelSwitch[4], 210);
//     lv_obj_set_height(ui_LabelSwitch[4], 15);
//     lv_obj_set_x(ui_LabelSwitch[4], 70);
//     lv_obj_set_y(ui_LabelSwitch[4], 0);
//     lv_obj_set_align(ui_LabelSwitch[4], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[4], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[4], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[4], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
//     ui_Container6 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container6);
//     lv_obj_set_width(ui_Container6, 340);
//     lv_obj_set_height(ui_Container6, 50);
//     lv_obj_set_x(ui_Container6, 0);
//     lv_obj_set_y(ui_Container6, 55);
//     lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label34 = lv_label_create(ui_Container6);
//     lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label34, -100);
//     lv_obj_set_y(ui_Label34, 0);
//     lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label34, "Switch 6:");
//     lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_LabelSwitch[5] = lv_label_create(ui_Container6);
//     lv_obj_set_width(ui_LabelSwitch[5], 210);
//     lv_obj_set_height(ui_LabelSwitch[5], 15);
//     lv_obj_set_x(ui_LabelSwitch[5], 70);
//     lv_obj_set_y(ui_LabelSwitch[5], 0);
//     lv_obj_set_align(ui_LabelSwitch[5], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[5], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[5], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[5], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container7 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container7);
//     lv_obj_set_width(ui_Container7, 340);
//     lv_obj_set_height(ui_Container7, 50);
//     lv_obj_set_x(ui_Container7, 0);
//     lv_obj_set_y(ui_Container7, 90);
//     lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[6] = lv_label_create(ui_Container7);
//     lv_obj_set_width(ui_LabelSwitch[6], 210);
//     lv_obj_set_height(ui_LabelSwitch[6], 15);
//     lv_obj_set_x(ui_LabelSwitch[6], 70);
//     lv_obj_set_y(ui_LabelSwitch[6], 0);
//     lv_obj_set_align(ui_LabelSwitch[6], LV_ALIGN_CENTER);  
//     lv_label_set_text(ui_LabelSwitch[6], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[6], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[6], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label38 = lv_label_create(ui_Container7);
//     lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label38, -100);
//     lv_obj_set_y(ui_Label38, 0);
//     lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label38, "Switch 7:");
//     lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container8 = lv_obj_create(ui_Panel23);
//     lv_obj_remove_style_all(ui_Container8);
//     lv_obj_set_width(ui_Container8, 340);
//     lv_obj_set_height(ui_Container8, 50);
//     lv_obj_set_x(ui_Container8, 0);
//     lv_obj_set_y(ui_Container8, 125);
//     lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_LabelSwitch[7] = lv_label_create(ui_Container8);
//     lv_obj_set_width(ui_LabelSwitch[7], 210);
//     lv_obj_set_height(ui_LabelSwitch[7], 15);
//     lv_obj_set_x(ui_LabelSwitch[7], 70);
//     lv_obj_set_y(ui_LabelSwitch[7], 0);
//     lv_obj_set_align(ui_LabelSwitch[7], LV_ALIGN_CENTER);
//     lv_label_set_text(ui_LabelSwitch[7], "No Schedule Event");
//     lv_obj_set_style_text_color(ui_LabelSwitch[7], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_LabelSwitch[7], 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label39 = lv_label_create(ui_Container8);
//     lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label39, -100);
//     lv_obj_set_y(ui_Label39, 0);
//     lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label39, "Switch 8:");
//     lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Calendar1 = lv_calendar_create(ui_Screen3);
//     lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
//     lv_obj_set_width(ui_Calendar1, 280);
//     lv_obj_set_height(ui_Calendar1, 240);
//     lv_obj_set_x(ui_Calendar1, 39);
//     lv_obj_set_y(ui_Calendar1, 55);
//     lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Calendar1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Calendar1, LV_OBJ_FLAG_HIDDEN);     /// Flags

//     lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Calendar1, ui_event_Calendar1, LV_EVENT_ALL, NULL);
// }

