// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_LightPanelSche, 90);
    lv_obj_set_height(ui_LightPanelSche, 400);
    lv_obj_set_x(ui_LightPanelSche, -283);
    lv_obj_set_y(ui_LightPanelSche, -31);
    lv_obj_set_align(ui_LightPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabelSche = lv_label_create(ui_LightPanelSche);
    lv_obj_set_width(ui_LightLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabelSche, 0);
    lv_obj_set_y(ui_LightLabelSche, -112);
    lv_obj_set_align(ui_LightLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabelSche, "LIGHT");
    lv_obj_set_style_text_color(ui_LightLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightImageSche = lv_img_create(ui_LightPanelSche);
    lv_img_set_src(ui_LightImageSche, &ui_img_314743278);
    lv_obj_set_width(ui_LightImageSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightImageSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightImageSche, -1);
    lv_obj_set_y(ui_LightImageSche, -159);
    lv_obj_set_align(ui_LightImageSche, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightImageSche, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LightImageSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightSliderSche = lv_slider_create(ui_LightPanelSche);
    lv_slider_set_value(ui_LightSliderSche, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LightSliderSche) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LightSliderSche, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_LightSliderSche, 26);
    lv_obj_set_height(ui_LightSliderSche, 263);
    lv_obj_set_x(ui_LightSliderSche, -1);
    lv_obj_set_y(ui_LightSliderSche, 41);
    lv_obj_set_align(ui_LightSliderSche, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LightSliderSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSliderSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightSliderSche, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSliderSche, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightSliderSche, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightSliderSche, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PumperPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_PumperPanelSche, 90);
    lv_obj_set_height(ui_PumperPanelSche, 400);
    lv_obj_set_x(ui_PumperPanelSche, -59);
    lv_obj_set_y(ui_PumperPanelSche, -31);
    lv_obj_set_align(ui_PumperPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PumperPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PumperPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumperPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumperPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperLabelSche = lv_label_create(ui_PumperPanelSche);
    lv_obj_set_width(ui_PumperLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperLabelSche, 0);
    lv_obj_set_y(ui_PumperLabelSche, -110);
    lv_obj_set_align(ui_PumperLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PumperLabelSche, "PUMP");
    lv_obj_set_style_text_color(ui_PumperLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumperLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperImageSche = lv_img_create(ui_PumperPanelSche);
    lv_img_set_src(ui_PumperImageSche, &ui_img_1466017491);
    lv_obj_set_width(ui_PumperImageSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperImageSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperImageSche, 0);
    lv_obj_set_y(ui_PumperImageSche, -155);
    lv_obj_set_align(ui_PumperImageSche, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PumperImageSche, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PumperImageSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PumperSliderSche = lv_slider_create(ui_PumperPanelSche);
    lv_slider_set_value(ui_PumperSliderSche, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PumperSliderSche) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PumperSliderSche, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_PumperSliderSche, 26);
    lv_obj_set_height(ui_PumperSliderSche, 263);
    lv_obj_set_x(ui_PumperSliderSche, -1);
    lv_obj_set_y(ui_PumperSliderSche, 41);
    lv_obj_set_align(ui_PumperSliderSche, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PumperSliderSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSliderSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PumperSliderSche, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSliderSche, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PumperSliderSche, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperSliderSche, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SprayerPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_SprayerPanelSche, 90);
    lv_obj_set_height(ui_SprayerPanelSche, 400);
    lv_obj_set_x(ui_SprayerPanelSche, -172);
    lv_obj_set_y(ui_SprayerPanelSche, -31);
    lv_obj_set_align(ui_SprayerPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SprayerPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SprayerPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SprayerPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SprayerPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerLabelSche = lv_label_create(ui_SprayerPanelSche);
    lv_obj_set_width(ui_SprayerLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerLabelSche, -1);
    lv_obj_set_y(ui_SprayerLabelSche, -110);
    lv_obj_set_align(ui_SprayerLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SprayerLabelSche, "SPRAYER");
    lv_obj_set_style_text_color(ui_SprayerLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SprayerLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerImageSche = lv_img_create(ui_SprayerPanelSche);
    lv_img_set_src(ui_SprayerImageSche, &ui_img_805172986);
    lv_obj_set_width(ui_SprayerImageSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerImageSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerImageSche, 1);
    lv_obj_set_y(ui_SprayerImageSche, -154);
    lv_obj_set_align(ui_SprayerImageSche, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SprayerImageSche, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SprayerImageSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SprayerSliderSche = lv_slider_create(ui_SprayerPanelSche);
    lv_slider_set_value(ui_SprayerSliderSche, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SprayerSliderSche) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SprayerSliderSche, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SprayerSliderSche, 26);
    lv_obj_set_height(ui_SprayerSliderSche, 263);
    lv_obj_set_x(ui_SprayerSliderSche, -1);
    lv_obj_set_y(ui_SprayerSliderSche, 41);
    lv_obj_set_align(ui_SprayerSliderSche, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SprayerSliderSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSliderSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SprayerSliderSche, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSliderSche, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SprayerSliderSche, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerSliderSche, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FanPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_FanPanelSche, 90);
    lv_obj_set_height(ui_FanPanelSche, 400);
    lv_obj_set_x(ui_FanPanelSche, 53);
    lv_obj_set_y(ui_FanPanelSche, -31);
    lv_obj_set_align(ui_FanPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FanPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FanPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanLabelSche = lv_label_create(ui_FanPanelSche);
    lv_obj_set_width(ui_FanLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanLabelSche, -1);
    lv_obj_set_y(ui_FanLabelSche, -106);
    lv_obj_set_align(ui_FanLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanLabelSche, "FAN");
    lv_obj_set_style_text_color(ui_FanLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanImageSche = lv_img_create(ui_FanPanelSche);
    lv_img_set_src(ui_FanImageSche, &ui_img_1839274786);
    lv_obj_set_width(ui_FanImageSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanImageSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanImageSche, 0);
    lv_obj_set_y(ui_FanImageSche, -153);
    lv_obj_set_align(ui_FanImageSche, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanImageSche, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FanImageSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FanSliderSche = lv_slider_create(ui_FanPanelSche);
    lv_slider_set_value(ui_FanSliderSche, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_FanSliderSche) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_FanSliderSche, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_FanSliderSche, 26);
    lv_obj_set_height(ui_FanSliderSche, 263);
    lv_obj_set_x(ui_FanSliderSche, -1);
    lv_obj_set_y(ui_FanSliderSche, 41);
    lv_obj_set_align(ui_FanSliderSche, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FanSliderSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSliderSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FanSliderSche, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSliderSche, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FanSliderSche, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanSliderSche, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanSliderSche, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanSliderSche, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanSliderSche, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BottomBarScreen8 = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_BottomBarScreen8, 826);
    lv_obj_set_height(ui_BottomBarScreen8, 69);
    lv_obj_set_x(ui_BottomBarScreen8, 5);
    lv_obj_set_y(ui_BottomBarScreen8, 207);
    lv_obj_set_align(ui_BottomBarScreen8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen8, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen8, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton8 = lv_btn_create(ui_BottomBarScreen8);
    lv_obj_set_width(ui_SchedulerButton8, 119);
    lv_obj_set_height(ui_SchedulerButton8, 60);
    lv_obj_set_x(ui_SchedulerButton8, 267);
    lv_obj_set_y(ui_SchedulerButton8, 0);
    lv_obj_set_align(ui_SchedulerButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton8, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel8 = lv_label_create(ui_SchedulerButton8);
    lv_obj_set_width(ui_SchedulerLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel8, 0);
    lv_obj_set_y(ui_SchedulerLabel8, 21);
    lv_obj_set_align(ui_SchedulerLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel8, "Scheduler");

    ui_SchedulerImage8 = lv_img_create(ui_SchedulerButton8);
    lv_img_set_src(ui_SchedulerImage8, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage8, 0);
    lv_obj_set_y(ui_SchedulerImage8, -11);
    lv_obj_set_align(ui_SchedulerImage8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton8 = lv_btn_create(ui_BottomBarScreen8);
    lv_obj_set_width(ui_SwitchButton8, 119);
    lv_obj_set_height(ui_SwitchButton8, 60);
    lv_obj_set_x(ui_SwitchButton8, -73);
    lv_obj_set_y(ui_SwitchButton8, 0);
    lv_obj_set_align(ui_SwitchButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton8, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel8 = lv_label_create(ui_SwitchButton8);
    lv_obj_set_width(ui_SwitchLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel8, 0);
    lv_obj_set_y(ui_SwitchLabel8, 21);
    lv_obj_set_align(ui_SwitchLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel8, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage8 = lv_img_create(ui_SwitchButton8);
    lv_img_set_src(ui_SwitchImage8, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage8, 0);
    lv_obj_set_y(ui_SwitchImage8, -11);
    lv_obj_set_align(ui_SwitchImage8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton8 = lv_btn_create(ui_BottomBarScreen8);
    lv_obj_set_width(ui_WifiButton8, 119);
    lv_obj_set_height(ui_WifiButton8, 60);
    lv_obj_set_x(ui_WifiButton8, 105);
    lv_obj_set_y(ui_WifiButton8, 0);
    lv_obj_set_align(ui_WifiButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton8, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel8 = lv_label_create(ui_WifiButton8);
    lv_obj_set_width(ui_WifiLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel8, 0);
    lv_obj_set_y(ui_WifiLabel8, 21);
    lv_obj_set_align(ui_WifiLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel8, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage8 = lv_img_create(ui_WifiButton8);
    lv_img_set_src(ui_WifiImage8, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage8, 0);
    lv_obj_set_y(ui_WifiImage8, -11);
    lv_obj_set_align(ui_WifiImage8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton8 = lv_btn_create(ui_BottomBarScreen8);
    lv_obj_set_width(ui_HomeButton8, 119);
    lv_obj_set_height(ui_HomeButton8, 60);
    lv_obj_set_x(ui_HomeButton8, -265);
    lv_obj_set_y(ui_HomeButton8, 0);
    lv_obj_set_align(ui_HomeButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton8, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButton8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButton8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel8 = lv_label_create(ui_HomeButton8);
    lv_obj_set_width(ui_HomeLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabel8, 0);
    lv_obj_set_y(ui_HomeLabel8, 21);
    lv_obj_set_align(ui_HomeLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel8, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage8 = lv_img_create(ui_HomeButton8);
    lv_img_set_src(ui_HomeImage8, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage8, 0);
    lv_obj_set_y(ui_HomeImage8, -11);
    lv_obj_set_align(ui_HomeImage8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightSwitchPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_LightSwitchPanelSche, 90);
    lv_obj_set_height(ui_LightSwitchPanelSche, 85);
    lv_obj_set_x(ui_LightSwitchPanelSche, 167);
    lv_obj_set_y(ui_LightSwitchPanelSche, -189);
    lv_obj_set_align(ui_LightSwitchPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightSwitchPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightSwitchPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightSwitchPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightSwitchPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightSwitchSche = lv_switch_create(ui_LightSwitchPanelSche);
    lv_obj_set_width(ui_LightSwitchSche, 50);
    lv_obj_set_height(ui_LightSwitchSche, 25);
    lv_obj_set_x(ui_LightSwitchSche, 0);
    lv_obj_set_y(ui_LightSwitchSche, -12);
    lv_obj_set_align(ui_LightSwitchSche, LV_ALIGN_CENTER);


    ui_LightSwitchLabelSche = lv_label_create(ui_LightSwitchPanelSche);
    lv_obj_set_width(ui_LightSwitchLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightSwitchLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightSwitchLabelSche, 1);
    lv_obj_set_y(ui_LightSwitchLabelSche, 23);
    lv_obj_set_align(ui_LightSwitchLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightSwitchLabelSche, "LIGHT");
    lv_obj_set_style_text_color(ui_LightSwitchLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightSwitchLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperSwitchPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_PumperSwitchPanelSche, 90);
    lv_obj_set_height(ui_PumperSwitchPanelSche, 85);
    lv_obj_set_x(ui_PumperSwitchPanelSche, 167);
    lv_obj_set_y(ui_PumperSwitchPanelSche, -96);
    lv_obj_set_align(ui_PumperSwitchPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PumperSwitchPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PumperSwitchPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumperSwitchPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumperSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperSwitchPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperSwitchSche = lv_switch_create(ui_PumperSwitchPanelSche);
    lv_obj_set_width(ui_PumperSwitchSche, 50);
    lv_obj_set_height(ui_PumperSwitchSche, 25);
    lv_obj_set_x(ui_PumperSwitchSche, 0);
    lv_obj_set_y(ui_PumperSwitchSche, -12);
    lv_obj_set_align(ui_PumperSwitchSche, LV_ALIGN_CENTER);


    ui_PumperSwitchLabelSche = lv_label_create(ui_PumperSwitchPanelSche);
    lv_obj_set_width(ui_PumperSwitchLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperSwitchLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperSwitchLabelSche, 1);
    lv_obj_set_y(ui_PumperSwitchLabelSche, 23);
    lv_obj_set_align(ui_PumperSwitchLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PumperSwitchLabelSche, "PUMP");
    lv_obj_set_style_text_color(ui_PumperSwitchLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumperSwitchLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerSwitchPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_SprayerSwitchPanelSche, 90);
    lv_obj_set_height(ui_SprayerSwitchPanelSche, 85);
    lv_obj_set_x(ui_SprayerSwitchPanelSche, 276);
    lv_obj_set_y(ui_SprayerSwitchPanelSche, -189);
    lv_obj_set_align(ui_SprayerSwitchPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SprayerSwitchPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SprayerSwitchPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SprayerSwitchPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SprayerSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerSwitchPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerSwitchSche = lv_switch_create(ui_SprayerSwitchPanelSche);
    lv_obj_set_width(ui_SprayerSwitchSche, 50);
    lv_obj_set_height(ui_SprayerSwitchSche, 25);
    lv_obj_set_x(ui_SprayerSwitchSche, 0);
    lv_obj_set_y(ui_SprayerSwitchSche, -12);
    lv_obj_set_align(ui_SprayerSwitchSche, LV_ALIGN_CENTER);


    ui_SprayerSwitchLabelSche = lv_label_create(ui_SprayerSwitchPanelSche);
    lv_obj_set_width(ui_SprayerSwitchLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerSwitchLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerSwitchLabelSche, 1);
    lv_obj_set_y(ui_SprayerSwitchLabelSche, 23);
    lv_obj_set_align(ui_SprayerSwitchLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SprayerSwitchLabelSche, "SPRAYER");
    lv_obj_set_style_text_color(ui_SprayerSwitchLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SprayerSwitchLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSwitchPanelSche = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_FanSwitchPanelSche, 90);
    lv_obj_set_height(ui_FanSwitchPanelSche, 85);
    lv_obj_set_x(ui_FanSwitchPanelSche, 276);
    lv_obj_set_y(ui_FanSwitchPanelSche, -96);
    lv_obj_set_align(ui_FanSwitchPanelSche, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FanSwitchPanelSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FanSwitchPanelSche, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanSwitchPanelSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanSwitchPanelSche, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanSwitchPanelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanSwitchPanelSche, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanSwitchPanelSche, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSwitchSche = lv_switch_create(ui_FanSwitchPanelSche);
    lv_obj_set_width(ui_FanSwitchSche, 50);
    lv_obj_set_height(ui_FanSwitchSche, 25);
    lv_obj_set_x(ui_FanSwitchSche, 0);
    lv_obj_set_y(ui_FanSwitchSche, -12);
    lv_obj_set_align(ui_FanSwitchSche, LV_ALIGN_CENTER);


    ui_FanSwitchLabelSche = lv_label_create(ui_FanSwitchPanelSche);
    lv_obj_set_width(ui_FanSwitchLabelSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanSwitchLabelSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanSwitchLabelSche, 1);
    lv_obj_set_y(ui_FanSwitchLabelSche, 23);
    lv_obj_set_align(ui_FanSwitchLabelSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanSwitchLabelSche, "FAN");
    lv_obj_set_style_text_color(ui_FanSwitchLabelSche, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanSwitchLabelSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventLabel = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_EventLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EventLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EventLabel, 150);
    lv_obj_set_y(ui_EventLabel, 0);
    lv_obj_set_align(ui_EventLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EventLabel, "Label:");
    lv_obj_set_style_text_color(ui_EventLabel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EventLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 151);
    lv_obj_set_y(ui_DateLabel, -36);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "Date:");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventText = lv_textarea_create(ui_Screen8);
    lv_obj_set_width(ui_EventText, 171);
    lv_obj_set_height(ui_EventText, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_EventText, 258);
    lv_obj_set_y(ui_EventText, -1);
    lv_obj_set_align(ui_EventText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_EventText, "Morning Watering");
    lv_textarea_set_one_line(ui_EventText, true);
    lv_obj_set_style_text_color(ui_EventText, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EventText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EventText, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EventText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EventText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EventText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_FromSche = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_FromSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FromSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FromSche, 151);
    lv_obj_set_y(ui_FromSche, 48);
    lv_obj_set_align(ui_FromSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FromSche, "From:");
    lv_obj_set_style_text_color(ui_FromSche, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FromSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToSche = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_ToSche, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToSche, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToSche, 161);
    lv_obj_set_y(ui_ToSche, 100);
    lv_obj_set_align(ui_ToSche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToSche, "To:");
    lv_obj_set_style_text_color(ui_ToSche, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1 = lv_checkbox_create(ui_Screen8);
    lv_checkbox_set_text(ui_Checkbox1, "Repeat every week");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, 215);
    lv_obj_set_y(ui_Checkbox1, 151);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Checkbox1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Checkbox1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_FromRollerHour = lv_roller_create(ui_Screen8);
    lv_roller_set_options(ui_FromRollerHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_FromRollerHour, 47);
    lv_obj_set_width(ui_FromRollerHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_FromRollerHour, 212);
    lv_obj_set_y(ui_FromRollerHour, 44);
    lv_obj_set_align(ui_FromRollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FromRollerHour, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FromRollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FromRollerHour, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FromRollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FromRollerMinute = lv_roller_create(ui_Screen8);
    lv_roller_set_options(ui_FromRollerMinute,
                          "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_FromRollerMinute, 47);
    lv_obj_set_width(ui_FromRollerMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_FromRollerMinute, 292);
    lv_obj_set_y(ui_FromRollerMinute, 44);
    lv_obj_set_align(ui_FromRollerMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FromRollerMinute, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FromRollerMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FromRollerMinute, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FromRollerMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, 264);
    lv_obj_set_y(ui_Label100, -36);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "Wednesday 22/10/2025");
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButtonSche = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_SaveButtonSche, 51);
    lv_obj_set_height(ui_SaveButtonSche, 40);
    lv_obj_set_x(ui_SaveButtonSche, 325);
    lv_obj_set_y(ui_SaveButtonSche, 150);
    lv_obj_set_align(ui_SaveButtonSche, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveButtonSche, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveButtonSche, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveButtonSche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButtonSche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SaveButtonSche, &ui_img_save_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDot1 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_DoubleDot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoubleDot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoubleDot1, 250);
    lv_obj_set_y(ui_DoubleDot1, 44);
    lv_obj_set_align(ui_DoubleDot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoubleDot1, ":");
    lv_obj_set_style_text_color(ui_DoubleDot1, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoubleDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDot2 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_DoubleDot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoubleDot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoubleDot2, 251);
    lv_obj_set_y(ui_DoubleDot2, 99);
    lv_obj_set_align(ui_DoubleDot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoubleDot2, ":");
    lv_obj_set_style_text_color(ui_DoubleDot2, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoubleDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_BackButton, 52);
    lv_obj_set_height(ui_BackButton, 50);
    lv_obj_set_x(ui_BackButton, -367);
    lv_obj_set_y(ui_BackButton, -200);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BackButton, &ui_img_1568750885, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BackButton, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BackButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BackButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BackButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BackButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToRollerHour = lv_roller_create(ui_Screen8);
    lv_roller_set_options(ui_ToRollerHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_ToRollerHour, 47);
    lv_obj_set_width(ui_ToRollerHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ToRollerHour, 212);
    lv_obj_set_y(ui_ToRollerHour, 97);
    lv_obj_set_align(ui_ToRollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ToRollerHour, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToRollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ToRollerHour, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToRollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToRollerMinute = lv_roller_create(ui_Screen8);
    lv_roller_set_options(ui_ToRollerMinute,
                          "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_ToRollerMinute, 47);
    lv_obj_set_width(ui_ToRollerMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ToRollerMinute, 292);
    lv_obj_set_y(ui_ToRollerMinute, 97);
    lv_obj_set_align(ui_ToRollerMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ToRollerMinute, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToRollerMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ToRollerMinute, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToRollerMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackLabel, -366);
    lv_obj_set_y(ui_BackLabel, -162);
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "Back");
    lv_obj_set_style_text_color(ui_BackLabel, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

        
    ui_KeyboardLabel = lv_keyboard_create(ui_Screen8);
    lv_obj_set_width(ui_KeyboardLabel, 500);
    lv_obj_set_height(ui_KeyboardLabel, 200);
    lv_obj_set_x(ui_KeyboardLabel, -100);
    lv_obj_set_y(ui_KeyboardLabel, 45);
    lv_obj_add_flag(ui_KeyboardLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_KeyboardLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_KeyboardLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_HourPanel1 = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_HourPanel1, 427);
    lv_obj_set_height(ui_HourPanel1, 219);
    lv_obj_set_x(ui_HourPanel1, 13);
    lv_obj_set_y(ui_HourPanel1, -28);
    lv_obj_set_align(ui_HourPanel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourPanel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HourPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourPanel1, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HourPanel1, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HourPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_OkeButton = lv_btn_create(ui_HourPanel1);
    lv_obj_set_width(ui_OkeButton, 100);
    lv_obj_set_height(ui_OkeButton, 50);
    lv_obj_set_x(ui_OkeButton, 0);
    lv_obj_set_y(ui_OkeButton, 58);
    lv_obj_set_align(ui_OkeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OkeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OkeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OkeButton, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OkeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OkeLabel = lv_label_create(ui_OkeButton);
    lv_obj_set_width(ui_OkeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OkeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OkeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OkeLabel, "OK");
    lv_obj_set_style_text_font(ui_OkeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourLabel1 = lv_label_create(ui_HourPanel1);
    lv_obj_set_width(ui_HourLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabel1, 1);
    lv_obj_set_y(ui_HourLabel1, -34);
    lv_obj_set_align(ui_HourLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourLabel1,
                      "Invalid start time and end time.\nPlease set again.");
    lv_obj_set_style_text_align(ui_HourLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OkeButton, ui_event_OkeButton, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_SchedulerButton8, ui_event_SchedulerButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton8, ui_event_SwitchButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton8, ui_event_WifiButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton8, ui_event_HomeButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);


    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8_Load, LV_EVENT_SCREEN_LOAD_START, NULL);
    lv_obj_add_event_cb(ui_SaveButtonSche, ui_event_SaveButtonSche, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_EventText, ui_event_EventText, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardLabel, ui_EventText);
    lv_obj_add_event_cb(ui_KeyboardLabel, ui_event_KeyboardLabel, LV_EVENT_ALL, NULL);
}
