// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar3 = lv_calendar_create(ui_Screen6);
    lv_obj_t * ui_Calendar3_header = lv_calendar_header_arrow_create(ui_Calendar3);
    lv_obj_set_width(ui_Calendar3, 790);
    lv_obj_set_height(ui_Calendar3, 376);
    lv_obj_set_x(ui_Calendar3, 0);
    lv_obj_set_y(ui_Calendar3, -21);
    lv_obj_set_align(ui_Calendar3, LV_ALIGN_CENTER);

    ui_BottomBarScreen6 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_BottomBarScreen6, 826);
    lv_obj_set_height(ui_BottomBarScreen6, 69);
    lv_obj_set_x(ui_BottomBarScreen6, 5);
    lv_obj_set_y(ui_BottomBarScreen6, 207);
    lv_obj_set_align(ui_BottomBarScreen6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen6, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen6, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton6 = lv_btn_create(ui_BottomBarScreen6);
    lv_obj_set_width(ui_SchedulerButton6, 119);
    lv_obj_set_height(ui_SchedulerButton6, 60);
    lv_obj_set_x(ui_SchedulerButton6, 267);
    lv_obj_set_y(ui_SchedulerButton6, 0);
    lv_obj_set_align(ui_SchedulerButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton6, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel6 = lv_label_create(ui_SchedulerButton6);
    lv_obj_set_width(ui_SchedulerLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel6, 0);
    lv_obj_set_y(ui_SchedulerLabel6, 21);
    lv_obj_set_align(ui_SchedulerLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel6, "Scheduler");

    ui_SchedulerImage6 = lv_img_create(ui_SchedulerButton6);
    lv_img_set_src(ui_SchedulerImage6, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage6, 0);
    lv_obj_set_y(ui_SchedulerImage6, -11);
    lv_obj_set_align(ui_SchedulerImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton6 = lv_btn_create(ui_BottomBarScreen6);
    lv_obj_set_width(ui_SwitchButton6, 119);
    lv_obj_set_height(ui_SwitchButton6, 60);
    lv_obj_set_x(ui_SwitchButton6, -73);
    lv_obj_set_y(ui_SwitchButton6, 0);
    lv_obj_set_align(ui_SwitchButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton6, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel6 = lv_label_create(ui_SwitchButton6);
    lv_obj_set_width(ui_SwitchLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel6, 0);
    lv_obj_set_y(ui_SwitchLabel6, 21);
    lv_obj_set_align(ui_SwitchLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel6, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage6 = lv_img_create(ui_SwitchButton6);
    lv_img_set_src(ui_SwitchImage6, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage6, 0);
    lv_obj_set_y(ui_SwitchImage6, -11);
    lv_obj_set_align(ui_SwitchImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton6 = lv_btn_create(ui_BottomBarScreen6);
    lv_obj_set_width(ui_WifiButton6, 119);
    lv_obj_set_height(ui_WifiButton6, 60);
    lv_obj_set_x(ui_WifiButton6, 105);
    lv_obj_set_y(ui_WifiButton6, 0);
    lv_obj_set_align(ui_WifiButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton6, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel6 = lv_label_create(ui_WifiButton6);
    lv_obj_set_width(ui_WifiLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel6, 0);
    lv_obj_set_y(ui_WifiLabel6, 21);
    lv_obj_set_align(ui_WifiLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel6, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage6 = lv_img_create(ui_WifiButton6);
    lv_img_set_src(ui_WifiImage6, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage6, 0);
    lv_obj_set_y(ui_WifiImage6, -11);
    lv_obj_set_align(ui_WifiImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton6 = lv_btn_create(ui_BottomBarScreen6);
    lv_obj_set_width(ui_HomeButton6, 119);
    lv_obj_set_height(ui_HomeButton6, 60);
    lv_obj_set_x(ui_HomeButton6, -265);
    lv_obj_set_y(ui_HomeButton6, 0);
    lv_obj_set_align(ui_HomeButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton6, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButton6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel6 = lv_label_create(ui_HomeButton6);
    lv_obj_set_width(ui_HomeLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabel6, 0);
    lv_obj_set_y(ui_HomeLabel6, 21);
    lv_obj_set_align(ui_HomeLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel6, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage6 = lv_img_create(ui_HomeButton6);
    lv_img_set_src(ui_HomeImage6, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage6, 0);
    lv_obj_set_y(ui_HomeImage6, -11);
    lv_obj_set_align(ui_HomeImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_DotImage = lv_img_create(ui_Screen6);
    // lv_img_set_src(ui_DotImage, &ui_img_1833007111);
    // lv_obj_set_width(ui_DotImage, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_DotImage, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_DotImage, 38);
    // lv_obj_set_y(ui_DotImage, -96);
    // lv_obj_set_align(ui_DotImage, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_DotImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    // lv_obj_clear_flag(ui_DotImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_bg_img_opa(ui_DotImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_recolor(ui_DotImage, lv_color_hex(0xFF0026), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_recolor_opa(ui_DotImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_img_recolor(ui_DotImage, lv_color_hex(0xFF0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_img_recolor_opa(ui_DotImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar6 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_TopBar6, 818);
    lv_obj_set_height(ui_TopBar6, 32);
    lv_obj_set_x(ui_TopBar6, 0);
    lv_obj_set_y(ui_TopBar6, -228);
    lv_obj_set_align(ui_TopBar6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar6, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar6, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel6 = lv_label_create(ui_TopBar6);
    lv_obj_set_width(ui_TimeLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel6, 0);
    lv_obj_set_y(ui_TimeLabel6, 0);
    lv_obj_set_align(ui_TimeLabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel6, "17:24");
    lv_obj_set_style_text_font(ui_TimeLabel6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel6 = lv_label_create(ui_TopBar6);
    lv_obj_set_width(ui_DateLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel6, -294);
    lv_obj_set_y(ui_DateLabel6, 1);
    lv_obj_set_align(ui_DateLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel6, "Wed, OCT 22 ");
    lv_obj_set_style_text_font(ui_DateLabel6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiNoti6 = lv_img_create(ui_TopBar6);
    lv_img_set_src(ui_WifiNoti6, &ui_img_1186191835);
    lv_obj_set_width(ui_WifiNoti6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiNoti6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiNoti6, 382);
    lv_obj_set_y(ui_WifiNoti6, 0);
    lv_obj_set_align(ui_WifiNoti6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiNoti6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_WifiNoti6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiNoti6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiNoti6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiNoti6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Calendar3, ui_event_Calendar3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SchedulerButton6, ui_event_SchedulerButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton6, ui_event_SwitchButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton6, ui_event_WifiButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton6, ui_event_HomeButton6, LV_EVENT_ALL, NULL);

}
