// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_LightPanel, 90);
    lv_obj_set_height(ui_LightPanel, 376);
    lv_obj_set_x(ui_LightPanel, -293);
    lv_obj_set_y(ui_LightPanel, -23);
    lv_obj_set_align(ui_LightPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel = lv_label_create(ui_LightPanel);
    lv_obj_set_width(ui_LightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabel, -1);
    lv_obj_set_y(ui_LightLabel, -116);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "LIGHT");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightImage = lv_img_create(ui_LightPanel);
    lv_img_set_src(ui_LightImage, &ui_img_314743278);
    lv_obj_set_width(ui_LightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightImage, -1);
    lv_obj_set_y(ui_LightImage, -157);
    lv_obj_set_align(ui_LightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightSlider = lv_slider_create(ui_LightPanel);
    lv_slider_set_value(ui_LightSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LightSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LightSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LightSlider, 26);
    lv_obj_set_height(ui_LightSlider, 263);
    lv_obj_set_x(ui_LightSlider, -1);
    lv_obj_set_y(ui_LightSlider, 28);
    lv_obj_set_align(ui_LightSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightSlider, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PumperPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PumperPanel, 90);
    lv_obj_set_height(ui_PumperPanel, 376);
    lv_obj_set_x(ui_PumperPanel, -82);
    lv_obj_set_y(ui_PumperPanel, -23);
    lv_obj_set_align(ui_PumperPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PumperPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PumperPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumperPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumperPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperLabel = lv_label_create(ui_PumperPanel);
    lv_obj_set_width(ui_PumperLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperLabel, 1);
    lv_obj_set_y(ui_PumperLabel, -117);
    lv_obj_set_align(ui_PumperLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PumperLabel, "PUMP");
    lv_obj_set_style_text_color(ui_PumperLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumperLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperImage = lv_img_create(ui_PumperPanel);
    lv_img_set_src(ui_PumperImage, &ui_img_1466017491);
    lv_obj_set_width(ui_PumperImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperImage, -1);
    lv_obj_set_y(ui_PumperImage, -158);
    lv_obj_set_align(ui_PumperImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PumperImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PumperImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PumperSlider = lv_slider_create(ui_PumperPanel);
    lv_slider_set_value(ui_PumperSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PumperSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PumperSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_PumperSlider, 26);
    lv_obj_set_height(ui_PumperSlider, 263);
    lv_obj_set_x(ui_PumperSlider, 1);
    lv_obj_set_y(ui_PumperSlider, 29);
    lv_obj_set_align(ui_PumperSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PumperSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PumperSlider, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PumperSlider, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperSlider, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SprayerPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SprayerPanel, 90);
    lv_obj_set_height(ui_SprayerPanel, 376);
    lv_obj_set_x(ui_SprayerPanel, -188);
    lv_obj_set_y(ui_SprayerPanel, -22);
    lv_obj_set_align(ui_SprayerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SprayerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SprayerPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SprayerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SprayerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerLabel = lv_label_create(ui_SprayerPanel);
    lv_obj_set_width(ui_SprayerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerLabel, 0);
    lv_obj_set_y(ui_SprayerLabel, -116);
    lv_obj_set_align(ui_SprayerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SprayerLabel, "SPRAYER");
    lv_obj_set_style_text_color(ui_SprayerLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SprayerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerImage = lv_img_create(ui_SprayerPanel);
    lv_img_set_src(ui_SprayerImage, &ui_img_805172986);
    lv_obj_set_width(ui_SprayerImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerImage, 0);
    lv_obj_set_y(ui_SprayerImage, -157);
    lv_obj_set_align(ui_SprayerImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SprayerImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SprayerImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SprayerSlider = lv_slider_create(ui_SprayerPanel);
    lv_slider_set_value(ui_SprayerSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SprayerSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SprayerSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SprayerSlider, 26);
    lv_obj_set_height(ui_SprayerSlider, 263);
    lv_obj_set_x(ui_SprayerSlider, -1);
    lv_obj_set_y(ui_SprayerSlider, 29);
    lv_obj_set_align(ui_SprayerSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SprayerSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SprayerSlider, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SprayerSlider, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerSlider, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FanPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_FanPanel, 90);
    lv_obj_set_height(ui_FanPanel, 376);
    lv_obj_set_x(ui_FanPanel, 23);
    lv_obj_set_y(ui_FanPanel, -22);
    lv_obj_set_align(ui_FanPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FanPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FanPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanLabel = lv_label_create(ui_FanPanel);
    lv_obj_set_width(ui_FanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanLabel, 0);
    lv_obj_set_y(ui_FanLabel, -118);
    lv_obj_set_align(ui_FanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanLabel, "FAN");
    lv_obj_set_style_text_color(ui_FanLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanImage = lv_img_create(ui_FanPanel);
    lv_img_set_src(ui_FanImage, &ui_img_1839274786);
    lv_obj_set_width(ui_FanImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanImage, 0);
    lv_obj_set_y(ui_FanImage, -154);
    lv_obj_set_align(ui_FanImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FanImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FanSlider = lv_slider_create(ui_FanPanel);
    lv_slider_set_value(ui_FanSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_FanSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_FanSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FanSlider, 26);
    lv_obj_set_height(ui_FanSlider, 263);
    lv_obj_set_x(ui_FanSlider, 0);
    lv_obj_set_y(ui_FanSlider, 30);
    lv_obj_set_align(ui_FanSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FanSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FanSlider, lv_color_hex(0x92EAA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FanSlider, lv_color_hex(0x8ADB8A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanSlider, lv_color_hex(0x71B45C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BottomBarScreen2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_BottomBarScreen2, 826);
    lv_obj_set_height(ui_BottomBarScreen2, 69);
    lv_obj_set_x(ui_BottomBarScreen2, 5);
    lv_obj_set_y(ui_BottomBarScreen2, 207);
    lv_obj_set_align(ui_BottomBarScreen2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen2, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen2, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton2 = lv_btn_create(ui_BottomBarScreen2);
    lv_obj_set_width(ui_SchedulerButton2, 119);
    lv_obj_set_height(ui_SchedulerButton2, 60);
    lv_obj_set_x(ui_SchedulerButton2, 267);
    lv_obj_set_y(ui_SchedulerButton2, 0);
    lv_obj_set_align(ui_SchedulerButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton2, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel2 = lv_label_create(ui_SchedulerButton2);
    lv_obj_set_width(ui_SchedulerLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel2, 0);
    lv_obj_set_y(ui_SchedulerLabel2, 21);
    lv_obj_set_align(ui_SchedulerLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel2, "Scheduler");

    ui_SchedulerImage2 = lv_img_create(ui_SchedulerButton2);
    lv_img_set_src(ui_SchedulerImage2, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage2, 0);
    lv_obj_set_y(ui_SchedulerImage2, -11);
    lv_obj_set_align(ui_SchedulerImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton2 = lv_btn_create(ui_BottomBarScreen2);
    lv_obj_set_width(ui_SwitchButton2, 119);
    lv_obj_set_height(ui_SwitchButton2, 60);
    lv_obj_set_x(ui_SwitchButton2, -73);
    lv_obj_set_y(ui_SwitchButton2, 0);
    lv_obj_set_align(ui_SwitchButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton2, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel2 = lv_label_create(ui_SwitchButton2);
    lv_obj_set_width(ui_SwitchLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel2, 0);
    lv_obj_set_y(ui_SwitchLabel2, 21);
    lv_obj_set_align(ui_SwitchLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel2, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage2 = lv_img_create(ui_SwitchButton2);
    lv_img_set_src(ui_SwitchImage2, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage2, 0);
    lv_obj_set_y(ui_SwitchImage2, -11);
    lv_obj_set_align(ui_SwitchImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton2 = lv_btn_create(ui_BottomBarScreen2);
    lv_obj_set_width(ui_WifiButton2, 119);
    lv_obj_set_height(ui_WifiButton2, 60);
    lv_obj_set_x(ui_WifiButton2, 105);
    lv_obj_set_y(ui_WifiButton2, 0);
    lv_obj_set_align(ui_WifiButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton2, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel2 = lv_label_create(ui_WifiButton2);
    lv_obj_set_width(ui_WifiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel2, 0);
    lv_obj_set_y(ui_WifiLabel2, 21);
    lv_obj_set_align(ui_WifiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel2, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage2 = lv_img_create(ui_WifiButton2);
    lv_img_set_src(ui_WifiImage2, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage2, 0);
    lv_obj_set_y(ui_WifiImage2, -11);
    lv_obj_set_align(ui_WifiImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton2 = lv_btn_create(ui_BottomBarScreen2);
    lv_obj_set_width(ui_HomeButton2, 119);
    lv_obj_set_height(ui_HomeButton2, 60);
    lv_obj_set_x(ui_HomeButton2, -265);
    lv_obj_set_y(ui_HomeButton2, 0);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton2, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButton2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel2 = lv_label_create(ui_HomeButton2);
    lv_obj_set_width(ui_HomeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabel2, 0);
    lv_obj_set_y(ui_HomeLabel2, 21);
    lv_obj_set_align(ui_HomeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel2, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage2 = lv_img_create(ui_HomeButton2);
    lv_img_set_src(ui_HomeImage2, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage2, 0);
    lv_obj_set_y(ui_HomeImage2, -11);
    lv_obj_set_align(ui_HomeImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightSwitchPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_LightSwitchPanel, 90);
    lv_obj_set_height(ui_LightSwitchPanel, 85);
    lv_obj_set_x(ui_LightSwitchPanel, 137);
    lv_obj_set_y(ui_LightSwitchPanel, -166);
    lv_obj_set_align(ui_LightSwitchPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightSwitchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightSwitchPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightSwitchPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LightSwitchPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LightSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LightSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LightSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LightSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LightSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightSwitch = lv_switch_create(ui_LightSwitchPanel);
    lv_obj_set_width(ui_LightSwitch, 50);
    lv_obj_set_height(ui_LightSwitch, 25);
    lv_obj_set_x(ui_LightSwitch, 0);
    lv_obj_set_y(ui_LightSwitch, -12);
    lv_obj_set_align(ui_LightSwitch, LV_ALIGN_CENTER);

    ui_LightSwitchLabel = lv_label_create(ui_LightSwitchPanel);
    lv_obj_set_width(ui_LightSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightSwitchLabel, 1);
    lv_obj_set_y(ui_LightSwitchLabel, 23);
    lv_obj_set_align(ui_LightSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightSwitchLabel, "LIGHT");
    lv_obj_set_style_text_color(ui_LightSwitchLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightSwitchLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperSwitchPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PumperSwitchPanel, 90);
    lv_obj_set_height(ui_PumperSwitchPanel, 85);
    lv_obj_set_x(ui_PumperSwitchPanel, 137);
    lv_obj_set_y(ui_PumperSwitchPanel, -74);
    lv_obj_set_align(ui_PumperSwitchPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PumperSwitchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PumperSwitchPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumperSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumperSwitchPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumperSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PumperSwitchPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PumperSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PumperSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PumperSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PumperSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PumperSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumperSwitch = lv_switch_create(ui_PumperSwitchPanel);
    lv_obj_set_width(ui_PumperSwitch, 50);
    lv_obj_set_height(ui_PumperSwitch, 25);
    lv_obj_set_x(ui_PumperSwitch, 0);
    lv_obj_set_y(ui_PumperSwitch, -12);
    lv_obj_set_align(ui_PumperSwitch, LV_ALIGN_CENTER);

    ui_PumperSwitchLabel = lv_label_create(ui_PumperSwitchPanel);
    lv_obj_set_width(ui_PumperSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumperSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumperSwitchLabel, 1);
    lv_obj_set_y(ui_PumperSwitchLabel, 23);
    lv_obj_set_align(ui_PumperSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PumperSwitchLabel, "PUMP");
    lv_obj_set_style_text_color(ui_PumperSwitchLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumperSwitchLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerSwitchPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SprayerSwitchPanel, 90);
    lv_obj_set_height(ui_SprayerSwitchPanel, 85);
    lv_obj_set_x(ui_SprayerSwitchPanel, 240);
    lv_obj_set_y(ui_SprayerSwitchPanel, -167);
    lv_obj_set_align(ui_SprayerSwitchPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SprayerSwitchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SprayerSwitchPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SprayerSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SprayerSwitchPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SprayerSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SprayerSwitchPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SprayerSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SprayerSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SprayerSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SprayerSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SprayerSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SprayerSwitch = lv_switch_create(ui_SprayerSwitchPanel);
    lv_obj_set_width(ui_SprayerSwitch, 50);
    lv_obj_set_height(ui_SprayerSwitch, 25);
    lv_obj_set_x(ui_SprayerSwitch, 0);
    lv_obj_set_y(ui_SprayerSwitch, -12);
    lv_obj_set_align(ui_SprayerSwitch, LV_ALIGN_CENTER);

    ui_SprayerSwitchLabel = lv_label_create(ui_SprayerSwitchPanel);
    lv_obj_set_width(ui_SprayerSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SprayerSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SprayerSwitchLabel, 1);
    lv_obj_set_y(ui_SprayerSwitchLabel, 23);
    lv_obj_set_align(ui_SprayerSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SprayerSwitchLabel, "SPRAYER");
    lv_obj_set_style_text_color(ui_SprayerSwitchLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SprayerSwitchLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSwitchPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_FanSwitchPanel, 90);
    lv_obj_set_height(ui_FanSwitchPanel, 85);
    lv_obj_set_x(ui_FanSwitchPanel, 239);
    lv_obj_set_y(ui_FanSwitchPanel, -73);
    lv_obj_set_align(ui_FanSwitchPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FanSwitchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FanSwitchPanel, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanSwitchPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanSwitchPanel, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanSwitchPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanSwitchPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_FanSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_FanSwitchPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSwitch = lv_switch_create(ui_FanSwitchPanel);
    lv_obj_set_width(ui_FanSwitch, 50);
    lv_obj_set_height(ui_FanSwitch, 25);
    lv_obj_set_x(ui_FanSwitch, 0);
    lv_obj_set_y(ui_FanSwitch, -12);
    lv_obj_set_align(ui_FanSwitch, LV_ALIGN_CENTER);

    ui_FanSwitchLabel = lv_label_create(ui_FanSwitchPanel);
    lv_obj_set_width(ui_FanSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanSwitchLabel, 1);
    lv_obj_set_y(ui_FanSwitchLabel, 23);
    lv_obj_set_align(ui_FanSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanSwitchLabel, "FAN");
    lv_obj_set_style_text_color(ui_FanSwitchLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanSwitchLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_TopBar2, 818);
    lv_obj_set_height(ui_TopBar2, 32);
    lv_obj_set_x(ui_TopBar2, 0);
    lv_obj_set_y(ui_TopBar2, -228);
    lv_obj_set_align(ui_TopBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar2, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar2, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_TimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel2, 0);
    lv_obj_set_y(ui_TimeLabel2, 0);
    lv_obj_set_align(ui_TimeLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel2, "17:24");
    lv_obj_set_style_text_font(ui_TimeLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_DateLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel2, -294);
    lv_obj_set_y(ui_DateLabel2, 1);
    lv_obj_set_align(ui_DateLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel2, "Wed, OCT 22 ");
    lv_obj_set_style_text_font(ui_DateLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiNoti2 = lv_img_create(ui_TopBar2);
    lv_img_set_src(ui_WifiNoti2, &ui_img_1186191835);
    lv_obj_set_width(ui_WifiNoti2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiNoti2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiNoti2, 382);
    lv_obj_set_y(ui_WifiNoti2, 0);
    lv_obj_set_align(ui_WifiNoti2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiNoti2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_WifiNoti2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiNoti2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiNoti2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiNoti2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 118);
    lv_obj_set_y(ui_Date, 22);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "Date:");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date2, 239);
    lv_obj_set_y(ui_Date2, 23);
    lv_obj_set_align(ui_Date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date2, "Wednesday 22/10/2025");
    lv_obj_set_style_text_color(ui_Date2, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnGoingEvent = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_OnGoingEvent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnGoingEvent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnGoingEvent, 500);
    lv_obj_set_y(ui_OnGoingEvent, 66);
    lv_obj_set_align(ui_OnGoingEvent, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OnGoingEvent, "On going event: ");
    lv_obj_set_style_text_color(ui_OnGoingEvent, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnGoingEvent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Event, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event, 629);
    lv_obj_set_y(ui_Event, 66);
    lv_obj_set_align(ui_Event, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event, "Morning Wartering");
    lv_obj_set_style_text_color(ui_Event, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReloadButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ReloadButton, 52);
    lv_obj_set_height(ui_ReloadButton, 50);
    lv_obj_set_x(ui_ReloadButton, 341);
    lv_obj_set_y(ui_ReloadButton, -183);
    lv_obj_set_align(ui_ReloadButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReloadButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReloadButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReloadButton, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReloadButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ReloadButton, &ui_img_380898346, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReloadButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReloadButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReloadButton, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReloadButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReloadButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReloadButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ReloadButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ReloadButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReloadLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ReloadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReloadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReloadLabel, 343);
    lv_obj_set_y(ui_ReloadLabel, -142);
    lv_obj_set_align(ui_ReloadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReloadLabel, "Reload");
    lv_obj_set_style_text_color(ui_ReloadLabel, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReloadLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_From = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_From, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_From, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_From, 123);
    lv_obj_set_y(ui_From, 108);
    lv_obj_set_align(ui_From, LV_ALIGN_CENTER);
    lv_label_set_text(ui_From, "From:");
    lv_obj_set_style_text_color(ui_From, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_From, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_To_ = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_To_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_To_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_To_, 245);
    lv_obj_set_y(ui_To_, 108);
    lv_obj_set_align(ui_To_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_To_, "To:");
    lv_obj_set_style_text_color(ui_To_, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_To_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FromTime = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_FromTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FromTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FromTime, 182);
    lv_obj_set_y(ui_FromTime, 109);
    lv_obj_set_align(ui_FromTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FromTime, "6:00 ");
    lv_obj_set_style_text_color(ui_FromTime, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FromTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToTime = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ToTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToTime, 291);
    lv_obj_set_y(ui_ToTime, 109);
    lv_obj_set_align(ui_ToTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToTime, "7:00");
    lv_obj_set_style_text_color(ui_ToTime, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_SaveButton, 52);
    lv_obj_set_height(ui_SaveButton, 50);
    lv_obj_set_x(ui_SaveButton, 342);
    lv_obj_set_y(ui_SaveButton, -88);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0xB4C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SaveButton, &ui_img_save_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SaveButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SaveButton, lv_color_hex(0xD5D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SaveButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SaveButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabel, 344);
    lv_obj_set_y(ui_SaveLabel, -45);
    lv_obj_set_align(ui_SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabel, "Save");
    lv_obj_set_style_text_color(ui_SaveLabel, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningPanel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_WarningPanel1, 427);
    lv_obj_set_height(ui_WarningPanel1, 219);
    lv_obj_set_x(ui_WarningPanel1, 13);
    lv_obj_set_y(ui_WarningPanel1, -28);
    lv_obj_set_align(ui_WarningPanel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningPanel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WarningPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WarningPanel1, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningPanel1, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YesButton1 = lv_btn_create(ui_WarningPanel1);
    lv_obj_set_width(ui_YesButton1, 100);
    lv_obj_set_height(ui_YesButton1, 50);
    lv_obj_set_x(ui_YesButton1, -92);
    lv_obj_set_y(ui_YesButton1, 59);
    lv_obj_set_align(ui_YesButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YesButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_YesButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YesButton1, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YesButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YesLabel1 = lv_label_create(ui_YesButton1);
    lv_obj_set_width(ui_YesLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YesLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_YesLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YesLabel1, "YES");
    lv_obj_set_style_text_font(ui_YesLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoButton1 = lv_btn_create(ui_WarningPanel1);
    lv_obj_set_width(ui_NoButton1, 100);
    lv_obj_set_height(ui_NoButton1, 50);
    lv_obj_set_x(ui_NoButton1, 97);
    lv_obj_set_y(ui_NoButton1, 58);
    lv_obj_set_align(ui_NoButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NoButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NoButton1, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoLabel1 = lv_label_create(ui_NoButton1);
    lv_obj_set_width(ui_NoLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NoLabel1, "NO");
    lv_obj_set_style_text_font(ui_NoLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningLabel1 = lv_label_create(ui_WarningPanel1);
    lv_obj_set_width(ui_WarningLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningLabel1, 1);
    lv_obj_set_y(ui_WarningLabel1, -34);
    lv_obj_set_align(ui_WarningLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningLabel1,
                      "Do you really want to disable\ncurrent event and overwrite\n with these settings?");
    lv_obj_set_style_text_align(ui_WarningLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SchedulerButton2, ui_event_SchedulerButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton2, ui_event_SwitchButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton2, ui_event_WifiButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_YesButton1, ui_event_YesButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NoButton1, ui_event_NoButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2_Load, LV_EVENT_SCREEN_LOAD_START, NULL);
    lv_obj_add_event_cb(ui_ReloadButton, ui_event_ReloadButton, LV_EVENT_ALL, NULL);
}