// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomBarScreen1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomBarScreen1, 826);
    lv_obj_set_height(ui_BottomBarScreen1, 69);
    lv_obj_set_x(ui_BottomBarScreen1, 5);
    lv_obj_set_y(ui_BottomBarScreen1, 207);
    lv_obj_set_align(ui_BottomBarScreen1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen1, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen1, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton1 = lv_btn_create(ui_BottomBarScreen1);
    lv_obj_set_width(ui_SchedulerButton1, 119);
    lv_obj_set_height(ui_SchedulerButton1, 60);
    lv_obj_set_x(ui_SchedulerButton1, 267);
    lv_obj_set_y(ui_SchedulerButton1, 0);
    lv_obj_set_align(ui_SchedulerButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton1, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel1 = lv_label_create(ui_SchedulerButton1);
    lv_obj_set_width(ui_SchedulerLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel1, 0);
    lv_obj_set_y(ui_SchedulerLabel1, 21);
    lv_obj_set_align(ui_SchedulerLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel1, "Scheduler");

    ui_SchedulerImage1 = lv_img_create(ui_SchedulerButton1);
    lv_img_set_src(ui_SchedulerImage1, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage1, 0);
    lv_obj_set_y(ui_SchedulerImage1, -11);
    lv_obj_set_align(ui_SchedulerImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton1 = lv_btn_create(ui_BottomBarScreen1);
    lv_obj_set_width(ui_SwitchButton1, 119);
    lv_obj_set_height(ui_SwitchButton1, 60);
    lv_obj_set_x(ui_SwitchButton1, -73);
    lv_obj_set_y(ui_SwitchButton1, 0);
    lv_obj_set_align(ui_SwitchButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton1, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel1 = lv_label_create(ui_SwitchButton1);
    lv_obj_set_width(ui_SwitchLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel1, 0);
    lv_obj_set_y(ui_SwitchLabel1, 21);
    lv_obj_set_align(ui_SwitchLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel1, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage1 = lv_img_create(ui_SwitchButton1);
    lv_img_set_src(ui_SwitchImage1, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage1, 0);
    lv_obj_set_y(ui_SwitchImage1, -11);
    lv_obj_set_align(ui_SwitchImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton1 = lv_btn_create(ui_BottomBarScreen1);
    lv_obj_set_width(ui_WifiButton1, 119);
    lv_obj_set_height(ui_WifiButton1, 60);
    lv_obj_set_x(ui_WifiButton1, 105);
    lv_obj_set_y(ui_WifiButton1, 0);
    lv_obj_set_align(ui_WifiButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton1, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel1 = lv_label_create(ui_WifiButton1);
    lv_obj_set_width(ui_WifiLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel1, 0);
    lv_obj_set_y(ui_WifiLabel1, 21);
    lv_obj_set_align(ui_WifiLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel1, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage1 = lv_img_create(ui_WifiButton1);
    lv_img_set_src(ui_WifiImage1, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage1, 0);
    lv_obj_set_y(ui_WifiImage1, -11);
    lv_obj_set_align(ui_WifiImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton1 = lv_btn_create(ui_BottomBarScreen1);
    lv_obj_set_width(ui_HomeButton1, 119);
    lv_obj_set_height(ui_HomeButton1, 60);
    lv_obj_set_x(ui_HomeButton1, -265);
    lv_obj_set_y(ui_HomeButton1, 0);
    lv_obj_set_align(ui_HomeButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButton1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel1 = lv_label_create(ui_HomeButton1);
    lv_obj_set_width(ui_HomeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabel1, 0);
    lv_obj_set_y(ui_HomeLabel1, 21);
    lv_obj_set_align(ui_HomeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel1, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_HomeImage1 = lv_img_create(ui_HomeButton1);
    lv_img_set_src(ui_HomeImage1, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage1, 0);
    lv_obj_set_y(ui_HomeImage1, -11);
    lv_obj_set_align(ui_HomeImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MonitorPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MonitorPanel, 452);
    lv_obj_set_height(ui_MonitorPanel, 74);
    lv_obj_set_x(ui_MonitorPanel, 0);
    lv_obj_set_y(ui_MonitorPanel, -163);
    lv_obj_set_align(ui_MonitorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MonitorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MonitorPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MonitorPanel, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MonitorPanel, lv_color_hex(0x9D9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MonitorPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MonitorPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_MonitorPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_MonitorPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_MonitorPanel);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_TempLabel, -11);
    lv_obj_set_y(ui_TempLabel, 1);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempLabel, "30°C");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xD59233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidLabel = lv_label_create(ui_MonitorPanel);
    lv_obj_set_width(ui_HumidLabel, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_HumidLabel, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_HumidLabel, 222);
    lv_obj_set_y(ui_HumidLabel, 1);
    lv_obj_set_align(ui_HumidLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HumidLabel, "80%");
    lv_obj_set_style_text_color(ui_HumidLabel, lv_color_hex(0x29B3C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempImage = lv_img_create(ui_MonitorPanel);
    lv_img_set_src(ui_TempImage, &ui_img_857429126);
    lv_obj_set_width(ui_TempImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempImage, -42);
    lv_obj_set_y(ui_TempImage, 0);
    lv_obj_set_align(ui_TempImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempImage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidImage = lv_img_create(ui_MonitorPanel);
    lv_img_set_src(ui_HumidImage, &ui_img_humidity_11682360_png);
    lv_obj_set_width(ui_HumidImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidImage, 177);
    lv_obj_set_y(ui_HumidImage, 0);
    lv_obj_set_align(ui_HumidImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HumidImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_ChartPanel, 691);
    lv_obj_set_height(ui_ChartPanel, 283);
    lv_obj_set_x(ui_ChartPanel, 0);
    lv_obj_set_y(ui_ChartPanel, 23);
    lv_obj_set_align(ui_ChartPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChartPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChartPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ChartPanel, lv_color_hex(0x9D9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ChartPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ChartPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ChartPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ChartPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ChartPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_ChartPanel);
    lv_obj_set_width(ui_Chart2, 572);
    lv_obj_set_height(ui_Chart2, 236);
    lv_obj_set_x(ui_Chart2, 0);
    lv_obj_set_y(ui_Chart2, -5);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 40);
    lv_chart_set_div_line_count(ui_Chart2, 10, 20);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 7, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 6, 5, true, 25);
     ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xD59233),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x29B3C2),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart2, lv_color_hex(0xD7D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0xD2D2D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TopBar1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopBar1, 818);
    lv_obj_set_height(ui_TopBar1, 32);
    lv_obj_set_x(ui_TopBar1, 0);
    lv_obj_set_y(ui_TopBar1, -228);
    lv_obj_set_align(ui_TopBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar1, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar1, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel1 = lv_label_create(ui_TopBar1);
    lv_obj_set_width(ui_TimeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel1, 0);
    lv_obj_set_y(ui_TimeLabel1, 0);
    lv_obj_set_align(ui_TimeLabel1, LV_ALIGN_LEFT_MID);
lv_label_set_text(ui_TimeLabel1, "17:24");
    lv_obj_set_style_text_font(ui_TimeLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel1 = lv_label_create(ui_TopBar1);
    lv_obj_set_width(ui_DateLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel1, -294);
    lv_obj_set_y(ui_DateLabel1, 1);
    lv_obj_set_align(ui_DateLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel1, "Wed, OCT 22 ");
    lv_obj_set_style_text_font(ui_DateLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiNoti1 = lv_img_create(ui_TopBar1);
    lv_img_set_src(ui_WifiNoti1, &ui_img_1186191835);
    lv_obj_set_width(ui_WifiNoti1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiNoti1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiNoti1, 382);
    lv_obj_set_y(ui_WifiNoti1, 0);
    lv_obj_set_align(ui_WifiNoti1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiNoti1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_add_flag(ui_WifiNoti1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_WifiNoti1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiNoti1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiNoti1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SchedulerButton1, ui_event_SchedulerButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton1, ui_event_SwitchButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton1, ui_event_WifiButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
    
}