// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.4.0
// // LVGL version: 8.3.11
// // Project name: DA_KTMT

// #include "../ui.h"
// #include "../ui_images.h"

// void ui_Screen5_screen_init(void)
// {
//     ui_Screen5 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image28 = lv_img_create(ui_Screen5);
//     lv_img_set_src(ui_Image28, &ui_img_wifi_12237189_png);
//     lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image28, 14);
//     lv_obj_set_y(ui_Image28, -174);
//     lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Panel3 = lv_obj_create(ui_Screen5);
//     lv_obj_set_width(ui_Panel3, 785);
//     lv_obj_set_height(ui_Panel3, 331);
//     lv_obj_set_x(ui_Panel3, 0);
//     lv_obj_set_y(ui_Panel3, 29);
//     lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TextArea1 = lv_textarea_create(ui_Panel3);
//     lv_obj_set_width(ui_TextArea1, 713);
//     lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 44
//     lv_obj_set_x(ui_TextArea1, 3);
//     lv_obj_set_y(ui_TextArea1, -134);
//     lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_TextArea1, "Wifi SSID...");
//     lv_textarea_set_one_line(ui_TextArea1, true);
//     lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TextArea2 = lv_textarea_create(ui_Panel3);
//     lv_obj_set_width(ui_TextArea2, 713);
//     lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 44
//     lv_obj_set_x(ui_TextArea2, 3);
//     lv_obj_set_y(ui_TextArea2, -81);
//     lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_TextArea2, "Wifi password...");
//     lv_textarea_set_one_line(ui_TextArea2, true);
//     lv_textarea_set_password_mode(ui_TextArea2, true);
//     lv_obj_clear_flag(ui_TextArea2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_TextArea2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Keyboard1 = lv_keyboard_create(ui_Panel3);
//     lv_obj_set_width(ui_Keyboard1, 708);
//     lv_obj_set_height(ui_Keyboard1, 200);
//     lv_obj_set_x(ui_Keyboard1, 3);
//     lv_obj_set_y(ui_Keyboard1, 45);
//     lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
//     lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_blend_mode(ui_Keyboard1, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);

//     ui_Keyboard2 = lv_keyboard_create(ui_Panel3);
//     lv_obj_set_width(ui_Keyboard2, 708);
//     lv_obj_set_height(ui_Keyboard2, 200);
//     lv_obj_set_x(ui_Keyboard2, 3);
//     lv_obj_set_y(ui_Keyboard2, 45);
//     lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
//     lv_obj_set_style_radius(ui_Keyboard2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_radius(ui_Keyboard2, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_blend_mode(ui_Keyboard2, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);

//     ui_Panel9 = lv_obj_create(ui_Screen5);
//     lv_obj_set_width(ui_Panel9, 543);
//     lv_obj_set_height(ui_Panel9, 260);
//     lv_obj_set_x(ui_Panel9, 8);
//     lv_obj_set_y(ui_Panel9, -50);
//     lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Panel9, LV_OBJ_FLAG_HIDDEN);     /// Flags
//     lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label10 = lv_label_create(ui_Panel9);
//     lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label10, 0);
//     lv_obj_set_y(ui_Label10, 50);
//     lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label10, "Wifi connecting, please wait...");

//     ui_Spinner1 = lv_roller_create(ui_Panel9);
//     //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
//     lv_obj_set_width(ui_Spinner1, 66);
//     lv_obj_set_height(ui_Spinner1, 63);
//     lv_obj_set_x(ui_Spinner1, 0);
//     lv_obj_set_y(ui_Spinner1, -34);
//     lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

//     lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

//     ui_Panel8 = lv_obj_create(ui_Screen5);
//     lv_obj_set_width(ui_Panel8, 645);
//     lv_obj_set_height(ui_Panel8, 300);
//     lv_obj_set_x(ui_Panel8, 4);
//     lv_obj_set_y(ui_Panel8, -48);
//     lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Panel8, LV_OBJ_FLAG_HIDDEN);     /// Flags
//     lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label12 = lv_label_create(ui_Panel8);
//     lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label12, 0);
//     lv_obj_set_y(ui_Label12, 3);
//     lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label12,
//                       "	  Please type in your Wi-Fi settings first \nbefore proceeding to another application!");

//     ui_Image2 = lv_img_create(ui_Panel8);
//     lv_img_set_src(ui_Image2, &ui_img_1384146481);
//     lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image2, 0);
//     lv_obj_set_y(ui_Image2, -74);
//     lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0xB33737), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_img_recolor_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Button8 = lv_btn_create(ui_Panel8);
//     lv_obj_set_width(ui_Button8, 86);
//     lv_obj_set_height(ui_Button8, 34);
//     lv_obj_set_x(ui_Button8, 296);
//     lv_obj_set_y(ui_Button8, 192);
//     lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label13 = lv_label_create(ui_Button8);
//     lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label13, "OK");

//     ui_Panel17 = lv_obj_create(ui_Screen5);
//     lv_obj_set_width(ui_Panel17, 826);
//     lv_obj_set_height(ui_Panel17, 69);
//     lv_obj_set_x(ui_Panel17, 5);
//     lv_obj_set_y(ui_Panel17, 207);
//     lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Button10 = lv_btn_create(ui_Panel17);
//     lv_obj_set_width(ui_Button10, 119);
//     lv_obj_set_height(ui_Button10, 60);
//     lv_obj_set_x(ui_Button10, 267);
//     lv_obj_set_y(ui_Button10, 0);
//     lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label17 = lv_label_create(ui_Button10);
//     lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label17, 0);
//     lv_obj_set_y(ui_Label17, 21);
//     lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label17, "Scheduler");

//     ui_Image10 = lv_img_create(ui_Button10);
//     lv_img_set_src(ui_Image10, &ui_img_calendar_747310_png);
//     lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image10, 0);
//     lv_obj_set_y(ui_Image10, -11);
//     lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button2 = lv_btn_create(ui_Panel17);
//     lv_obj_set_width(ui_Button2, 119);
//     lv_obj_set_height(ui_Button2, 60);
//     lv_obj_set_x(ui_Button2, -73);
//     lv_obj_set_y(ui_Button2, 0);
//     lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label5 = lv_label_create(ui_Button2);
//     lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label5, 0);
//     lv_obj_set_y(ui_Label5, 21);
//     lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label5, "Switch");
//     lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image7 = lv_img_create(ui_Button2);
//     lv_img_set_src(ui_Image7, &ui_img_981488682);
//     lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image7, 0);
//     lv_obj_set_y(ui_Image7, -11);
//     lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button3 = lv_btn_create(ui_Panel17);
//     lv_obj_set_width(ui_Button3, 119);
//     lv_obj_set_height(ui_Button3, 60);
//     lv_obj_set_x(ui_Button3, 105);
//     lv_obj_set_y(ui_Button3, 0);
//     lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label15 = lv_label_create(ui_Button3);
//     lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label15, 0);
//     lv_obj_set_y(ui_Label15, 21);
//     lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label15, "Wifi setting");
//     lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image8 = lv_img_create(ui_Button3);
//     lv_img_set_src(ui_Image8, &ui_img_wifi_12237189_png);
//     lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image8, 0);
//     lv_obj_set_y(ui_Image8, -11);
//     lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Button17 = lv_btn_create(ui_Panel17);
//     lv_obj_set_width(ui_Button17, 119);
//     lv_obj_set_height(ui_Button17, 60);
//     lv_obj_set_x(ui_Button17, -265);
//     lv_obj_set_y(ui_Button17, 0);
//     lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_letter_space(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_line_space(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(ui_Button17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label24 = lv_label_create(ui_Button17);
//     lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label24, 0);
//     lv_obj_set_y(ui_Label24, 21);
//     lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label24, "Home");
//     lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Image20 = lv_img_create(ui_Button17);
//     lv_img_set_src(ui_Image20, &ui_img_home_12484335_png);
//     lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Image20, 0);
//     lv_obj_set_y(ui_Image20, -11);
//     lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Panel7 = lv_obj_create(ui_Screen5);
//     lv_obj_set_width(ui_Panel7, 818);
//     lv_obj_set_height(ui_Panel7, 32);
//     lv_obj_set_x(ui_Panel7, 0);
//     lv_obj_set_y(ui_Panel7, -228);
//     lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label116 = lv_label_create(ui_Panel7);
//     lv_obj_set_width(ui_Label116, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label116, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label116, -365);
//     lv_obj_set_y(ui_Label116, 0);
//     lv_obj_set_align(ui_Label116, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label116, "17:24");
//     lv_obj_set_style_text_font(ui_Label116, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label49 = lv_label_create(ui_Panel7);
//     lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label49, -294);
//     lv_obj_set_y(ui_Label49, 1);
//     lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label49, "Wed, OCT 22 ");
//     lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
//     lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
//     lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
//     lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
//     lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
// }
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLogoImage = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_WifiLogoImage, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiLogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLogoImage, 14);
    lv_obj_set_y(ui_WifiLogoImage, -174);
    lv_obj_set_align(ui_WifiLogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiLogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiLogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiPassPanel = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_WifiPassPanel, 785);
    lv_obj_set_height(ui_WifiPassPanel, 331);
    lv_obj_set_x(ui_WifiPassPanel, 0);
    lv_obj_set_y(ui_WifiPassPanel, 29);
    lv_obj_set_align(ui_WifiPassPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiPassPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPassPanel, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiPassPanel, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiPassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDText = lv_textarea_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_SSIDText, 713);
    lv_obj_set_height(ui_SSIDText, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_SSIDText, 3);
    lv_obj_set_y(ui_SSIDText, -134);
    lv_obj_set_align(ui_SSIDText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSIDText, "Wifi SSID...");
    lv_textarea_set_one_line(ui_SSIDText, true);
    lv_obj_set_style_text_color(ui_SSIDText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SSIDText, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SSIDText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SSIDText, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SSIDText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_PasswordText = lv_textarea_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordText, 713);
    lv_obj_set_height(ui_PasswordText, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_PasswordText, 3);
    lv_obj_set_y(ui_PasswordText, -81);
    lv_obj_set_align(ui_PasswordText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordText, "Wifi password...");
    lv_textarea_set_one_line(ui_PasswordText, true);
    lv_textarea_set_password_mode(ui_PasswordText, true);
    lv_obj_clear_flag(ui_PasswordText, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_PasswordText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PasswordText, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PasswordText, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PasswordText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_SSIDKeyboard = lv_keyboard_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_SSIDKeyboard, 708);
    lv_obj_set_height(ui_SSIDKeyboard, 200);
    lv_obj_set_x(ui_SSIDKeyboard, 3);
    lv_obj_set_y(ui_SSIDKeyboard, 45);
    lv_obj_set_align(ui_SSIDKeyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SSIDKeyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SSIDKeyboard, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_SSIDKeyboard, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PasswordKeyboard = lv_keyboard_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordKeyboard, 708);
    lv_obj_set_height(ui_PasswordKeyboard, 200);
    lv_obj_set_x(ui_PasswordKeyboard, 3);
    lv_obj_set_y(ui_PasswordKeyboard, 45);
    lv_obj_set_align(ui_PasswordKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_PasswordKeyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PasswordKeyboard, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PasswordKeyboard, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_WifiLoadingPanel = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_WifiLoadingPanel, 543);
    lv_obj_set_height(ui_WifiLoadingPanel, 260);
    lv_obj_set_x(ui_WifiLoadingPanel, 8);
    lv_obj_set_y(ui_WifiLoadingPanel, -50);
    lv_obj_set_align(ui_WifiLoadingPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiLoadingPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WifiLoadingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLoadingLabel = lv_label_create(ui_WifiLoadingPanel);
    lv_obj_set_width(ui_WifiLoadingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLoadingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLoadingLabel, 0);
    lv_obj_set_y(ui_WifiLoadingLabel, 50);
    lv_obj_set_align(ui_WifiLoadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLoadingLabel, "Wifi connecting, please wait...");

    ui_WifiLoadingSpinner = lv_spinner_create(ui_WifiLoadingPanel, 1000, 90);
    lv_obj_set_width(ui_WifiLoadingSpinner, 66);
    lv_obj_set_height(ui_WifiLoadingSpinner, 63);
    lv_obj_set_x(ui_WifiLoadingSpinner, 0);
    lv_obj_set_y(ui_WifiLoadingSpinner, -34);
    lv_obj_set_align(ui_WifiLoadingSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiLoadingSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_WifiLoadingSpinner, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WifiLoadingSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WifiWarningType = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_WifiWarningType, 645);
    lv_obj_set_height(ui_WifiWarningType, 300);
    lv_obj_set_x(ui_WifiWarningType, 4);
    lv_obj_set_y(ui_WifiWarningType, -48);
    lv_obj_set_align(ui_WifiWarningType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiWarningType, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WifiWarningType, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiWarningLabel = lv_label_create(ui_WifiWarningType);
    lv_obj_set_width(ui_WifiWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiWarningLabel, 0);
    lv_obj_set_y(ui_WifiWarningLabel, 3);
    lv_obj_set_align(ui_WifiWarningLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiWarningLabel,
                      "	  Please type in your Wi-Fi settings first \nbefore proceeding to another application!");

    ui_WifiWarningImage = lv_img_create(ui_WifiWarningType);
    lv_img_set_src(ui_WifiWarningImage, &ui_img_1384146481);
    lv_obj_set_width(ui_WifiWarningImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiWarningImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiWarningImage, 0);
    lv_obj_set_y(ui_WifiWarningImage, -74);
    lv_obj_set_align(ui_WifiWarningImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiWarningImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiWarningImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiWarningImage, lv_color_hex(0xB33737), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiWarningImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmButton = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ConfirmButton, 119);
    lv_obj_set_height(ui_ConfirmButton, 60);
    lv_obj_set_x(ui_ConfirmButton, 317);
    lv_obj_set_y(ui_ConfirmButton, -170);
    lv_obj_set_align(ui_ConfirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfirmButton, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ConfirmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ConfirmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfirmButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_ConfirmImage = lv_label_create(ui_ConfirmButton);
    lv_obj_set_width(ui_ConfirmImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfirmImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfirmImage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfirmImage, "OK");

    ui_BottomBarScreen5 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_BottomBarScreen5, 826);
    lv_obj_set_height(ui_BottomBarScreen5, 69);
    lv_obj_set_x(ui_BottomBarScreen5, 5);
    lv_obj_set_y(ui_BottomBarScreen5, 207);
    lv_obj_set_align(ui_BottomBarScreen5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen5, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen5, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton5 = lv_btn_create(ui_BottomBarScreen5);
    lv_obj_set_width(ui_SchedulerButton5, 119);
    lv_obj_set_height(ui_SchedulerButton5, 60);
    lv_obj_set_x(ui_SchedulerButton5, 267);
    lv_obj_set_y(ui_SchedulerButton5, 2);
    lv_obj_set_align(ui_SchedulerButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton5, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel5 = lv_label_create(ui_SchedulerButton5);
    lv_obj_set_width(ui_SchedulerLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel5, 0);
    lv_obj_set_y(ui_SchedulerLabel5, 21);
    lv_obj_set_align(ui_SchedulerLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel5, "Scheduler");

    ui_SchedulerImage5 = lv_img_create(ui_SchedulerButton5);
    lv_img_set_src(ui_SchedulerImage5, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage5, 0);
    lv_obj_set_y(ui_SchedulerImage5, -11);
    lv_obj_set_align(ui_SchedulerImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton5 = lv_btn_create(ui_BottomBarScreen5);
    lv_obj_set_width(ui_SwitchButton5, 119);
    lv_obj_set_height(ui_SwitchButton5, 60);
    lv_obj_set_x(ui_SwitchButton5, -73);
    lv_obj_set_y(ui_SwitchButton5, 0);
    lv_obj_set_align(ui_SwitchButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton5, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel5 = lv_label_create(ui_SwitchButton5);
    lv_obj_set_width(ui_SwitchLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel5, 0);
    lv_obj_set_y(ui_SwitchLabel5, 21);
    lv_obj_set_align(ui_SwitchLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel5, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage5 = lv_img_create(ui_SwitchButton5);
    lv_img_set_src(ui_SwitchImage5, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage5, 0);
    lv_obj_set_y(ui_SwitchImage5, -11);
    lv_obj_set_align(ui_SwitchImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton5 = lv_btn_create(ui_BottomBarScreen5);
    lv_obj_set_width(ui_WifiButton5, 119);
    lv_obj_set_height(ui_WifiButton5, 60);
    lv_obj_set_x(ui_WifiButton5, 105);
    lv_obj_set_y(ui_WifiButton5, 0);
    lv_obj_set_align(ui_WifiButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton5, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel5 = lv_label_create(ui_WifiButton5);
    lv_obj_set_width(ui_WifiLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel5, 0);
    lv_obj_set_y(ui_WifiLabel5, 21);
    lv_obj_set_align(ui_WifiLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel5, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage5 = lv_img_create(ui_WifiButton5);
    lv_img_set_src(ui_WifiImage5, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage5, 0);
    lv_obj_set_y(ui_WifiImage5, -11);
    lv_obj_set_align(ui_WifiImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton5 = lv_btn_create(ui_BottomBarScreen5);
    lv_obj_set_width(ui_HomeButton5, 119);
    lv_obj_set_height(ui_HomeButton5, 60);
    lv_obj_set_x(ui_HomeButton5, -265);
    lv_obj_set_y(ui_HomeButton5, 0);
    lv_obj_set_align(ui_HomeButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton5, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButton5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HoneLabel5 = lv_label_create(ui_HomeButton5);
    lv_obj_set_width(ui_HoneLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HoneLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HoneLabel5, 0);
    lv_obj_set_y(ui_HoneLabel5, 21);
    lv_obj_set_align(ui_HoneLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HoneLabel5, "Home");
    lv_obj_set_style_text_color(ui_HoneLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HoneLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage5 = lv_img_create(ui_HomeButton5);
    lv_img_set_src(ui_HomeImage5, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage5, 0);
    lv_obj_set_y(ui_HomeImage5, -11);
    lv_obj_set_align(ui_HomeImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar5 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_TopBar5, 818);
    lv_obj_set_height(ui_TopBar5, 32);
    lv_obj_set_x(ui_TopBar5, 0);
    lv_obj_set_y(ui_TopBar5, -228);
    lv_obj_set_align(ui_TopBar5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar5, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar5, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel5 = lv_label_create(ui_TopBar5);
    lv_obj_set_width(ui_TimeLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel5, 0);
    lv_obj_set_y(ui_TimeLabel5, 0);
    lv_obj_set_align(ui_TimeLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel5, "17:24");
    lv_obj_set_style_text_font(ui_TimeLabel5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel5 = lv_label_create(ui_TopBar5);
    lv_obj_set_width(ui_DateLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel5, -294);
    lv_obj_set_y(ui_DateLabel5, 1);
    lv_obj_set_align(ui_DateLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel5, "Wed, OCT 22 ");
    lv_obj_set_style_text_font(ui_DateLabel5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    


    lv_obj_add_event_cb(ui_SSIDText, ui_event_SSIDText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordText, ui_event_PasswordText, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_SSIDKeyboard, ui_SSIDText);
    lv_obj_add_event_cb(ui_SSIDKeyboard, ui_event_SSIDKeyboard, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PasswordKeyboard, ui_PasswordText);
    lv_obj_add_event_cb(ui_PasswordKeyboard, ui_event_PasswordKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfirmButton, ui_event_ConfirmButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SchedulerButton5, ui_event_SchedulerButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton5, ui_event_SwitchButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton5, ui_event_WifiButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton5, ui_event_HomeButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiWarningType, ui_event_WifiWarningType, LV_EVENT_ALL, NULL);
    uic_WifiLogoImage = ui_WifiLogoImage;
    uic_WifiPassPanel = ui_WifiPassPanel;
    uic_SSIDText = ui_SSIDText;
    uic_PasswordText = ui_PasswordText;
    uic_SSIDKeyboard = ui_SSIDKeyboard;
    uic_PasswordKeyboard = ui_PasswordKeyboard;
    uic_WifiLoadingPanel = ui_WifiLoadingPanel;
    uic_WifiLoadingLabel = ui_WifiLoadingLabel;
    uic_WifiLoadingSpinner = ui_WifiLoadingSpinner;
    uic_WifiWarningType = ui_WifiWarningType;
    uic_WifiWarningLabel = ui_WifiWarningLabel;
    uic_WifiWarningImage = ui_WifiWarningImage;
    uic_ConfirmButton = ui_ConfirmButton;
    uic_ConfirmImage = ui_ConfirmImage;
    uic_BottomBarScreen5 = ui_BottomBarScreen5;
    uic_SchedulerButton5 = ui_SchedulerButton5;
    uic_SchedulerLabel5 = ui_SchedulerLabel5;
    uic_SchedulerImage5 = ui_SchedulerImage5;
    uic_SwitchButton5 = ui_SwitchButton5;
    uic_SwitchLabel5 = ui_SwitchLabel5;
    uic_SwitchImage5 = ui_SwitchImage5;
    uic_WifiButton5 = ui_WifiButton5;
    uic_WifiLabel5 = ui_WifiLabel5;
    uic_WifiImage5 = ui_WifiImage5;
    uic_HomeButton5 = ui_HomeButton5;
    uic_HoneLabel5 = ui_HoneLabel5;
    uic_HomeImage5 = ui_HomeImage5;
    uic_TimeLabel5 = ui_TimeLabel5;
    uic_DateLabel5 = ui_DateLabel5;

}