// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "../ui.h"
#include "../ui_images.h"

void ui_Screen7_screen_init(void)
{
    
    
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventsPanel = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_EventsPanel, 786);
    lv_obj_set_height(ui_EventsPanel, 321);
    lv_obj_set_x(ui_EventsPanel, -1);
    lv_obj_set_y(ui_EventsPanel, 10);
    lv_obj_set_align(ui_EventsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EventsPanel, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_style_bg_color(ui_EventsPanel, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EventsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EventsPanel, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EventsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_EventsPanel, lv_color_hex(0xADADAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_EventsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_EventsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_EventsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_EventsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_EventsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event1 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event1, 688);
    lv_obj_set_height(ui_Event1, 50);
    lv_obj_set_x(ui_Event1, -42);
    lv_obj_set_y(ui_Event1, -116);
    lv_obj_set_align(ui_Event1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event1Label = lv_label_create(ui_Event1);
    lv_obj_set_width(ui_Event1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event1Label, 0);
    lv_obj_set_y(ui_Event1Label, 0);
    lv_obj_set_align(ui_Event1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event1Label, "Morning watering ");
    lv_obj_set_style_text_color(ui_Event1Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent1 = lv_label_create(ui_Event1);
    lv_obj_set_width(ui_TimeLabelEvent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent1, 99);
    lv_obj_set_y(ui_TimeLabelEvent1, 2);
    lv_obj_set_align(ui_TimeLabelEvent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent1, "6:00  - 7:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent1, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent1 = lv_btn_create(ui_Event1);
    lv_obj_set_width(ui_DeleteButtonEvent1, 49);
    lv_obj_set_height(ui_DeleteButtonEvent1, 50);
    lv_obj_set_x(ui_DeleteButtonEvent1, 312);
    lv_obj_set_y(ui_DeleteButtonEvent1, 1);
    lv_obj_set_align(ui_DeleteButtonEvent1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent1, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent1, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent1 = lv_btn_create(ui_Event1);
    lv_obj_set_width(ui_ConfigButtonEvent1, 50);
    lv_obj_set_height(ui_ConfigButtonEvent1, 50);
    lv_obj_set_x(ui_ConfigButtonEvent1, 253);
    lv_obj_set_y(ui_ConfigButtonEvent1, 0);
    lv_obj_set_align(ui_ConfigButtonEvent1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent1, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent1, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent1 = lv_btn_create(ui_Event1);
    lv_obj_set_width(ui_SeenButtonEvent1, 72);
    lv_obj_set_height(ui_SeenButtonEvent1, 50);
    lv_obj_set_x(ui_SeenButtonEvent1, 479);
    lv_obj_set_y(ui_SeenButtonEvent1, 1);
    lv_obj_set_align(ui_SeenButtonEvent1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent1, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent1, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash1 = lv_label_create(ui_Event1);
    lv_obj_set_width(ui_Slash1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash1, 232);
    lv_obj_set_y(ui_Slash1, 3);
    lv_obj_set_align(ui_Slash1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash1, "/");
    lv_obj_set_style_text_color(ui_Slash1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash1, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event2 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event2, 688);
    lv_obj_set_height(ui_Event2, 50);
    lv_obj_set_x(ui_Event2, -41);
    lv_obj_set_y(ui_Event2, -46);
    lv_obj_set_align(ui_Event2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event2Label = lv_label_create(ui_Event2);
    lv_obj_set_width(ui_Event2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event2Label, 0);
    lv_obj_set_y(ui_Event2Label, 0);
    lv_obj_set_align(ui_Event2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event2Label, "Afternoon watering ");
    lv_obj_set_style_text_color(ui_Event2Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent2 = lv_label_create(ui_Event2);
    lv_obj_set_width(ui_TimeLabelEvent2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent2, 99);
    lv_obj_set_y(ui_TimeLabelEvent2, 2);
    lv_obj_set_align(ui_TimeLabelEvent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent2, "12:00  - 13:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent2, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent2 = lv_btn_create(ui_Event2);
    lv_obj_set_width(ui_DeleteButtonEvent2, 49);
    lv_obj_set_height(ui_DeleteButtonEvent2, 50);
    lv_obj_set_x(ui_DeleteButtonEvent2, 312);
    lv_obj_set_y(ui_DeleteButtonEvent2, 1);
    lv_obj_set_align(ui_DeleteButtonEvent2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent2, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent2, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent2 = lv_btn_create(ui_Event2);
    lv_obj_set_width(ui_ConfigButtonEvent2, 50);
    lv_obj_set_height(ui_ConfigButtonEvent2, 50);
    lv_obj_set_x(ui_ConfigButtonEvent2, 252);
    lv_obj_set_y(ui_ConfigButtonEvent2, 0);
    lv_obj_set_align(ui_ConfigButtonEvent2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent2, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent2, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent2 = lv_btn_create(ui_Event2);
    lv_obj_set_width(ui_SeenButtonEvent2, 72);
    lv_obj_set_height(ui_SeenButtonEvent2, 50);
    lv_obj_set_x(ui_SeenButtonEvent2, 479);
    lv_obj_set_y(ui_SeenButtonEvent2, 1);
    lv_obj_set_align(ui_SeenButtonEvent2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent2, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent2, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash2 = lv_label_create(ui_Event2);
    lv_obj_set_width(ui_Slash2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash2, 229);
    lv_obj_set_y(ui_Slash2, 5);
    lv_obj_set_align(ui_Slash2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash2, "/");
    lv_obj_set_style_text_color(ui_Slash2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash2, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event3 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event3, 688);
    lv_obj_set_height(ui_Event3, 50);
    lv_obj_set_x(ui_Event3, -41);
    lv_obj_set_y(ui_Event3, 21);
    lv_obj_set_align(ui_Event3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event3Label = lv_label_create(ui_Event3);
    lv_obj_set_width(ui_Event3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event3Label, 0);
    lv_obj_set_y(ui_Event3Label,0);
    lv_obj_set_align(ui_Event3Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event3Label, "Evening watering ");
    lv_obj_set_style_text_color(ui_Event3Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent3 = lv_label_create(ui_Event3);
    lv_obj_set_width(ui_TimeLabelEvent3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent3, 99);
    lv_obj_set_y(ui_TimeLabelEvent3, 2);
    lv_obj_set_align(ui_TimeLabelEvent3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent3, "17:00  - 18:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent3, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent3 = lv_btn_create(ui_Event3);
    lv_obj_set_width(ui_ConfigButtonEvent3, 50);
    lv_obj_set_height(ui_ConfigButtonEvent3, 50);
    lv_obj_set_x(ui_ConfigButtonEvent3, 252);
    lv_obj_set_y(ui_ConfigButtonEvent3, 0);
    lv_obj_set_align(ui_ConfigButtonEvent3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent3, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent3, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent3 = lv_btn_create(ui_Event3);
    lv_obj_set_width(ui_SeenButtonEvent3, 72);
    lv_obj_set_height(ui_SeenButtonEvent3, 50);
    lv_obj_set_x(ui_SeenButtonEvent3, 479);
    lv_obj_set_y(ui_SeenButtonEvent3, 1);
    lv_obj_set_align(ui_SeenButtonEvent3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent3, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent3, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash3 = lv_label_create(ui_Event3);
    lv_obj_set_width(ui_Slash3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash3, 229);
    lv_obj_set_y(ui_Slash3, 0);
    lv_obj_set_align(ui_Slash3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash3, "/");
    lv_obj_set_style_text_color(ui_Slash3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash3, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent3 = lv_btn_create(ui_Event3);
    lv_obj_set_width(ui_DeleteButtonEvent3, 49);
    lv_obj_set_height(ui_DeleteButtonEvent3, 50);
    lv_obj_set_x(ui_DeleteButtonEvent3, 312);
    lv_obj_set_y(ui_DeleteButtonEvent3, 1);
    lv_obj_set_align(ui_DeleteButtonEvent3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent3, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent3, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event4 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event4, 688);
    lv_obj_set_height(ui_Event4, 50);
    lv_obj_set_x(ui_Event4, -41);
    lv_obj_set_y(ui_Event4, 91);
    lv_obj_set_align(ui_Event4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event4Label = lv_label_create(ui_Event4);
    lv_obj_set_width(ui_Event4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event4Label, 0);
    lv_obj_set_y(ui_Event4Label, 0);
    lv_obj_set_align(ui_Event4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event4Label, "Night lighting ");
    lv_obj_set_style_text_color(ui_Event4Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent4 = lv_label_create(ui_Event4);
    lv_obj_set_width(ui_TimeLabelEvent4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent4, 99);
    lv_obj_set_y(ui_TimeLabelEvent4, 2);
    lv_obj_set_align(ui_TimeLabelEvent4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent4, "20:00  - 4:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent4, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent4 = lv_btn_create(ui_Event4);
    lv_obj_set_width(ui_ConfigButtonEvent4, 50);
    lv_obj_set_height(ui_ConfigButtonEvent4, 50);
    lv_obj_set_x(ui_ConfigButtonEvent4, 252);
    lv_obj_set_y(ui_ConfigButtonEvent4, 0);
    lv_obj_set_align(ui_ConfigButtonEvent4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent4, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent4, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent4 = lv_btn_create(ui_Event4);
    lv_obj_set_width(ui_SeenButtonEvent4, 72);
    lv_obj_set_height(ui_SeenButtonEvent4, 50);
    lv_obj_set_x(ui_SeenButtonEvent4, 479);
    lv_obj_set_y(ui_SeenButtonEvent4, 1);
    lv_obj_set_align(ui_SeenButtonEvent4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent4, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent4, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash4 = lv_label_create(ui_Event4);
    lv_obj_set_width(ui_Slash4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash4, 227);
    lv_obj_set_y(ui_Slash4, 2);
    lv_obj_set_align(ui_Slash4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash4, "/");
    lv_obj_set_style_text_color(ui_Slash4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash4, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent4 = lv_btn_create(ui_Event4);
    lv_obj_set_width(ui_DeleteButtonEvent4, 49);
    lv_obj_set_height(ui_DeleteButtonEvent4, 50);
    lv_obj_set_x(ui_DeleteButtonEvent4, 312);
    lv_obj_set_y(ui_DeleteButtonEvent4, 1);
    lv_obj_set_align(ui_DeleteButtonEvent4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent4, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent4, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch1 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch1, 50);
    lv_obj_set_height(ui_EventSwitch1, 25);
    lv_obj_set_x(ui_EventSwitch1, 336);
    lv_obj_set_y(ui_EventSwitch1, -116);
    lv_obj_set_align(ui_EventSwitch1, LV_ALIGN_CENTER);


    ui_EventSwitch2 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch2, 50);
    lv_obj_set_height(ui_EventSwitch2, 25);
    lv_obj_set_x(ui_EventSwitch2, 338);
    lv_obj_set_y(ui_EventSwitch2, -44);
    lv_obj_set_align(ui_EventSwitch2, LV_ALIGN_CENTER);


    ui_EventSwitch3 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch3, 50);
    lv_obj_set_height(ui_EventSwitch3, 25);
    lv_obj_set_x(ui_EventSwitch3, 339);
    lv_obj_set_y(ui_EventSwitch3, 21);
    lv_obj_set_align(ui_EventSwitch3, LV_ALIGN_CENTER);


    ui_EventSwitch4 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch4, 50);
    lv_obj_set_height(ui_EventSwitch4, 25);
    lv_obj_set_x(ui_EventSwitch4, 339);
    lv_obj_set_y(ui_EventSwitch4, 92);
    lv_obj_set_align(ui_EventSwitch4, LV_ALIGN_CENTER);


    ui_Event5 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event5, 688);
    lv_obj_set_height(ui_Event5, 50);
    lv_obj_set_x(ui_Event5, -41);
    lv_obj_set_y(ui_Event5, 159);
    lv_obj_set_align(ui_Event5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Event5Label = lv_label_create(ui_Event5);
    lv_obj_set_width(ui_Event5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event5Label, 0);
    lv_obj_set_y(ui_Event5Label, 0);
    lv_obj_set_align(ui_Event5Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event5Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event5Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event5Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent5 = lv_label_create(ui_Event5);
    lv_obj_set_width(ui_TimeLabelEvent5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent5, 99);
    lv_obj_set_y(ui_TimeLabelEvent5, 2);
    lv_obj_set_align(ui_TimeLabelEvent5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent5, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent5, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent5 = lv_btn_create(ui_Event5);
    lv_obj_set_width(ui_ConfigButtonEvent5, 50);
    lv_obj_set_height(ui_ConfigButtonEvent5, 50);
    lv_obj_set_x(ui_ConfigButtonEvent5, 252);
    lv_obj_set_y(ui_ConfigButtonEvent5, 0);
    lv_obj_set_align(ui_ConfigButtonEvent5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent5, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent5, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent5 = lv_btn_create(ui_Event5);
    lv_obj_set_width(ui_SeenButtonEvent5, 72);
    lv_obj_set_height(ui_SeenButtonEvent5, 50);
    lv_obj_set_x(ui_SeenButtonEvent5, 479);
    lv_obj_set_y(ui_SeenButtonEvent5, 1);
    lv_obj_set_align(ui_SeenButtonEvent5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent5, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent5, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash5 = lv_label_create(ui_Event5);
    lv_obj_set_width(ui_Slash5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash5, 233);
    lv_obj_set_y(ui_Slash5, -3);
    lv_obj_set_align(ui_Slash5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash5, "/");
    lv_obj_set_style_text_color(ui_Slash5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash5, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent5 = lv_btn_create(ui_Event5);
    lv_obj_set_width(ui_DeleteButtonEvent5, 49);
    lv_obj_set_height(ui_DeleteButtonEvent5, 50);
    lv_obj_set_x(ui_DeleteButtonEvent5, 312);
    lv_obj_set_y(ui_DeleteButtonEvent5, 1);
    lv_obj_set_align(ui_DeleteButtonEvent5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent5, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent5, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch5 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch5, 50);
    lv_obj_set_height(ui_EventSwitch5, 27);
    lv_obj_set_x(ui_EventSwitch5, 340);
    lv_obj_set_y(ui_EventSwitch5, 160);
    lv_obj_set_align(ui_EventSwitch5, LV_ALIGN_CENTER);

    //Event 6

    ui_Event6 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event6, 688);
    lv_obj_set_height(ui_Event6, 50);
    lv_obj_set_x(ui_Event6, -41);
    lv_obj_set_y(ui_Event6, 230);
    lv_obj_set_align(ui_Event6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event6, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Event6Label = lv_label_create(ui_Event6);
    lv_obj_set_width(ui_Event6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event6Label, 0);
    lv_obj_set_y(ui_Event6Label, 0);
    lv_obj_set_align(ui_Event6Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event6Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event6Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event6Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent6 = lv_label_create(ui_Event6);
    lv_obj_set_width(ui_TimeLabelEvent6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent6, 99);
    lv_obj_set_y(ui_TimeLabelEvent6, 2);
    lv_obj_set_align(ui_TimeLabelEvent6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent6, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent6, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent6 = lv_btn_create(ui_Event6);
    lv_obj_set_width(ui_ConfigButtonEvent6, 50);
    lv_obj_set_height(ui_ConfigButtonEvent6, 50);
    lv_obj_set_x(ui_ConfigButtonEvent6, 252);
    lv_obj_set_y(ui_ConfigButtonEvent6, 0);
    lv_obj_set_align(ui_ConfigButtonEvent6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent6, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent6, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent6 = lv_btn_create(ui_Event6);
    lv_obj_set_width(ui_SeenButtonEvent6, 72);
    lv_obj_set_height(ui_SeenButtonEvent6, 50);
    lv_obj_set_x(ui_SeenButtonEvent6, 479);
    lv_obj_set_y(ui_SeenButtonEvent6, 1);
    lv_obj_set_align(ui_SeenButtonEvent6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent6, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent6, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash6 = lv_label_create(ui_Event6);
    lv_obj_set_width(ui_Slash6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash6, 233);
    lv_obj_set_y(ui_Slash6, -3);
    lv_obj_set_align(ui_Slash6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash6, "/");
    lv_obj_set_style_text_color(ui_Slash6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash6, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent6 = lv_btn_create(ui_Event6);
    lv_obj_set_width(ui_DeleteButtonEvent6, 49);
    lv_obj_set_height(ui_DeleteButtonEvent6, 50);
    lv_obj_set_x(ui_DeleteButtonEvent6, 312);
    lv_obj_set_y(ui_DeleteButtonEvent6, 1);
    lv_obj_set_align(ui_DeleteButtonEvent6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent6, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent6, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch6 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch6, 50);
    lv_obj_set_height(ui_EventSwitch6, 27);
    lv_obj_set_x(ui_EventSwitch6, 340);
    lv_obj_set_y(ui_EventSwitch6, 230);
    lv_obj_set_align(ui_EventSwitch6, LV_ALIGN_CENTER);
    //end event 6

    // ===============================================
    // EVENT 7: Tọa độ Y = 300 (230 + 70)
    // ===============================================
    ui_Event7 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event7, 688);
    lv_obj_set_height(ui_Event7, 50);
    lv_obj_set_x(ui_Event7, -41);
    lv_obj_set_y(ui_Event7, 300);
    lv_obj_set_align(ui_Event7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event7, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event7, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event7, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Event7Label = lv_label_create(ui_Event7);
    lv_obj_set_width(ui_Event7Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event7Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event7Label, 0);
    lv_obj_set_y(ui_Event7Label, 0);
    lv_obj_set_align(ui_Event7Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event7Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event7Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event7Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent7 = lv_label_create(ui_Event7);
    lv_obj_set_width(ui_TimeLabelEvent7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent7, 99);
    lv_obj_set_y(ui_TimeLabelEvent7, 2);
    lv_obj_set_align(ui_TimeLabelEvent7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent7, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent7, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent7 = lv_btn_create(ui_Event7);
    lv_obj_set_width(ui_ConfigButtonEvent7, 50);
    lv_obj_set_height(ui_ConfigButtonEvent7, 50);
    lv_obj_set_x(ui_ConfigButtonEvent7, 252);
    lv_obj_set_y(ui_ConfigButtonEvent7, 0);
    lv_obj_set_align(ui_ConfigButtonEvent7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent7, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent7, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent7, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent7 = lv_btn_create(ui_Event7);
    lv_obj_set_width(ui_SeenButtonEvent7, 72);
    lv_obj_set_height(ui_SeenButtonEvent7, 50);
    lv_obj_set_x(ui_SeenButtonEvent7, 479);
    lv_obj_set_y(ui_SeenButtonEvent7, 1);
    lv_obj_set_align(ui_SeenButtonEvent7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent7, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent7, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent7, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash7 = lv_label_create(ui_Event7);
    lv_obj_set_width(ui_Slash7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash7, 233);
    lv_obj_set_y(ui_Slash7, -3);
    lv_obj_set_align(ui_Slash7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash7, "/");
    lv_obj_set_style_text_color(ui_Slash7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash7, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent7 = lv_btn_create(ui_Event7);
    lv_obj_set_width(ui_DeleteButtonEvent7, 49);
    lv_obj_set_height(ui_DeleteButtonEvent7, 50);
    lv_obj_set_x(ui_DeleteButtonEvent7, 312);
    lv_obj_set_y(ui_DeleteButtonEvent7, 1);
    lv_obj_set_align(ui_DeleteButtonEvent7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent7, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent7, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent7, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch7 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch7, 50);
    lv_obj_set_height(ui_EventSwitch7, 27);
    lv_obj_set_x(ui_EventSwitch7, 340);
    lv_obj_set_y(ui_EventSwitch7, 300);
    lv_obj_set_align(ui_EventSwitch7, LV_ALIGN_CENTER);


    // ===============================================
    // EVENT 8: Tọa độ Y = 370 (300 + 70)
    // ===============================================
    ui_Event8 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event8, 688);
    lv_obj_set_height(ui_Event8, 50);
    lv_obj_set_x(ui_Event8, -41);
    lv_obj_set_y(ui_Event8, 370);
    lv_obj_set_align(ui_Event8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event8, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event8, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event8, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Event8Label = lv_label_create(ui_Event8);
    lv_obj_set_width(ui_Event8Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event8Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event8Label, 0);
    lv_obj_set_y(ui_Event8Label, 0);
    lv_obj_set_align(ui_Event8Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event8Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event8Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event8Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent8 = lv_label_create(ui_Event8);
    lv_obj_set_width(ui_TimeLabelEvent8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent8, 99);
    lv_obj_set_y(ui_TimeLabelEvent8, 2);
    lv_obj_set_align(ui_TimeLabelEvent8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent8, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent8, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent8 = lv_btn_create(ui_Event8);
    lv_obj_set_width(ui_ConfigButtonEvent8, 50);
    lv_obj_set_height(ui_ConfigButtonEvent8, 50);
    lv_obj_set_x(ui_ConfigButtonEvent8, 252);
    lv_obj_set_y(ui_ConfigButtonEvent8, 0);
    lv_obj_set_align(ui_ConfigButtonEvent8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent8, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent8, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent8, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent8 = lv_btn_create(ui_Event8);
    lv_obj_set_width(ui_SeenButtonEvent8, 72);
    lv_obj_set_height(ui_SeenButtonEvent8, 50);
    lv_obj_set_x(ui_SeenButtonEvent8, 479);
    lv_obj_set_y(ui_SeenButtonEvent8, 1);
    lv_obj_set_align(ui_SeenButtonEvent8, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent8, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent8, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent8, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash8 = lv_label_create(ui_Event8);
    lv_obj_set_width(ui_Slash8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash8, 233);
    lv_obj_set_y(ui_Slash8, -3);
    lv_obj_set_align(ui_Slash8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash8, "/");
    lv_obj_set_style_text_color(ui_Slash8, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash8, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent8 = lv_btn_create(ui_Event8);
    lv_obj_set_width(ui_DeleteButtonEvent8, 49);
    lv_obj_set_height(ui_DeleteButtonEvent8, 50);
    lv_obj_set_x(ui_DeleteButtonEvent8, 312);
    lv_obj_set_y(ui_DeleteButtonEvent8, 1);
    lv_obj_set_align(ui_DeleteButtonEvent8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent8, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent8, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent8, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch8 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch8, 50);
    lv_obj_set_height(ui_EventSwitch8, 27);
    lv_obj_set_x(ui_EventSwitch8, 340);
    lv_obj_set_y(ui_EventSwitch8, 370);
    lv_obj_set_align(ui_EventSwitch8, LV_ALIGN_CENTER);


    // ===============================================
    // EVENT 9: Tọa độ Y = 440 (370 + 70)
    // ===============================================
     ui_Event9 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event9, 688);
    lv_obj_set_height(ui_Event9, 50);
    lv_obj_set_x(ui_Event9, -41);
    lv_obj_set_y(ui_Event9, 440);
    lv_obj_set_align(ui_Event9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event9, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event9, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event9, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Event9Label = lv_label_create(ui_Event9);
    lv_obj_set_width(ui_Event9Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event9Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event9Label, 0);
    lv_obj_set_y(ui_Event9Label, 0);
    lv_obj_set_align(ui_Event9Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event9Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event9Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event9Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent9 = lv_label_create(ui_Event9);
    lv_obj_set_width(ui_TimeLabelEvent9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent9, 99);
    lv_obj_set_y(ui_TimeLabelEvent9, 2);
    lv_obj_set_align(ui_TimeLabelEvent9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent9, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent9, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent9 = lv_btn_create(ui_Event9);
    lv_obj_set_width(ui_ConfigButtonEvent9, 50);
    lv_obj_set_height(ui_ConfigButtonEvent9, 50);
    lv_obj_set_x(ui_ConfigButtonEvent9, 252);
    lv_obj_set_y(ui_ConfigButtonEvent9, 0);
    lv_obj_set_align(ui_ConfigButtonEvent9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent9, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent9, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent9, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent9 = lv_btn_create(ui_Event9);
    lv_obj_set_width(ui_SeenButtonEvent9, 72);
    lv_obj_set_height(ui_SeenButtonEvent9, 50);
    lv_obj_set_x(ui_SeenButtonEvent9, 479);
    lv_obj_set_y(ui_SeenButtonEvent9, 1);
    lv_obj_set_align(ui_SeenButtonEvent9, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent9, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent9, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent9, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash9 = lv_label_create(ui_Event9);
    lv_obj_set_width(ui_Slash9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash9, 233);
    lv_obj_set_y(ui_Slash9, -3);
    lv_obj_set_align(ui_Slash9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash9, "/");
    lv_obj_set_style_text_color(ui_Slash9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash9, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent9 = lv_btn_create(ui_Event9);
    lv_obj_set_width(ui_DeleteButtonEvent9, 49);
    lv_obj_set_height(ui_DeleteButtonEvent9, 50);
    lv_obj_set_x(ui_DeleteButtonEvent9, 312);
    lv_obj_set_y(ui_DeleteButtonEvent9, 1);
    lv_obj_set_align(ui_DeleteButtonEvent9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent9, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent9, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent9, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch9 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch9, 50);
    lv_obj_set_height(ui_EventSwitch9, 27);
    lv_obj_set_x(ui_EventSwitch9, 340);
    lv_obj_set_y(ui_EventSwitch9, 440);
    lv_obj_set_align(ui_EventSwitch9, LV_ALIGN_CENTER);

    // ===============================================
    // EVENT 10: Tọa độ Y = 510 (440 + 70)
    // ===============================================
     ui_Event10 = lv_obj_create(ui_EventsPanel);
    lv_obj_set_width(ui_Event10, 688);
    lv_obj_set_height(ui_Event10, 50);
    lv_obj_set_x(ui_Event10, -41);
    lv_obj_set_y(ui_Event10, 510);
    lv_obj_set_align(ui_Event10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Event10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Event10, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Event10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Event10, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Event10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Event10, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Event10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Event10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Event10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Event10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Event10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Event10Label = lv_label_create(ui_Event10);
    lv_obj_set_width(ui_Event10Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Event10Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Event10Label, 0);
    lv_obj_set_y(ui_Event10Label, 0);
    lv_obj_set_align(ui_Event10Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Event10Label, "Dawn rest");
    lv_obj_set_style_text_color(ui_Event10Label, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Event10Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabelEvent10 = lv_label_create(ui_Event10);
    lv_obj_set_width(ui_TimeLabelEvent10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabelEvent10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabelEvent10, 99);
    lv_obj_set_y(ui_TimeLabelEvent10, 2);
    lv_obj_set_align(ui_TimeLabelEvent10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabelEvent10, "4:00  - 6:00 ");
    lv_obj_set_style_text_color(ui_TimeLabelEvent10, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabelEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonEvent10 = lv_btn_create(ui_Event10);
    lv_obj_set_width(ui_ConfigButtonEvent10, 50);
    lv_obj_set_height(ui_ConfigButtonEvent10, 50);
    lv_obj_set_x(ui_ConfigButtonEvent10, 252);
    lv_obj_set_y(ui_ConfigButtonEvent10, 0);
    lv_obj_set_align(ui_ConfigButtonEvent10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButtonEvent10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButtonEvent10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButtonEvent10, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ConfigButtonEvent10, &ui_img2_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ConfigButtonEvent10, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ConfigButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeenButtonEvent10 = lv_btn_create(ui_Event10);
    lv_obj_set_width(ui_SeenButtonEvent10, 72);
    lv_obj_set_height(ui_SeenButtonEvent10, 50);
    lv_obj_set_x(ui_SeenButtonEvent10, 479);
    lv_obj_set_y(ui_SeenButtonEvent10, 1);
    lv_obj_set_align(ui_SeenButtonEvent10, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SeenButtonEvent10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SeenButtonEvent10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SeenButtonEvent10, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeenButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeenButtonEvent10, &ui_img3_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SeenButtonEvent10, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SeenButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slash10 = lv_label_create(ui_Event10);
    lv_obj_set_width(ui_Slash10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slash10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slash10, 233);
    lv_obj_set_y(ui_Slash10, -3);
    lv_obj_set_align(ui_Slash10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slash10, "/");
    lv_obj_set_style_text_color(ui_Slash10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Slash10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Slash10, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteButtonEvent10 = lv_btn_create(ui_Event10);
    lv_obj_set_width(ui_DeleteButtonEvent10, 49);
    lv_obj_set_height(ui_DeleteButtonEvent10, 50);
    lv_obj_set_x(ui_DeleteButtonEvent10, 312);
    lv_obj_set_y(ui_DeleteButtonEvent10, 1);
    lv_obj_set_align(ui_DeleteButtonEvent10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeleteButtonEvent10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteButtonEvent10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteButtonEvent10, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteButtonEvent10, &ui_img1_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DeleteButtonEvent10, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteButtonEvent10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EventSwitch10 = lv_switch_create(ui_EventsPanel);
    lv_obj_set_width(ui_EventSwitch10, 50);
    lv_obj_set_height(ui_EventSwitch10, 27);
    lv_obj_set_x(ui_EventSwitch10, 340);
    lv_obj_set_y(ui_EventSwitch10, 510);
    lv_obj_set_align(ui_EventSwitch10, LV_ALIGN_CENTER);

    ui_AddButton = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_AddButton, 60);
    lv_obj_set_height(ui_AddButton, 50);
    lv_obj_set_x(ui_AddButton, 275);
    lv_obj_set_y(ui_AddButton, -182);
    lv_obj_set_align(ui_AddButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AddButton, &ui_img4_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT);

    

    ui_BottomBarScreen7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_BottomBarScreen7, 826);
    lv_obj_set_height(ui_BottomBarScreen7, 69);
    lv_obj_set_x(ui_BottomBarScreen7, 5);
    lv_obj_set_y(ui_BottomBarScreen7, 207);
    lv_obj_set_align(ui_BottomBarScreen7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomBarScreen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBarScreen7, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBarScreen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBarScreen7, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBarScreen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerButton7 = lv_btn_create(ui_BottomBarScreen7);
    lv_obj_set_width(ui_SchedulerButton7, 119);
    lv_obj_set_height(ui_SchedulerButton7, 60);
    lv_obj_set_x(ui_SchedulerButton7, 267);
    lv_obj_set_y(ui_SchedulerButton7, 0);
    lv_obj_set_align(ui_SchedulerButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SchedulerButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulerButton7, lv_color_hex(0x76F176), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulerButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SchedulerButton7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SchedulerButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SchedulerButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SchedulerButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SchedulerButton7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SchedulerLabel7 = lv_label_create(ui_SchedulerButton7);
    lv_obj_set_width(ui_SchedulerLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerLabel7, 0);
    lv_obj_set_y(ui_SchedulerLabel7, 21);
    lv_obj_set_align(ui_SchedulerLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SchedulerLabel7, "Scheduler");

    ui_SchedulerImage7 = lv_img_create(ui_SchedulerButton7);
    lv_img_set_src(ui_SchedulerImage7, &ui_img_calendar_747310_png);
    lv_obj_set_width(ui_SchedulerImage7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SchedulerImage7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SchedulerImage7, 0);
    lv_obj_set_y(ui_SchedulerImage7, -11);
    lv_obj_set_align(ui_SchedulerImage7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SchedulerImage7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SchedulerImage7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchButton7 = lv_btn_create(ui_BottomBarScreen7);
    lv_obj_set_width(ui_SwitchButton7, 119);
    lv_obj_set_height(ui_SwitchButton7, 60);
    lv_obj_set_x(ui_SwitchButton7, -73);
    lv_obj_set_y(ui_SwitchButton7, 0);
    lv_obj_set_align(ui_SwitchButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButton7, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SwitchButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SwitchButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SwitchButton7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLabel7 = lv_label_create(ui_SwitchButton7);
    lv_obj_set_width(ui_SwitchLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel7, 0);
    lv_obj_set_y(ui_SwitchLabel7, 21);
    lv_obj_set_align(ui_SwitchLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel7, "Switch");
    lv_obj_set_style_text_color(ui_SwitchLabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchImage7 = lv_img_create(ui_SwitchButton7);
    lv_img_set_src(ui_SwitchImage7, &ui_img_981488682);
    lv_obj_set_width(ui_SwitchImage7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchImage7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchImage7, 0);
    lv_obj_set_y(ui_SwitchImage7, -11);
    lv_obj_set_align(ui_SwitchImage7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchImage7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SwitchImage7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton7 = lv_btn_create(ui_BottomBarScreen7);
    lv_obj_set_width(ui_WifiButton7, 119);
    lv_obj_set_height(ui_WifiButton7, 60);
    lv_obj_set_x(ui_WifiButton7, 105);
    lv_obj_set_y(ui_WifiButton7, 0);
    lv_obj_set_align(ui_WifiButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton7, lv_color_hex(0x6AB36A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WifiButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifiButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WifiButton7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiLabel7 = lv_label_create(ui_WifiButton7);
    lv_obj_set_width(ui_WifiLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel7, 0);
    lv_obj_set_y(ui_WifiLabel7, 21);
    lv_obj_set_align(ui_WifiLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel7, "Wifi setting");
    lv_obj_set_style_text_color(ui_WifiLabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage7 = lv_img_create(ui_WifiButton7);
    lv_img_set_src(ui_WifiImage7, &ui_img_wifi_12237189_png);
    lv_obj_set_width(ui_WifiImage7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage7, 0);
    lv_obj_set_y(ui_WifiImage7, -11);
    lv_obj_set_align(ui_WifiImage7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButotn7 = lv_btn_create(ui_BottomBarScreen7);
    lv_obj_set_width(ui_HomeButotn7, 119);
    lv_obj_set_height(ui_HomeButotn7, 60);
    lv_obj_set_x(ui_HomeButotn7, -265);
    lv_obj_set_y(ui_HomeButotn7, 0);
    lv_obj_set_align(ui_HomeButotn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButotn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButotn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButotn7, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButotn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HomeButotn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HomeButotn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeButotn7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel7 = lv_label_create(ui_HomeButotn7);
    lv_obj_set_width(ui_HomeLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabel7, 0);
    lv_obj_set_y(ui_HomeLabel7, 21);
    lv_obj_set_align(ui_HomeLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel7, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage7 = lv_img_create(ui_HomeButotn7);
    lv_img_set_src(ui_HomeImage7, &ui_img_home_12484335_png);
    lv_obj_set_width(ui_HomeImage7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage7, 0);
    lv_obj_set_y(ui_HomeImage7, -11);
    lv_obj_set_align(ui_HomeImage7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateEventsLabel = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_DateEventsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateEventsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateEventsLabel, 10);
    lv_obj_set_y(ui_DateEventsLabel, -183);
    lv_obj_set_align(ui_DateEventsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DateEventsLabel, "Events on");
    lv_obj_set_style_text_color(ui_DateEventsLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateEventsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateEventsLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToSchedulerButton = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_BackToSchedulerButton, 60);
    lv_obj_set_height(ui_BackToSchedulerButton, 50);
    lv_obj_set_x(ui_BackToSchedulerButton, 355);
    lv_obj_set_y(ui_BackToSchedulerButton, -182);
    lv_obj_set_align(ui_BackToSchedulerButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToSchedulerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToSchedulerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToSchedulerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToSchedulerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BackToSchedulerButton, &ui_img_calendar_747310_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningPanel = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_WarningPanel, 427);
    lv_obj_set_height(ui_WarningPanel, 219);
    lv_obj_set_x(ui_WarningPanel, 13);
    lv_obj_set_y(ui_WarningPanel, -28);
    lv_obj_set_align(ui_WarningPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WarningPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WarningPanel, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningPanel, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxWarningPanel = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_MaxWarningPanel, 427);
    lv_obj_set_height(ui_MaxWarningPanel, 219);
    lv_obj_set_x(ui_MaxWarningPanel, 13);
    lv_obj_set_y(ui_MaxWarningPanel, -28);
    lv_obj_set_align(ui_MaxWarningPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MaxWarningPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MaxWarningPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MaxWarningPanel, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxWarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MaxWarningPanel, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MaxWarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OkButton = lv_btn_create(ui_MaxWarningPanel);
    lv_obj_set_width(ui_OkButton, 100);
    lv_obj_set_height(ui_OkButton, 50);
    lv_obj_set_x(ui_OkButton, 7);
    lv_obj_set_y(ui_OkButton, 57);
    lv_obj_set_align(ui_OkButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OkButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OkButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OkButton, lv_color_hex(0xFB0031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OkButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OkLabel = lv_label_create(ui_OkButton);
    lv_obj_set_width(ui_OkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OkLabel, "OK");
    lv_obj_set_style_text_font(ui_OkLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_MaxWarningLabel = lv_label_create(ui_MaxWarningPanel);
    lv_obj_set_width(ui_MaxWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxWarningLabel, 1);
    lv_obj_set_y(ui_MaxWarningLabel, -34);
    lv_obj_set_align(ui_MaxWarningLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxWarningLabel, "You have reached the maximum\n number of events for this day!");
    lv_obj_set_style_text_align(ui_MaxWarningLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxWarningLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_YesButton = lv_btn_create(ui_WarningPanel);
    lv_obj_set_width(ui_YesButton, 100);
    lv_obj_set_height(ui_YesButton, 50);
    lv_obj_set_x(ui_YesButton, -92);
    lv_obj_set_y(ui_YesButton, 59);
    lv_obj_set_align(ui_YesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_YesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YesButton, lv_color_hex(0xFB0031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YesLabel = lv_label_create(ui_YesButton);
    lv_obj_set_width(ui_YesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_YesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YesLabel, "YES");
    lv_obj_set_style_text_font(ui_YesLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoButton = lv_btn_create(ui_WarningPanel);
    lv_obj_set_width(ui_NoButton, 100);
    lv_obj_set_height(ui_NoButton, 50);
    lv_obj_set_x(ui_NoButton, 97);
    lv_obj_set_y(ui_NoButton, 58);
    lv_obj_set_align(ui_NoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NoButton, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoLabel = lv_label_create(ui_NoButton);
    lv_obj_set_width(ui_NoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NoLabel, "NO");
    lv_obj_set_style_text_font(ui_NoLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningLabel = lv_label_create(ui_WarningPanel);
    lv_obj_set_width(ui_WarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningLabel, 1);
    lv_obj_set_y(ui_WarningLabel, -34);
    lv_obj_set_align(ui_WarningLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningLabel, "Do you really want\n to delete this scheduled event?");
    lv_obj_set_style_text_align(ui_WarningLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_TopBar7, 818);
    lv_obj_set_height(ui_TopBar7, 32);
    lv_obj_set_x(ui_TopBar7, 0);
    lv_obj_set_y(ui_TopBar7, -228);
    lv_obj_set_align(ui_TopBar7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar7, lv_color_hex(0x6AB36F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar7, lv_color_hex(0xE8EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel7 = lv_label_create(ui_TopBar7);
    lv_obj_set_width(ui_TimeLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel7, 0);
    lv_obj_set_y(ui_TimeLabel7, 0);
    lv_obj_set_align(ui_TimeLabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel7, "17:24");
    lv_obj_set_style_text_font(ui_TimeLabel7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel7 = lv_label_create(ui_TopBar7);
    lv_obj_set_width(ui_DateLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel7, -294);
    lv_obj_set_y(ui_DateLabel7, 1);
    lv_obj_set_align(ui_DateLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel7, "Wed, OCT 22 ");
    lv_obj_set_style_text_font(ui_DateLabel7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiNoti7 = lv_img_create(ui_TopBar7);
    lv_img_set_src(ui_WifiNoti7, &ui_img_1186191835);
    lv_obj_set_width(ui_WifiNoti7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiNoti7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiNoti7, 382);
    lv_obj_set_y(ui_WifiNoti7, 0);
    lv_obj_set_align(ui_WifiNoti7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiNoti7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_add_flag(ui_WifiNoti7, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_WifiNoti7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiNoti7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiNoti7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    

    // lv_obj_add_event_cb(ui_DeleteButtonEvent1, ui_event_DeleteButtonEvent1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ConfigButtonEvent1, ui_event_ConfigButtonEvent1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_SeenButtonEvent1, ui_event_SeenButtonEvent1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_DeleteButtonEvent2, ui_event_DeleteButtonEvent2, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ConfigButtonEvent2, ui_event_ConfigButtonEvent2, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_SeenButtonEvent2, ui_event_SeenButtonEvent2, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ConfigButtonEvent3, ui_event_ConfigButtonEvent3, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_SeenButtonEvent3, ui_event_SeenButtonEvent3, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_DeleteButtonEvent3, ui_event_DeleteButtonEvent3, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ConfigButtonEvent4, ui_event_ConfigButtonEvent4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_SeenButtonEvent4, ui_event_SeenButtonEvent4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_DeleteButtonEvent4, ui_event_DeleteButtonEvent4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ConfigButtonEvent5, ui_event_ConfigButtonEvent5, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_SeenButtonEvent5, ui_event_SeenButtonEvent5, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_DeleteButtonEvent5, ui_event_DeleteButtonEvent5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SchedulerButton7, ui_event_SchedulerButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchButton7, ui_event_SwitchButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton7, ui_event_WifiButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButotn7, ui_event_HomeButotn7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackToSchedulerButton, ui_event_BackToSchedulerButton, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_YesButton, ui_event_YesButton, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_NoButton, ui_event_NoButton, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_AddButton, ui_event_AddButton, LV_EVENT_ALL, NULL);

    
     
    // Gắn Event Handler cho nút ADD (Chuyển sang Screen 8 NEW)
    // Sửa tên handler từ ui_event_AddButton thành ui_event_AddButton_New để dùng logic mới
    lv_obj_add_event_cb(ui_AddButton, ui_event_AddButton_New, LV_EVENT_CLICKED, NULL);          /////////////////////////////////////////

    // // --- LOGIC SCHEDULER MỚI (Sử dụng Handler chung) ---
    // // Nút Config/Seen (Chuyển sang Screen 8 EDIT)
    lv_obj_add_event_cb(ui_ConfigButtonEvent1, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent1, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent2, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent2, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent3, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent3, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent4, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent4, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent5, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent5, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent6, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent6, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent7, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent7, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent8, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent8, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent9, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent9, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButtonEvent10, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SeenButtonEvent10, ui_event_ConfigEvent_Handler, LV_EVENT_CLICKED, NULL);

    // Nút Delete (Hiện Warning Panel)
    lv_obj_add_event_cb(ui_DeleteButtonEvent1, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent2, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent3, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent4, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent5, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent6, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent7, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent8, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent9, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DeleteButtonEvent10, ui_event_DeleteEvent_Handler, LV_EVENT_CLICKED, NULL);

    // Switch (Toggle trạng thái Event)
    lv_obj_add_event_cb(ui_EventSwitch1, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch2, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch3, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch4, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch5, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch6, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch7, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch8, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch9, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_EventSwitch10, ui_event_EventSwitch_Toggle, LV_EVENT_VALUE_CHANGED, NULL);
    
    // Nút Yes/No trên Warning Panel
    // Sửa tên handler để tránh trùng với handler cũ (ui_event_YesButton, ui_event_NoButton)
    lv_obj_add_event_cb(ui_YesButton, ui_event_YesButton_Delete, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_NoButton, ui_event_NoButton_Delete, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_OkButton, ui_event_OkButton, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_Screen7, ui_event_Screen7_Load, LV_EVENT_SCREEN_LOAD_START, NULL);
}
