// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#include "ui.h"
#include "ui_helpers.h"
#include "string.h"
#include "esp_log.h"
#include "stdio.h"
#include "storage.h"
#include "PCF8574.h"

///////////////////// VARIABLES ////////////////////

///////////////////// VARIABLES ////////////////////

bool volatile wifi_setup_done = false;
bool volatile switch_data_changed = false;

// SCREEN: ui_Screen5
// lv_obj_t *ui_Screen5;
// lv_obj_t *ui_Panel17;
// lv_obj_t *ui_Button10;
// lv_obj_t *ui_Label17;
// lv_obj_t *ui_Image10;
// lv_obj_t *ui_Button2;
// lv_obj_t *ui_Label5;
// lv_obj_t *ui_Image7;
// lv_obj_t *ui_Button3;
// lv_obj_t *ui_Label15;
// lv_obj_t *ui_Image8;
// lv_obj_t *ui_Button17;
// lv_obj_t *ui_Label24;
// lv_obj_t *ui_Image20;
// lv_obj_t *ui_Keyboard1;
// lv_obj_t *ui_Panel2;
// lv_obj_t *ui_TextArea1;
// lv_obj_t *ui_Panel3;
// lv_obj_t *ui_Label7;
// lv_obj_t *ui_Panel5;
// lv_obj_t *ui_Label8;
// lv_obj_t *ui_Panel7;
// lv_obj_t *ui_TextArea2;
// lv_obj_t *ui_Keyboard2;
// lv_obj_t *ui_Panel8;
// lv_obj_t *ui_Label12;
// lv_obj_t *ui_Image2;
// lv_obj_t *ui_Button8;
// lv_obj_t *ui_Label13;
// lv_obj_t *ui_Panel9;
// lv_obj_t *ui_Label10;
// lv_obj_t *ui_Image18;
// lv_obj_t *ui_Button6;
// lv_obj_t *ui_Image21;
// lv_obj_t *ui_Label1;
// lv_obj_t * ui_Image28;
// lv_obj_t * ui_Label49;
// lv_obj_t * ui_Label116;
// lv_obj_t * ui_Spinner1;

lv_obj_t * uic_DateLabel5;
lv_obj_t * uic_TimeLabel5;
lv_obj_t * uic_HomeImage5;
lv_obj_t * uic_HoneLabel5;
lv_obj_t * uic_HomeButton5;
lv_obj_t * uic_WifiImage5;
lv_obj_t * uic_WifiLabel5;
lv_obj_t * uic_WifiButton5;
lv_obj_t * uic_SwitchImage5;
lv_obj_t * uic_SwitchLabel5;
lv_obj_t * uic_SwitchButton5;
lv_obj_t * uic_SchedulerImage5;
lv_obj_t * uic_SchedulerLabel5;
lv_obj_t * uic_SchedulerButton5;
lv_obj_t * uic_BottomBarScreen5;
lv_obj_t * uic_ConfirmImage;
lv_obj_t * uic_ConfirmButton;
lv_obj_t * uic_WifiWarningImage;
lv_obj_t * uic_WifiWarningLabel;
lv_obj_t * uic_WifiWarningType;
lv_obj_t * uic_WifiLoadingSpinner;
lv_obj_t * uic_WifiLoadingLabel;
lv_obj_t * uic_WifiLoadingPanel;
lv_obj_t * uic_PasswordKeyboard;
lv_obj_t * uic_SSIDKeyboard;
lv_obj_t * uic_PasswordText;
lv_obj_t * uic_SSIDText;
lv_obj_t * uic_WifiPassPanel;
lv_obj_t * uic_WifiLogoImage;
lv_obj_t * ui_Screen5;
lv_obj_t * ui_WifiLogoImage;
lv_obj_t * ui_WifiPassPanel;
lv_obj_t * ui_SSIDText;
lv_obj_t * ui_PasswordText;
lv_obj_t * ui_SSIDKeyboard;
lv_obj_t * ui_PasswordKeyboard;
lv_obj_t * ui_WifiLoadingPanel;
lv_obj_t * ui_WifiLoadingLabel;
lv_obj_t * ui_WifiLoadingSpinner;
lv_obj_t * ui_WifiWarningType;
lv_obj_t * ui_WifiWarningLabel;
lv_obj_t * ui_WifiWarningImage;
lv_obj_t * ui_ConfirmButton;
lv_obj_t * ui_ConfirmImage;
lv_obj_t * ui_BottomBarScreen5;
lv_obj_t * ui_SchedulerButton5;
lv_obj_t * ui_SchedulerLabel5;
lv_obj_t * ui_SchedulerImage5;
lv_obj_t * ui_SwitchButton5;
lv_obj_t * ui_SwitchLabel5;
lv_obj_t * ui_SwitchImage5;
lv_obj_t * ui_WifiButton5;
lv_obj_t * ui_WifiLabel5;
lv_obj_t * ui_WifiImage5;
lv_obj_t * ui_HomeButton5;
lv_obj_t * ui_HoneLabel5;
lv_obj_t * ui_HomeImage5;
lv_obj_t * ui_TopBar5;
lv_obj_t * ui_TimeLabel5;
lv_obj_t * ui_DateLabel5;

// SCREEN: ui_Screen1
lv_obj_t * uic_WifiNoti1;
lv_obj_t * uic_TopBar1;
lv_obj_t * uic_Chart2;
lv_obj_t * uic_ChartPanel;
lv_obj_t * uic_HumidImage;
lv_obj_t * uic_TempImage;
lv_obj_t * uic_HumidLabel;
lv_obj_t * uic_TempLabel;
lv_obj_t * uic_MonitorPanel;
lv_obj_t * uic_HomeImage1;
lv_obj_t * uic_HomeLabel1;
lv_obj_t * uic_HomeButton1;
lv_obj_t * uic_WifiImage1;
lv_obj_t * uic_WifiLabel1;
lv_obj_t * uic_WifiButton1;
lv_obj_t * uic_SwitchImage1;
lv_obj_t * uic_SwitchLabel1;
lv_obj_t * uic_SwitchButton1;
lv_obj_t * uic_SchedulerImage1;
lv_obj_t * uic_SchedulerLabel1;
lv_obj_t * uic_SchedulerButton1;
lv_obj_t * uic_BottomBarScreen1;

lv_obj_t * ui_Screen1;
lv_obj_t * ui_BottomBarScreen1;
lv_obj_t * ui_SchedulerButton1;
lv_obj_t * ui_SchedulerLabel1;
lv_obj_t * ui_SchedulerImage1;
lv_obj_t * ui_SwitchButton1;
lv_obj_t * ui_SwitchLabel1;
lv_obj_t * ui_SwitchImage1;
lv_obj_t * ui_WifiButton1;
lv_obj_t * ui_WifiLabel1;
lv_obj_t * ui_WifiImage1;
lv_obj_t * ui_HomeButton1;
lv_obj_t * ui_HomeLabel1;
lv_obj_t * ui_HomeImage1;
lv_obj_t * ui_MonitorPanel;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_HumidLabel;
lv_obj_t * ui_TempImage;
lv_obj_t * ui_HumidImage;
lv_obj_t * ui_ChartPanel;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_TopBar1;
lv_obj_t * ui_TimeLabel1;
lv_obj_t * ui_DateLabel1;
lv_obj_t * ui_WifiNoti1;

lv_obj_t * ui_Panel6;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image12;
lv_chart_series_t * ui_Chart2_series_1;
lv_chart_series_t * ui_Chart2_series_2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Image3;


// SCREEN: ui_Screen2
lv_obj_t * ui_Switch[8];
lv_obj_t * ui_Screen2;
lv_obj_t * ui_LightPanel;
lv_obj_t * ui_LightLabel;
lv_obj_t * ui_LightImage;
lv_obj_t * ui_LightSlider;
lv_obj_t * ui_PumperPanel;
lv_obj_t * ui_PumperLabel;
lv_obj_t * ui_PumperImage;
lv_obj_t * ui_PumperSlider;
lv_obj_t * ui_SprayerPanel;
lv_obj_t * ui_SprayerLabel;
lv_obj_t * ui_SprayerImage;
lv_obj_t * ui_SprayerSlider;
lv_obj_t * ui_FanPanel;
lv_obj_t * ui_FanLabel;
lv_obj_t * ui_FanImage;
lv_obj_t * ui_FanSlider;
lv_obj_t * ui_BottomBarScreen2;
lv_obj_t * ui_SchedulerButton2;
lv_obj_t * ui_SchedulerLabel2;
lv_obj_t * ui_SchedulerImage2;
lv_obj_t * ui_SwitchButton2;
lv_obj_t * ui_SwitchLabel2;
lv_obj_t * ui_SwitchImage2;
lv_obj_t * ui_WifiButton2;
lv_obj_t * ui_WifiLabel2;
lv_obj_t * ui_WifiImage2;
lv_obj_t * ui_HomeButton2;
lv_obj_t * ui_HomeLabel2;
lv_obj_t * ui_HomeImage2;
lv_obj_t * ui_LightSwitchPanel;
lv_obj_t * ui_LightSwitch;
lv_obj_t * ui_LightSwitchLabel;
lv_obj_t * ui_PumperSwitchPanel;
lv_obj_t * ui_PumperSwitch;
lv_obj_t * ui_PumperSwitchLabel;
lv_obj_t * ui_SprayerSwitchPanel;
lv_obj_t * ui_SprayerSwitch;
lv_obj_t * ui_SprayerSwitchLabel;
lv_obj_t * ui_FanSwitchPanel;
lv_obj_t * ui_FanSwitch;
lv_obj_t * ui_FanSwitchLabel;
lv_obj_t * ui_TopBar2;
lv_obj_t * ui_TimeLabel2;
lv_obj_t * ui_DateLabel2;
lv_obj_t * ui_WifiNoti2;
lv_obj_t * ui_Date;
lv_obj_t * ui_Date2;
lv_obj_t * ui_OnGoingEvent;
lv_obj_t * ui_Event;
lv_obj_t * ui_ReloadButton;
lv_obj_t * ui_ReloadLabel;
lv_obj_t * ui_From;
lv_obj_t * ui_To_;
lv_obj_t * ui_FromTime;
lv_obj_t * ui_ToTime;
lv_obj_t * ui_SaveButton;
lv_obj_t * ui_SaveLabel;
lv_obj_t * ui_WarningPanel1;
lv_obj_t * ui_YesButton1;
lv_obj_t * ui_YesLabel1;
lv_obj_t * ui_NoButton1;
lv_obj_t * ui_NoLabel1;
lv_obj_t * ui_WarningLabel1;


// SCREEN: ui_Screen3
lv_obj_t *ui_LabelSwitch[8];
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Button18;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Image19;
lv_obj_t *ui_Button13;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Image14;
lv_obj_t *ui_Button15;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Image16;
lv_obj_t *ui_Button16;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Image17;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel20;
lv_obj_t *ui_Label26;
lv_obj_t *ui_Dropdown2;
lv_obj_t *ui_Panel21;
lv_obj_t *ui_Dropdown3;
lv_obj_t *ui_Dropdown4;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Panel22;
lv_obj_t *ui_Label28;
lv_obj_t *ui_TextArea3;
lv_obj_t *ui_Calendar1;
lv_obj_t *ui_Button19;
lv_obj_t *ui_Label36;
lv_obj_t *ui_Image23;
lv_obj_t *ui_Button20;
lv_obj_t *ui_Image22;
lv_obj_t *ui_Label37;
lv_obj_t *ui_Panel23;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Container2;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Container3;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Label32;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Label33;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Container7;
lv_obj_t *ui_Label38;
lv_obj_t *ui_Container8;
lv_obj_t *ui_Label39;
lv_obj_t *ui____initial_actions0;

// SCREEN: ui_Screen6
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Calendar3;
lv_obj_t * ui_BottomBarScreen6;
lv_obj_t * ui_SchedulerButton6;
lv_obj_t * ui_SchedulerLabel6;
lv_obj_t * ui_SchedulerImage6;
lv_obj_t * ui_SwitchButton6;
lv_obj_t * ui_SwitchLabel6;
lv_obj_t * ui_SwitchImage6;
lv_obj_t * ui_WifiButton6;
lv_obj_t * ui_WifiLabel6;
lv_obj_t * ui_WifiImage6;
lv_obj_t * ui_HomeButton6;
lv_obj_t * ui_HomeLabel6;
lv_obj_t * ui_HomeImage6;
lv_obj_t * ui_DotImage;
lv_obj_t * ui_TopBar6;
lv_obj_t * ui_TimeLabel6;
lv_obj_t * ui_DateLabel6;
lv_obj_t * ui_WifiNoti6;

// SCREEN: ui_Screen7

#define MAX_VISIBLE_EVENTS 10
lv_obj_t * ui_Screen7;
lv_obj_t * ui_EventsPanel;
lv_obj_t * ui_Event1;
lv_obj_t * ui_Event1Label;
lv_obj_t * ui_TimeLabelEvent1;
lv_obj_t * ui_DeleteButtonEvent1;
lv_obj_t * ui_ConfigButtonEvent1;
lv_obj_t * ui_SeenButtonEvent1;
lv_obj_t * ui_Slash1;
lv_obj_t * ui_Event2;
lv_obj_t * ui_Event2Label;
lv_obj_t * ui_TimeLabelEvent2;
lv_obj_t * ui_DeleteButtonEvent2;
lv_obj_t * ui_ConfigButtonEvent2;
lv_obj_t * ui_SeenButtonEvent2;
lv_obj_t * ui_Slash2;
lv_obj_t * ui_Event3;
lv_obj_t * ui_Event3Label;
lv_obj_t * ui_TimeLabelEvent3;
lv_obj_t * ui_ConfigButtonEvent3;
lv_obj_t * ui_SeenButtonEvent3;
lv_obj_t * ui_Slash3;
lv_obj_t * ui_DeleteButtonEvent3;
lv_obj_t * ui_Event4;
lv_obj_t * ui_Event4Label;
lv_obj_t * ui_TimeLabelEvent4;
lv_obj_t * ui_ConfigButtonEvent4;
lv_obj_t * ui_SeenButtonEvent4;
lv_obj_t * ui_Slash4;
lv_obj_t * ui_DeleteButtonEvent4;
lv_obj_t * ui_EventSwitch1;
lv_obj_t * ui_EventSwitch2;
lv_obj_t * ui_EventSwitch3;
lv_obj_t * ui_EventSwitch4;
lv_obj_t * ui_Event5;
lv_obj_t * ui_Event5Label;
lv_obj_t * ui_TimeLabelEvent5;
lv_obj_t * ui_ConfigButtonEvent5;
lv_obj_t * ui_SeenButtonEvent5;
lv_obj_t * ui_Slash5;
lv_obj_t * ui_DeleteButtonEvent5;
lv_obj_t * ui_EventSwitch5;
lv_obj_t * ui_Event6;
lv_obj_t * ui_Event6Label;
lv_obj_t * ui_TimeLabelEvent6;
lv_obj_t * ui_ConfigButtonEvent6;
lv_obj_t * ui_SeenButtonEvent6;
lv_obj_t * ui_Slash6;
lv_obj_t * ui_DeleteButtonEvent6;
lv_obj_t * ui_EventSwitch6;
lv_obj_t * ui_BottomBarScreen7;
lv_obj_t * ui_SchedulerButton7;
lv_obj_t * ui_SchedulerLabel7;
lv_obj_t * ui_SchedulerImage7;
lv_obj_t * ui_SwitchButton7;
lv_obj_t * ui_SwitchLabel7;
lv_obj_t * ui_SwitchImage7;
lv_obj_t * ui_WifiButton7;
lv_obj_t * ui_WifiLabel7;
lv_obj_t * ui_WifiImage7;
lv_obj_t * ui_HomeButotn7;
lv_obj_t * ui_HomeLabel7;
lv_obj_t * ui_HomeImage7;
lv_obj_t * ui_DateEventsLabel;
lv_obj_t * ui_BackToSchedulerButton;
lv_obj_t * ui_WarningPanel;
lv_obj_t * ui_YesButton;
lv_obj_t * ui_YesLabel;
lv_obj_t * ui_NoButton;
lv_obj_t * ui_NoLabel;
lv_obj_t * ui_WarningLabel;
lv_obj_t * ui_TopBar7;
lv_obj_t * ui_TimeLabel7;
lv_obj_t * ui_DateLabel7;
lv_obj_t * ui_WifiNoti7;
lv_obj_t * ui_AddButton;
lv_obj_t * ui_Event7;
lv_obj_t * ui_Event7Label;
lv_obj_t * ui_TimeLabelEvent7;
lv_obj_t * ui_ConfigButtonEvent7;
lv_obj_t * ui_SeenButtonEvent7;
lv_obj_t * ui_Slash7;
lv_obj_t * ui_DeleteButtonEvent7;
lv_obj_t * ui_EventSwitch7;
lv_obj_t * ui_MaxWarningPanel;
lv_obj_t * ui_MaxWarningLabel;
lv_obj_t * ui_OkButton;
lv_obj_t * ui_OkLabel;

//event 8
lv_obj_t * ui_Event8;
lv_obj_t * ui_Event8Label;
lv_obj_t * ui_TimeLabelEvent8;
lv_obj_t * ui_ConfigButtonEvent8;
lv_obj_t * ui_SeenButtonEvent8;
lv_obj_t * ui_Slash8;
lv_obj_t * ui_DeleteButtonEvent8;
lv_obj_t * ui_EventSwitch8;
//evnt 9
lv_obj_t * ui_Event9;
lv_obj_t * ui_Event9Label;
lv_obj_t * ui_TimeLabelEvent9;
lv_obj_t * ui_ConfigButtonEvent9;
lv_obj_t * ui_SeenButtonEvent9;
lv_obj_t * ui_Slash9;
lv_obj_t * ui_DeleteButtonEvent9;
lv_obj_t * ui_EventSwitch9;
//event 10
lv_obj_t * ui_Event10;   
lv_obj_t * ui_Event10Label;
lv_obj_t * ui_TimeLabelEvent10;
lv_obj_t * ui_ConfigButtonEvent10;
lv_obj_t * ui_SeenButtonEvent10;
lv_obj_t * ui_Slash10;
lv_obj_t * ui_DeleteButtonEvent10;
lv_obj_t * ui_EventSwitch10;

lv_obj_t * g_event_panels[] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_event_labels[] = { NULL, NULL, NULL , NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_time_labels[] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_config_buttons[] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_delete_buttons[] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_seen_buttons[] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL };
lv_obj_t * g_event_switches[] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
// Screen: ui_Screen8
lv_obj_t * ui_Screen8;
lv_obj_t * ui_LightPanelSche;
lv_obj_t * ui_LightLabelSche;
lv_obj_t * ui_LightImageSche;
lv_obj_t * ui_LightSliderSche;
lv_obj_t * ui_PumperPanelSche;
lv_obj_t * ui_PumperLabelSche;
lv_obj_t * ui_PumperImageSche;
lv_obj_t * ui_PumperSliderSche;
lv_obj_t * ui_SprayerPanelSche;
lv_obj_t * ui_SprayerLabelSche;
lv_obj_t * ui_SprayerImageSche;
lv_obj_t * ui_SprayerSliderSche;
lv_obj_t * ui_FanPanelSche;
lv_obj_t * ui_FanLabelSche;
lv_obj_t * ui_FanImageSche;
lv_obj_t * ui_FanSliderSche;
lv_obj_t * ui_BottomBarScreen8;
lv_obj_t * ui_SchedulerButton8;
lv_obj_t * ui_SchedulerLabel8;
lv_obj_t * ui_SchedulerImage8;
lv_obj_t * ui_SwitchButton8;
lv_obj_t * ui_SwitchLabel8;
lv_obj_t * ui_SwitchImage8;
lv_obj_t * ui_WifiButton8;
lv_obj_t * ui_WifiLabel8;
lv_obj_t * ui_WifiImage8;
lv_obj_t * ui_HomeButton8;
lv_obj_t * ui_HomeLabel8;
lv_obj_t * ui_HomeImage8;
lv_obj_t * ui_LightSwitchPanelSche;
lv_obj_t * ui_LightSwitchSche;
lv_obj_t * ui_LightSwitchLabelSche;
lv_obj_t * ui_PumperSwitchPanelSche;
lv_obj_t * ui_PumperSwitchSche;
lv_obj_t * ui_PumperSwitchLabelSche;
lv_obj_t * ui_SprayerSwitchPanelSche;
lv_obj_t * ui_SprayerSwitchSche;
lv_obj_t * ui_SprayerSwitchLabelSche;
lv_obj_t * ui_FanSwitchPanelSche;
lv_obj_t * ui_FanSwitchSche;
lv_obj_t * ui_FanSwitchLabelSche;
lv_obj_t * ui_EventLabel;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_EventText;
lv_obj_t * ui_FromSche;
lv_obj_t * ui_ToSche;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_FromRollerHour;
lv_obj_t * ui_FromRollerMinute;
lv_obj_t * ui_Label100;
lv_obj_t * ui_SaveButtonSche;
lv_obj_t * ui_DoubleDot1;
lv_obj_t * ui_DoubleDot2;
lv_obj_t * ui_BackButton;
lv_obj_t * ui_ToRollerHour;
lv_obj_t * ui_ToRollerMinute;
lv_obj_t * ui_BackLabel;
lv_obj_t * ui_KeyboardLabel;
lv_obj_t * ui_HourPanel1;
lv_obj_t * ui_HourLabel1;
lv_obj_t * ui_OkeButton;
lv_obj_t * ui_OkeLabel;


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ///////////////////
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// void ui_event_Keyboard1(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
   
//     if(event_code == LV_EVENT_READY) {
//         const char * text = lv_textarea_get_text(ui_TextArea1);
//         if(strlen(text) > 0) {
//             _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//             _ui_state_modify(ui_TextArea1, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
//         }
//         else {
//             lv_label_set_text(ui_Label12, "	  Please type in your Wi-Fi settings!");
//             _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//         }
//     }
// }
 void ui_event_KeyboardLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
   
    if(event_code == LV_EVENT_READY) {
        const char * text = lv_textarea_get_text(ui_EventText);
        if(strlen(text) > 0) {
            _ui_flag_modify(ui_KeyboardLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_state_modify(ui_EventText, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        }
        else {
            // lv_label_set_text(ui_Label12, "	  Please type in your Wi-Fi settings!");
            // _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
    }
}
void ui_event_EventText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
// void ui_event_TextArea1(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_FOCUSED) {
//         _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//     }
//     if(event_code == LV_EVENT_DEFOCUSED) {
//         _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_TextArea2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_FOCUSED) {
//         _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//     }
//     if(event_code == LV_EVENT_DEFOCUSED) {
//         _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Keyboard2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_READY) {
//         const char * text = lv_textarea_get_text(ui_TextArea2);
//         if (strlen(text) > 0) {
//             _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//             _ui_state_modify(ui_TextArea2, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
//         }
//         else {
//             lv_label_set_text(ui_Label12, "	  Please type in your Wi-Fi settings!");
//             _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//         }
//     }
// }
// void ui_event_Button6(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         const char * ssid = lv_textarea_get_text(ui_TextArea1);
//         const char * password = lv_textarea_get_text(ui_TextArea2);
//         if(strlen(ssid) > 0 && strlen(password) > 0) {
//             wifi_setup_done = true;
//             _ui_flag_modify(ui_Panel9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//         }
//         else {
//             lv_label_set_text(ui_Label12, "	  Please type in your Wi-Fi settings!");
//             _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//         }
//     }
// }

// void ui_event_Button8(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }

//Screen 5

void ui_event_SSIDText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_SSIDKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_SSIDKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PasswordText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SSIDKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
   
    if(event_code == LV_EVENT_READY) {
        const char * text = lv_textarea_get_text(ui_SSIDText);
        if(strlen(text) > 0) {
            _ui_flag_modify(ui_SSIDKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_state_modify(ui_SSIDText, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        }
        else {
            lv_label_set_text(ui_WifiWarningLabel, "	  Please type in your Wi-Fi settings!");
            _ui_flag_modify(ui_WifiWarningType, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
    }
}

void ui_event_PasswordKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        const char * text = lv_textarea_get_text(ui_PasswordText);
        if (strlen(text) > 0) {
            _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
            _ui_state_modify(ui_PasswordText, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        }
        else {
            lv_label_set_text(ui_WifiWarningLabel, "	  Please type in your Wi-Fi settings!");
            _ui_flag_modify(ui_WifiWarningType, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
    }
}

void ui_event_ConfirmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        const char * ssid = lv_textarea_get_text(ui_SSIDText);
        const char * password = lv_textarea_get_text(ui_PasswordText);
        if(strlen(ssid) > 0 && strlen(password) > 0) {
            wifi_setup_done = true;
            _ui_flag_modify(ui_WifiLoadingPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
        else {
            lv_label_set_text(ui_WifiWarningLabel, "	  Please type in your Wi-Fi settings!");
            _ui_flag_modify(ui_WifiWarningType, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }
    }
}

void ui_event_WifiWarningType(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_WifiWarningType, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}


void ui_event_SchedulerButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_SwitchButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_WifiButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_HomeButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}
/////Screen 1

void ui_event_SchedulerButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_SwitchButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_WifiButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_HomeButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}


////Screen 2

void ui_event_SchedulerButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_SwitchButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_WifiButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_ReloadButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        update_screen2_ui();
    }
}
void ui_event_HomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_SaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        
        // 1. THU THẬP DỮ LIỆU MỚI TỪ UI VÀO BUFFER TẠM THỜI
        g_temp_override_event.device_levels[0] = (uint8_t)lv_slider_get_value(ui_LightSlider);
        g_temp_override_event.device_states[0] = lv_obj_has_state(ui_LightSwitch, LV_STATE_CHECKED);
        
        // ... (Thu thập tương tự cho SPRAYER, PUMPER, FAN Index 1, 2, 3)
        g_temp_override_event.device_levels[1] = (uint8_t)lv_slider_get_value(ui_SprayerSlider);
        g_temp_override_event.device_states[1] = lv_obj_has_state(ui_SprayerSwitch, LV_STATE_CHECKED);
        
        g_temp_override_event.device_levels[2] = (uint8_t)lv_slider_get_value(ui_PumperSlider);
        g_temp_override_event.device_states[2] = lv_obj_has_state(ui_PumperSwitch, LV_STATE_CHECKED);

        g_temp_override_event.device_levels[3] = (uint8_t)lv_slider_get_value(ui_FanSlider);
        g_temp_override_event.device_states[3] = lv_obj_has_state(ui_FanSwitch, LV_STATE_CHECKED);

        
        // 2. KIỂM TRA ĐIỀU KIỆN CẢNH BÁO
        if (g_is_event_running && g_active_scheduler_index != -1) {
            // Có Event đang chạy và cần cảnh báo ghi đè
            
            // Cập nhật Label cảnh báo
            if (g_active_scheduler_index < event_count) {
                 char msg[200];
                 // Lấy tên event đang bị ghi đè
                 sprintf(msg, "Do you really want to disable\nevent '%s' and apply manual settings?", 
                         event_list[g_active_scheduler_index].label);
                 lv_label_set_text(ui_WarningLabel1, msg);
            }
            
            // Hiện Panel cảnh báo
            _ui_flag_modify(ui_WarningPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        } else {
            // Không có Event Scheduler nào đang chạy, chỉ cần áp dụng thay đổi thủ công.
            Serial.println("Manual states applied without override warning.");
            // Chuyển sang hàm YesButton logic để áp dụng g_temp_override_event cho g_current_active_event
            ui_event_YesButton1(e); 
        }
    }
}

void ui_event_YesButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        
        // 1. Ghi đè g_current_active_event bằng giá trị mới từ g_temp_override_event
        if (xSemaphoreTake(g_event_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
            // Sao chép toàn bộ trạng thái thiết bị mới
            memcpy(&g_current_active_event.device_states, &g_temp_override_event.device_states, sizeof(g_current_active_event.device_states));
            memcpy(&g_current_active_event.device_levels, &g_temp_override_event.device_levels, sizeof(g_current_active_event.device_levels));
            
            // 2. DISABLE EVENT GỐC trong event_list
            if (g_is_event_running && g_active_scheduler_index != -1 && g_active_scheduler_index < event_count) {
                
                // Đặt Event gốc thành Disable
                event_list[g_active_scheduler_index].is_enabled = false;
                
                // Lưu lại danh sách Event vào NVS
                if (save_event_list()) {
                     Serial.printf("SUCCESS: Disabled scheduled event at index %d due to manual override.\n", g_active_scheduler_index);
                } else {
                     Serial.println("ERROR: Failed to save event list after disabling scheduled event.");
                }
            }
            
            // Đặt cờ Event running thành FALSE (để biết đã bị override)
            g_is_event_running = false; 
            g_active_scheduler_index = -1; // Reset index đã bị disable

            xSemaphoreGive(g_event_mutex);
            sync_all_attributes_to_server(); // Đồng bộ trạng thái mới lên server
        }
        
        // 3. Ẩn Panel cảnh báo
        _ui_flag_modify(ui_WarningPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        
        // LƯU Ý: Task HardwareControlTask sẽ tự động nhận giá trị mới từ g_current_active_event và điều khiển thiết bị.
    }
}

void ui_event_NoButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// void ui_event_Button7(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
//     }
// }
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[0], LV_STATE_CHECKED);
        switch_data_array[0].state = state;
        PCF8574_WritePin(0, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch2(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[1], LV_STATE_CHECKED);
        switch_data_array[1].state = state;
        PCF8574_WritePin(1, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch3(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[2], LV_STATE_CHECKED);
        switch_data_array[2].state = state;
        PCF8574_WritePin(2, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch4(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[3], LV_STATE_CHECKED);
        switch_data_array[3].state = state;
        PCF8574_WritePin(3, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch5(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[4], LV_STATE_CHECKED);
        switch_data_array[4].state = state;
        PCF8574_WritePin(4, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch6(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[5], LV_STATE_CHECKED);
        switch_data_array[5].state = state;
        PCF8574_WritePin(5, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch7(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[6], LV_STATE_CHECKED);
        switch_data_array[6].state = state;
        PCF8574_WritePin(6, state);
        switch_data_changed = true;
    }
}

void ui_event_Switch8(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bool state = lv_obj_has_state(ui_Switch[7], LV_STATE_CHECKED);
        switch_data_array[7].state = state;
        PCF8574_WritePin(7, state);
        switch_data_changed = true;
    }
}

void update_screen2_ui() {
    // 1. Kiểm tra Mutex trước khi đọc g_current_active_event
    if (xSemaphoreTake(g_event_mutex, pdMS_TO_TICKS(10)) == pdTRUE) {
        
        // 2. Cập nhật Event/Time Label (On Going Event)
        if (g_is_event_running) {
            lv_label_set_text(ui_OnGoingEvent, "On going event:");
            lv_label_set_text(ui_Event, g_current_active_event.label);
            
            char from_time[6], to_time[6];
            sprintf(from_time, "%02d:%02d", g_current_active_event.start_hour, g_current_active_event.start_minute);
            sprintf(to_time, "%02d:%02d", g_current_active_event.end_hour, g_current_active_event.end_minute);
            
            lv_label_set_text(ui_FromTime, from_time);
            lv_label_set_text(ui_ToTime, to_time);
            
            // 3. Cập nhật trạng thái và Slider của thiết bị
            // Ánh xạ g_current_active_event -> UI Widgets
            
            

            // Hiển thị Warning Panel khi Save
            // _ui_flag_modify(ui_WarningPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
            
        } else {
            // Không có Event nào chạy -> Reset UI về mặc định
            lv_label_set_text(ui_OnGoingEvent, "No event running");
            lv_label_set_text(ui_Event, "");
            lv_label_set_text(ui_FromTime, "");
            lv_label_set_text(ui_ToTime, "");
        }
        // LIGHT (Index 0)
            lv_slider_set_value(ui_LightSlider, g_current_active_event.device_levels[0], LV_ANIM_OFF);
            if (g_current_active_event.device_states[0]) lv_obj_add_state(ui_LightSwitch, LV_STATE_CHECKED);
            else lv_obj_clear_state(ui_LightSwitch, LV_STATE_CHECKED);

            // SPRAYER (Index 1)
            lv_slider_set_value(ui_SprayerSlider, g_current_active_event.device_levels[1], LV_ANIM_OFF);
            if (g_current_active_event.device_states[1]) lv_obj_add_state(ui_SprayerSwitch, LV_STATE_CHECKED);
            else lv_obj_clear_state(ui_SprayerSwitch, LV_STATE_CHECKED);
            
            // PUMPER (Index 2)
            lv_slider_set_value(ui_PumperSlider, g_current_active_event.device_levels[2], LV_ANIM_OFF);
            if (g_current_active_event.device_states[2]) lv_obj_add_state(ui_PumperSwitch, LV_STATE_CHECKED);
            else lv_obj_clear_state(ui_PumperSwitch, LV_STATE_CHECKED);
            
            // FAN (Index 3)
            lv_slider_set_value(ui_FanSlider, g_current_active_event.device_levels[3], LV_ANIM_OFF);
            if (g_current_active_event.device_states[3]) lv_obj_add_state(ui_FanSwitch, LV_STATE_CHECKED);
            else lv_obj_clear_state(ui_FanSwitch, LV_STATE_CHECKED);
        xSemaphoreGive(g_event_mutex);
    } else {
        Serial.println("ERROR: Could not take Mutex in update_screen2_ui!");
    }
}

void ui_event_Screen2_Load(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        update_screen2_ui(); 
    }
}
////Screen 3
// void ui_event_Button18(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
//     }
// }
// void ui_event_Button13(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
//     }
// }
// void ui_event_Button15(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
//     }
// }
// void ui_event_Button16(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
//     }
// }

// void ui_event_Calendar1(lv_event_t *e) {
//     lv_event_code_t code = lv_event_get_code(e);
//     lv_obj_t *obj = lv_event_get_target(e);
//     if(code == LV_EVENT_VALUE_CHANGED) {
//         lv_calendar_date_t selected_date;

//         // Use return value to check validity
//         if (lv_calendar_get_pressed_date(ui_Calendar1, &selected_date) == LV_RES_OK) {
//             char date_str[20];
//             sprintf(date_str, "%02d-%02d-%04d", selected_date.day, selected_date.month, selected_date.year);

//             // Highlight the selected date
//             static lv_calendar_date_t highlighted_dates[1];
//             highlighted_dates[0] = selected_date;

//             lv_calendar_set_highlighted_dates(ui_Calendar1, highlighted_dates, 1);
//             lv_textarea_set_text(ui_TextArea3, date_str); // Set the selected date in the TextArea
//         }
//     }
// }

// void ui_event_TextArea3(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_FOCUSED) {
//         _ui_flag_modify(ui_Calendar1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//     }
//     //calendar and textarea are unfocused
//     if(event_code == LV_EVENT_DEFOCUSED) {
//         _ui_flag_modify(ui_Calendar1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }

// void ui_event_Button19(lv_event_t * e){
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_Panel23, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
//     }
//     if(event_code == LV_EVENT_DEFOCUSED) {
//         _ui_flag_modify(ui_Panel23, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }

// void ui_event_Button20(lv_event_t * e){
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     const char * text = lv_textarea_get_text(ui_TextArea3);
//     char chswitch[10];
//     char chhour[3];
//     char chminute[3];
//     char state[4];
//     lv_dropdown_get_selected_str(ui_Dropdown1, chhour, 3);
//     lv_dropdown_get_selected_str(ui_Dropdown2, chminute, 3);
//     lv_dropdown_get_selected_str(ui_Dropdown3, chswitch, 10);
//     lv_dropdown_get_selected_str(ui_Dropdown4, state, 4);
//     char time_str[40];
//     tm time = {0};
//     time.tm_hour = atoi(chhour);
//     time.tm_min = atoi(chminute);
//     time.tm_year = atoi(text + 6) - 1900; 
//     time.tm_mon = atoi(text + 3) - 1;
//     time.tm_mday = atoi(text);
//     sprintf(time_str, "%02d-%02d-%04d, %02d:%02d, turn %s", time.tm_mday, time.tm_mon + 1, time.tm_year + 1900, time.tm_hour, time.tm_min, state);
//     if(event_code == LV_EVENT_CLICKED && text != NULL) {
//         if(strcmp(chswitch, "Switch 1") == 0){
//             lv_label_set_text(ui_LabelSwitch[0], time_str);
//             strcpy(switch_data_array[0].name, chswitch);
//             strcpy(switch_data_array[0].schedule, time_str);
//             switch_data_array[0].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 2") == 0){
//             lv_label_set_text(ui_LabelSwitch[1], time_str);
//             strcpy(switch_data_array[1].name, chswitch);
//             strcpy(switch_data_array[1].schedule, time_str);
//             switch_data_array[1].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 3") == 0){
//             lv_label_set_text(ui_LabelSwitch[2], time_str);
//             strcpy(switch_data_array[2].name, chswitch);
//             strcpy(switch_data_array[2].schedule, time_str);
//             switch_data_array[2].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 4") == 0){
//             lv_label_set_text(ui_LabelSwitch[3], time_str);
//             strcpy(switch_data_array[3].name, chswitch);
//             strcpy(switch_data_array[3].schedule, time_str);
//             switch_data_array[3].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 5") == 0){
//             lv_label_set_text(ui_LabelSwitch[4], time_str);
//             strcpy(switch_data_array[4].name, chswitch);
//             strcpy(switch_data_array[4].schedule, time_str);
//             switch_data_array[4].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 6") == 0){
//             lv_label_set_text(ui_LabelSwitch[5], time_str);
//             strcpy(switch_data_array[5].name, chswitch);
//             strcpy(switch_data_array[5].schedule, time_str);
//             switch_data_array[5].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 7") == 0){
//             lv_label_set_text(ui_LabelSwitch[6], time_str);
//             strcpy(switch_data_array[6].name, chswitch);
//             strcpy(switch_data_array[6].schedule, time_str);
//             switch_data_array[6].scheduletime = time;
//         }
//         else if(strcmp(chswitch, "Switch 8") == 0){
//             lv_label_set_text(ui_LabelSwitch[7], time_str);
//             strcpy(switch_data_array[7].name, chswitch);
//             strcpy(switch_data_array[7].schedule, time_str);
//             switch_data_array[7].scheduletime = time;
//         }
//         switch_data_changed = true;
//     }
// }

////Screen 6
void ui_event_Calendar3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        lv_calendar_date_t pressed_date;
        
        // 1. Cố gắng lấy ngày được chọn từ Calendar
        if (lv_calendar_get_pressed_date(ui_Calendar3, &pressed_date) == LV_RES_OK) {
            //2. Lưu ngày vào biến toàn cục g_selected_date
            g_selected_date.year = pressed_date.year;
            g_selected_date.month = pressed_date.month;
            g_selected_date.day = pressed_date.day;
            
            // Đánh dấu không phải là chỉnh sửa Event
            g_event_edit_index = -1;
            
            // 3. Chuyển sang Screen 7 (Danh sách Event)
             _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen7_screen_init);
        }
    }
}
void ui_event_SchedulerButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_SwitchButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_WifiButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

/// Screen 7
void ui_event_Screen7_Load(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        // Hàm helper này cần được gọi để tải dữ liệu Event lên Screen 7
        update_screen7_event_list(); 
    }
}

void ui_event_DeleteButtonEvent1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_ConfigButtonEvent1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_SeenButtonEvent1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_DeleteButtonEvent2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_ConfigButtonEvent2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_SeenButtonEvent2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_ConfigButtonEvent3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_SeenButtonEvent3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_DeleteButtonEvent3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_ConfigButtonEvent4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_SeenButtonEvent4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_DeleteButtonEvent4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_ConfigButtonEvent5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_SeenButtonEvent5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_DeleteButtonEvent5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_SchedulerButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_SwitchButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_WifiButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButotn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_BackToSchedulerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_YesButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_NoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_OkButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_MaxWarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
size_t count_active_events_for_date() {
    size_t active_count = 0;
    
    // Đảm bảo dữ liệu Event List được tải mới nhất
    load_event_list(); 
    
    for (size_t i = 0; i < event_count; i++) {
        scheduler_event_t * current_event = &event_list[i];
        

        // Kiểm tra xem Event này có hợp lệ cho ngày được chọn không
        // Sử dụng hàm lọc đã thiết lập
        if (is_event_active_on_selected_date(current_event, &g_selected_date)) {
            active_count++;
        }
    }
    return active_count;
}
void ui_event_AddButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}

// void setup_event_panels_array() {
//     g_event_panels[0] = ui_Event1;
//     g_event_panels[1] = ui_Event2;
//     g_event_panels[2] = ui_Event3;
//     g_event_panels[3] = ui_Event4;
//     g_event_panels[4] = ui_Event5;
// }
void setup_global_ui_arrays() {
    // 1. Khai báo các mảng global widget (đã được khai báo extern trong ui.h)
    
    // Mảng Event Panels (Dùng để hiển thị/ẩn hàng Event)
    g_event_panels[0] = ui_Event1;
    g_event_panels[1] = ui_Event2;
    g_event_panels[2] = ui_Event3;
    g_event_panels[3] = ui_Event4;
    g_event_panels[4] = ui_Event5;
    g_event_panels[5] = ui_Event6;
    g_event_panels[6] = ui_Event7;
    g_event_panels[7] = ui_Event8;
    g_event_panels[8] = ui_Event9;
    g_event_panels[9] = ui_Event10;

    // Mảng Label Tên Event
    g_event_labels[0] = ui_Event1Label;
    g_event_labels[1] = ui_Event2Label;
    g_event_labels[2] = ui_Event3Label;
    g_event_labels[3] = ui_Event4Label;
    g_event_labels[4] = ui_Event5Label;
    g_event_labels[5] = ui_Event6Label;
    g_event_labels[6] = ui_Event7Label;
    g_event_labels[7] = ui_Event8Label;
    g_event_labels[8] = ui_Event9Label;
    g_event_labels[9] = ui_Event10Label;

    // Mảng Label Thời gian
    g_time_labels[0] = ui_TimeLabelEvent1;
    g_time_labels[1] = ui_TimeLabelEvent2;
    g_time_labels[2] = ui_TimeLabelEvent3;
    g_time_labels[3] = ui_TimeLabelEvent4;
    g_time_labels[4] = ui_TimeLabelEvent5;
    g_time_labels[5] = ui_TimeLabelEvent6;
    g_time_labels[6] = ui_TimeLabelEvent7;
    g_time_labels[7] = ui_TimeLabelEvent8;
    g_time_labels[8] = ui_TimeLabelEvent9;
    g_time_labels[9] = ui_TimeLabelEvent10;

    // Mảng Nút Config/Seen (Edit/View)
    g_config_buttons[0] = ui_ConfigButtonEvent1;
    g_config_buttons[1] = ui_ConfigButtonEvent2;
    g_config_buttons[2] = ui_ConfigButtonEvent3;
    g_config_buttons[3] = ui_ConfigButtonEvent4;
    g_config_buttons[4] = ui_ConfigButtonEvent5;
    g_config_buttons[5] = ui_ConfigButtonEvent6;
    g_config_buttons[6] = ui_ConfigButtonEvent7;
    g_config_buttons[7] = ui_ConfigButtonEvent8;
    g_config_buttons[8] = ui_ConfigButtonEvent9;
    g_config_buttons[9] = ui_ConfigButtonEvent10;

    // Mảng Nút Delete
    g_delete_buttons[0] = ui_DeleteButtonEvent1;
    g_delete_buttons[1] = ui_DeleteButtonEvent2;
    g_delete_buttons[2] = ui_DeleteButtonEvent3;
    g_delete_buttons[3] = ui_DeleteButtonEvent4;
    g_delete_buttons[4] = ui_DeleteButtonEvent5;
    g_delete_buttons[5] = ui_DeleteButtonEvent6;
    g_delete_buttons[6] = ui_DeleteButtonEvent7;
    g_delete_buttons[7] = ui_DeleteButtonEvent8;
    g_delete_buttons[8] = ui_DeleteButtonEvent9;
    g_delete_buttons[9] = ui_DeleteButtonEvent10;
    
    // Mảng Switch (Toggle Event)
    g_event_switches[0] = ui_EventSwitch1;
    g_event_switches[1] = ui_EventSwitch2;
    g_event_switches[2] = ui_EventSwitch3;
    g_event_switches[3] = ui_EventSwitch4;
    g_event_switches[4] = ui_EventSwitch5;
    g_event_switches[5] = ui_EventSwitch6;
    g_event_switches[6] = ui_EventSwitch7;
    g_event_switches[7] = ui_EventSwitch8;
    g_event_switches[8] = ui_EventSwitch9;
    g_event_switches[9] = ui_EventSwitch10;

    g_seen_buttons[0] = ui_SeenButtonEvent1;
    g_seen_buttons[1] = ui_SeenButtonEvent2;
    g_seen_buttons[2] = ui_SeenButtonEvent3;
    g_seen_buttons[3] = ui_SeenButtonEvent4;
    g_seen_buttons[4] = ui_SeenButtonEvent5;
    g_seen_buttons[5] = ui_SeenButtonEvent6;
    g_seen_buttons[6] = ui_SeenButtonEvent7;
    g_seen_buttons[7] = ui_SeenButtonEvent8;    
    g_seen_buttons[8] = ui_SeenButtonEvent9;
    g_seen_buttons[9] = ui_SeenButtonEvent10;
    Serial.println("Global UI arrays re-initialized successfully.");
}
int get_day_of_week(uint16_t year, uint8_t month, uint8_t day) {
    struct tm t = {0};
    t.tm_year = year - 1900;
    t.tm_mon = month - 1;
    t.tm_mday = day;
    // Gọi hàm mktime để tính tm_wday (ngày trong tuần)
    mktime(&t); 
    // tm_wday: 0=CN, 1=T2, ..., 6=T7
    return t.tm_wday; 
}
const char* get_day_name(int dow) {
    // DOW: 0=CN, 1=T2, ..., 6=T7 (theo POSIX)
    switch (dow) {
        case 0: return "Sunday";
        case 1: return "Monday";
        case 2: return "Tuesday";
        case 3: return "Wednesday";
        case 4: return "Thursday";
        case 5: return "Friday";
        case 6: return "Saturday";
        default: return "";
    }
}
const char* get_day_name_top_bar(int dow) {
    // DOW: 0=CN, 1=T2, ..., 6=T7 (theo POSIX)
    switch (dow) {
        case 0: return "Sun";
        case 1: return "Mon";
        case 2: return "Tue";
        case 3: return "Wed";
        case 4: return "Thu";
        case 5: return "Fri";
        case 6: return "Sat";
        default: return "";
    }
}

const char* get_month_name_top_bar(int month) {
    // Tháng được truyền vào thường là 1 (Jan) đến 12 (Dec)
    switch (month) {
        case 1: return "JAN";
        case 2: return "FEB";
        case 3: return "MAR";
        case 4: return "APR";
        case 5: return "MAY";
        case 6: return "JUN";
        case 7: return "JUL";
        case 8: return "AUG";
        case 9: return "SEP";
        case 10: return "OCT";
        case 11: return "NOV";
        case 12: return "DEC";
        default: return ""; // Trả về chuỗi rỗng nếu tháng không hợp lệ
    }
}

bool is_event_active_on_selected_date(const scheduler_event_t *event, const selected_date_t *selected_date) {
    if (event->year == selected_date->year &&
        event->month == selected_date->month &&
        event->day == selected_date->day) 
    {
        return true;
    }

    // --- Trường hợp 1: Event Lặp lại Hàng tuần (Weekly Repeat) ---
    if (event->repeat_weekly) {
        
        // 1. Lấy ngày trong tuần (DOW) của Event đã lưu (Ngày Event được tạo/lưu)
        // Đây là DOW mà Event cần lặp lại hàng tuần.
        int event_dow = get_day_of_week(event->year, event->month, event->day);
        
        // 2. Lấy ngày trong tuần (DOW) của Ngày được chọn trên lịch
        int selected_dow = get_day_of_week(selected_date->year, selected_date->month, selected_date->day);
        
        // 3. Kiểm tra xem hai ngày trong tuần có trùng nhau không
        if (event_dow == selected_dow) {
            return true;
        }
        
        return false;
    } 

    // --- Trường hợp 2: Event Một lần (Single Event) ---
    
    // Kiểm tra chính xác ngày, tháng, năm đã lưu trong Event struct
    

    return false; // Không khớp
}
void update_screen7_event_list() {
    // 1. Tải Event List mới nhất từ NVS
    load_event_list(); 
    //setup_event_panels_array();
    
    // 2. Cập nhật ngày hiển thị trên Screen 7
    char date_str[100];
    int dow = get_day_of_week(g_selected_date.year, g_selected_date.month, g_selected_date.day);
    const char* day_name = get_day_name(dow);

// Định dạng chuỗi mới: "Events on Thứ X, DD/MM/YYYY"
sprintf(date_str, "Events on %s, %02d/%02d/%04d", 
        day_name, 
        g_selected_date.day, 
        g_selected_date.month, 
        g_selected_date.year);
    lv_label_set_text(ui_DateEventsLabel, date_str);
    
    for (size_t i = 0; i < MAX_VISIBLE_EVENTS; i++) {
        _ui_flag_modify(g_event_panels[i], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        if (g_event_switches[i] != NULL) {
             // CLEAR trạng thái switch để tránh lỗi "switch stuck ON"
            lv_obj_clear_state(g_event_switches[i], LV_STATE_CHECKED);
        }
    }

    int visible_events_count = 0;
    
    //3. Duyệt qua danh sách Event và cập nhật Panel //event_count && visible_events_count < MAX_VISIBLE_EVENTS
    for (size_t i = 0; i < event_count && visible_events_count < MAX_VISIBLE_EVENTS; i++) {
         scheduler_event_t * current_event = &event_list[i];
        
    //     // // --- LOGIC LỌC TẠM THỜI ---
    //     // // Hiện tại, chúng ta bỏ qua lọc theo ngày. Sau này, bạn cần thêm logic kiểm tra xem
    //     // // Event này có trùng với g_selected_date không (dựa trên repeat_weekly hoặc ngày cụ thể).
    //     // // Tạm thời, chỉ hiển thị tất cả Event đã lưu.
        if (!is_event_active_on_selected_date(current_event, &g_selected_date)) {
            continue; // Bỏ qua Event này nếu nó không hoạt động vào ngày đã chọn
        }
         lv_obj_t * event_panel = g_event_panels[visible_events_count];
        
    //     // // Hiện Panel
         _ui_flag_modify(event_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    //     // a. Tên Event
         lv_label_set_text(g_event_labels[visible_events_count], current_event->label);
        
    //     // b. Thời gian Event
          char time_range[16];
          sprintf(time_range, "%02d:%02d - %02d:%02d", 
            current_event->start_hour, current_event->start_minute, 
             current_event->end_hour, current_event->end_minute);
          lv_label_set_text(g_time_labels[visible_events_count], time_range);
        
    //     // c. Trạng thái Switch (Bật/Tắt Event)
          if (current_event->is_enabled) {
              lv_obj_add_state(g_event_switches[visible_events_count], LV_STATE_CHECKED);
          } else {
              lv_obj_clear_state(g_event_switches[visible_events_count], LV_STATE_CHECKED);
          }
        
    //     // d. Lưu Event Index vào User Data của các nút và Switch
        //Việc này giúp chúng ta biết Event nào đang được thao tác khi nhấn nút.
        lv_obj_set_user_data(g_config_buttons[visible_events_count], (void*)i);
        lv_obj_set_user_data(g_delete_buttons[visible_events_count], (void*)i);
        lv_obj_set_user_data(g_seen_buttons[visible_events_count], (void*)i);
         lv_obj_set_user_data(g_event_switches[visible_events_count], (void*)i);

         visible_events_count++;
    }
    
    //4. Ẩn các Panel Event còn lại
    // for (size_t i = visible_events_count; i < MAX_VISIBLE_EVENTS; i++) {
    //     _ui_flag_modify(g_event_panels[i], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    // }
}

/// Screen 8
void ui_event_Screen8_Load(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        update_screen8_editor();
    }
}

void update_screen8_editor() {
    if (g_event_edit_index >= 0 && g_event_edit_index < event_count) {
        // --- CHẾ ĐỘ CHỈNH SỬA (EDIT) ---
        scheduler_event_t * current_event = &event_list[g_event_edit_index];
        lv_label_set_text(ui_EventLabel, "Label:"); 
        
        // 1. Tên và Checkbox
        lv_textarea_set_text(ui_EventText, current_event->label);
        if (current_event->repeat_weekly) lv_obj_add_state(ui_Checkbox1, LV_STATE_CHECKED);
        else lv_obj_clear_state(ui_Checkbox1, LV_STATE_CHECKED);

        // 2. Thời gian
        lv_roller_set_selected(ui_FromRollerHour, current_event->start_hour, LV_ANIM_OFF);
        lv_roller_set_selected(ui_FromRollerMinute, current_event->start_minute, LV_ANIM_OFF);
        lv_roller_set_selected(ui_ToRollerHour, current_event->end_hour, LV_ANIM_OFF);
        lv_roller_set_selected(ui_ToRollerMinute, current_event->end_minute, LV_ANIM_OFF);

        // 3. Thiết bị (Lấy 4 thiết bị: 0=LIGHT, 1=SPRAYER, 2=PUMP, 3=FAN)
        lv_slider_set_value(ui_LightSliderSche, current_event->device_levels[0], LV_ANIM_OFF);
        if (current_event->device_states[0]) lv_obj_add_state(ui_LightSwitchSche, LV_STATE_CHECKED);
        else lv_obj_clear_state(ui_LightSwitchSche, LV_STATE_CHECKED);
        
        lv_slider_set_value(ui_SprayerSliderSche, current_event->device_levels[1], LV_ANIM_OFF);
        if (current_event->device_states[1]) lv_obj_add_state(ui_SprayerSwitchSche, LV_STATE_CHECKED);
        else lv_obj_clear_state(ui_SprayerSwitchSche, LV_STATE_CHECKED);
        
        lv_slider_set_value(ui_PumperSliderSche, current_event->device_levels[2], LV_ANIM_OFF); 
        if (current_event->device_states[2]) lv_obj_add_state(ui_PumperSwitchSche, LV_STATE_CHECKED);
        else lv_obj_clear_state(ui_PumperSwitchSche, LV_STATE_CHECKED);
        
        lv_slider_set_value(ui_FanSliderSche, current_event->device_levels[3], LV_ANIM_OFF);
        if (current_event->device_states[3]) lv_obj_add_state(ui_FanSwitchSche, LV_STATE_CHECKED);
        else lv_obj_clear_state(ui_FanSwitchSche, LV_STATE_CHECKED);

    } else {
        // --- CHẾ ĐỘ THÊM MỚI (NEW) ---
        lv_label_set_text(ui_EventLabel, "Label:");
        
        // Đặt giá trị mặc định/reset
        lv_textarea_set_text(ui_EventText, "");
        lv_roller_set_selected(ui_FromRollerHour, 0, LV_ANIM_OFF);
        lv_roller_set_selected(ui_FromRollerMinute, 0, LV_ANIM_OFF);
        // ... (Đặt mặc định cho tất cả các widget khác)
        lv_slider_set_value(ui_LightSliderSche, 0, LV_ANIM_OFF);
        lv_obj_clear_state(ui_LightSwitchSche, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Checkbox1, LV_STATE_CHECKED); 
    }
    char date_str[100];
    
    // 1. Tính toán Thứ của ngày được chọn
    int dow = get_day_of_week(g_selected_date.year, g_selected_date.month, g_selected_date.day);
    const char* day_name = get_day_name(dow);
    
    // 2. Tạo chuỗi hoàn chỉnh: "Thứ X, Ngày/Tháng/Năm"
    sprintf(date_str, "%s %02d/%02d/%04d", 
            day_name, 
            g_selected_date.day, 
            g_selected_date.month, 
            g_selected_date.year);
    
    // 3. Gán chuỗi vào Label
    if (ui_Label100 != NULL) { 
        lv_label_set_text(ui_Label100, date_str);
    }
}
void ui_event_OkeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_HourPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SaveButtonSche(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        
        int start_hour = lv_roller_get_selected(ui_FromRollerHour);
        int start_minute = lv_roller_get_selected(ui_FromRollerMinute);
        int end_hour = lv_roller_get_selected(ui_ToRollerHour);
        int end_minute = lv_roller_get_selected(ui_ToRollerMinute);
        
        // 2. Tính tổng số phút để so sánh
        int start_total_minutes = start_hour * 60 + start_minute;
        int end_total_minutes = end_hour * 60 + end_minute;

        // 3. KIỂM TRA LOGIC: Giờ kết thúc <= Giờ bắt đầu
        if (end_total_minutes <= start_total_minutes) {
            
            // Lỗi: Giờ kết thúc không hợp lệ
            //Serial.println("VALIDATION ERROR: End time must be greater than start time.");
            
            // Hiện Panel cảnh báo
            _ui_flag_modify(ui_HourPanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
            
            return; // KHÔNG gọi logic save
            
        }


        // Dùng saved_event để thu thập dữ liệu từ UI
        scheduler_event_t saved_event = {0}; 
        bool save_successful = false;
        
        // --- 1. Thu thập dữ liệu từ Widgets ---
        
        // Lấy tên Event
        const char * label = lv_textarea_get_text(ui_EventText);
        strncpy(saved_event.label, label, sizeof(saved_event.label) - 1);
        saved_event.label[sizeof(saved_event.label) - 1] = '\0';
        
        // Lấy thời gian (Rollers)
        char roller_str[5]; 
        lv_roller_get_selected_str(ui_FromRollerHour, roller_str, sizeof(roller_str));
        saved_event.start_hour = (uint8_t)atoi(roller_str);
        
        lv_roller_get_selected_str(ui_FromRollerMinute, roller_str, sizeof(roller_str));
        saved_event.start_minute = (uint8_t)atoi(roller_str);

        lv_roller_get_selected_str(ui_ToRollerHour, roller_str, sizeof(roller_str));
        saved_event.end_hour = (uint8_t)atoi(roller_str);

        lv_roller_get_selected_str(ui_ToRollerMinute, roller_str, sizeof(roller_str));
        saved_event.end_minute = (uint8_t)atoi(roller_str);
        
        // Lấy trạng thái Repeat & Enable
        saved_event.repeat_weekly = lv_obj_has_state(ui_Checkbox1, LV_STATE_CHECKED);
        saved_event.is_enabled = true; // Mặc định bật khi Save

        // Lấy trạng thái và level thiết bị (Sliders và Switches)
        // 0: LIGHT | 1: SPRAYER | 2: PUMP/PUMPER | 3: FAN
        saved_event.device_levels[0] = (uint8_t)lv_slider_get_value(ui_LightSliderSche);
        saved_event.device_states[0] = lv_obj_has_state(ui_LightSwitchSche, LV_STATE_CHECKED);
        
        saved_event.device_levels[1] = (uint8_t)lv_slider_get_value(ui_SprayerSliderSche);
        saved_event.device_states[1] = lv_obj_has_state(ui_SprayerSwitchSche, LV_STATE_CHECKED);
        
        saved_event.device_levels[2] = (uint8_t)lv_slider_get_value(ui_PumperSliderSche);
        saved_event.device_states[2] = lv_obj_has_state(ui_PumperSwitchSche, LV_STATE_CHECKED);
        
        saved_event.device_levels[3] = (uint8_t)lv_slider_get_value(ui_FanSliderSche);
        saved_event.device_states[3] = lv_obj_has_state(ui_FanSwitchSche, LV_STATE_CHECKED);



        
            saved_event.year = g_selected_date.year;
            saved_event.month = g_selected_date.month;
            saved_event.day = g_selected_date.day;
            
            saved_event.active_days = 0;


        // --- 2. Thêm mới hoặc Chỉnh sửa vào Event List ---
        if (g_event_edit_index == -1) {
            // CHẾ ĐỘ THÊM MỚI
            if (event_count < MAX_SCHEDULE_EVENTS) {
                event_list[event_count] = saved_event; // Gán vào vị trí mới
                event_count++;
                Serial.printf("New Event added: %s\n", saved_event.label);
                save_successful = true;
            } else {
                Serial.println("ERROR: Maximum number of events reached! Cannot save.");
                // Có thể thêm hiển thị thông báo lỗi trên UI ở đây
            }
        } else {
            // CHẾ ĐỘ CHỈNH SỬA
            if (g_event_edit_index >= 0 && g_event_edit_index < event_count) {
                event_list[g_event_edit_index] = saved_event; // Ghi đè vào index cũ
                Serial.printf("Event at index %d updated: %s\n", g_event_edit_index, saved_event.label);
                save_successful = true;
            } else {
                Serial.println("ERROR: Invalid index for editing!");
            }
        }

        // --- 3. Lưu mảng Event đã cập nhật vào NVS ---
        if (save_successful) {
            if (save_event_list()) {
                Serial.println("Event list persisted successfully to NVS.");
            } else {
                Serial.println("CRITICAL ERROR: Failed to save event list to NVS.");
            }
        }

        // --- 4. Chuyển màn hình về Screen 7 ---
        // (Luôn chuyển màn hình, ngay cả khi save không thành công để thoát khỏi Editor)
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_SchedulerButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_SwitchButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_WifiButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}

////main UI init function

void SwitchDataUI(){
    for(int i = 0; i < 8; i++){
        lv_label_set_text(ui_LabelSwitch[i], switch_data_array[i].schedule);
        if (switch_data_array[i].state == true) lv_obj_add_state(ui_Switch[i], LV_STATE_CHECKED);
        PCF8574_WritePin(i, switch_data_array[i].state);
    }
}


///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen5_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    //ui_Screen3_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    setup_global_ui_arrays();
    ui____initial_actions0 = lv_obj_create(NULL);
    // SwitchDataUI();
    if(wifi_setting.connected) lv_disp_load_scr(ui_Screen1);
    else{
        lv_disp_load_scr(ui_Screen6);
        // _ui_flag_modify(ui_Panel17, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}


void delete_event(int32_t index) {
    // Đảm bảo index hợp lệ
    if (index >= 0 && index < event_count) {
        // Di chuyển các phần tử sau index lên trước (logic xóa khỏi mảng)
        for (size_t i = index; i < event_count - 1; i++) {
            event_list[i] = event_list[i + 1];
        }
        event_count--;
        save_event_list(); // Lưu NVS
        Serial.printf("Event at index %d deleted: %s\n", index, event_list[index].label);
    }
}

// --- LOGIC CHUYỂN SCREEN VÀ XỬ LÝ DỮ LIỆU ---

// 1. Chuyển sang Screen 8 EDIT (Config/Seen Button)
void ui_event_ConfigEvent_Handler(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        // Lấy Event Index đã được lưu trong user_data của nút
        g_event_edit_index = (int32_t)lv_obj_get_user_data(target);
        
        // Chuyển sang Screen 8 (sẽ tải dữ liệu cũ lên do g_event_edit_index >= 0)
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}

// 2. Chuyển sang Screen 8 NEW (Add Button)
void ui_event_AddButton_New(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        size_t current_active_count = count_active_events_for_date();
        
        // 2. Kiểm tra nếu đã đạt đến giới hạn hiển thị tối đa (MAX_VISIBLE_EVENTS)
        // Chúng ta sử dụng MAX_VISIBLE_EVENTS (ví dụ: 10) làm giới hạn hợp lý cho UI
        if (current_active_count >= MAX_VISIBLE_EVENTS) {
            
            // HIỂN THỊ CẢNH BÁO MAX EVENT
            
            // Giả định Panel cảnh báo là ui_MaxWarningPanel
            if (ui_MaxWarningPanel != NULL) { 
                 _ui_flag_modify(ui_MaxWarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
                 // Bạn có thể thêm logic cập nhật Label cảnh báo tại đây
                 Serial.println("WARNING: Cannot add more events. Max visible limit reached.");
            } else {
                 Serial.println("ERROR: ui_MaxWarningPanel is NULL.");
            }
            
            // Không chuyển màn hình (END FUNCTION)
            return; 
        } 
        
        // 3. Nếu chưa đạt giới hạn, tiến hành chuyển sang Screen 8 (ADD NEW)
        g_event_edit_index = -1; // Đánh dấu là Thêm mới
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}

// 3. Toggle Switch (Bật/Tắt Event)
void ui_event_EventSwitch_Toggle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    // Sử dụng LV_EVENT_VALUE_CHANGED vì đây là Switch
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        // Lấy Event Index đã được lưu trong user_data của switch
        int32_t event_index = (int32_t)lv_obj_get_user_data(target);
        
        if (event_index >= 0 && event_index < event_count) {
            bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
            
            // Cập nhật trạng thái và lưu NVS
            event_list[event_index].is_enabled = state;
            save_event_list();
            
            Serial.printf("Event %s toggled to %s\n", event_list[event_index].label, state ? "ON" : "OFF");
        }
    }
}

// --- LOGIC XÁC NHẬN XÓA (Warning Panel) ---

// 4. Nút Delete (Hiện Warning Panel)
void ui_event_DeleteEvent_Handler(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        // 1. Lấy Index Event từ User Data của nút
        int32_t index_to_delete = (int32_t)lv_obj_get_user_data(target);
        
        // 2. Lưu index vào biến toàn cục cho hàm xác nhận
        g_event_edit_index = index_to_delete; 
        
        // 3. Cập nhật Label xác nhận
        if (g_event_edit_index != -1 && g_event_edit_index < event_count) {
             char msg[100];
             sprintf(msg, "Do you want\n to delete event: %s?", event_list[index_to_delete].label);
             lv_label_set_text(ui_WarningLabel, msg);
        }
        // 4. Hiện Warning Panel
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// 5. Nút YES (Thực hiện xóa)
void ui_event_YesButton_Delete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if (g_event_edit_index != -1) {
            delete_event(g_event_edit_index); // Xóa Event và lưu NVS
            g_event_edit_index = -1; // Reset index
        }
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        update_screen7_event_list(); // Cập nhật lại danh sách trên UI
    }
}

// 6. Nút NO (Hủy xóa)
void ui_event_NoButton_Delete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WarningPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        g_event_edit_index = -1; // Reset index
    }
}