// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DA_KTMT

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_GREEN 0

#define UI_THEME_DEFAULT 0

extern ui_theme_variable_t _ui_theme_color_green[1];
extern ui_theme_variable_t _ui_theme_alpha_green[1];

extern uint32_t * ui_theme_colors[1];
extern uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
